### ISSUE TITLE
Endless syncing...

### ISSUE THREAD

**Issue by akmalwest** [Chia-Network/chia-blockchain#10302]
The syncing process is never ending, i tried restarting the comp several times, tried deleting the plots from the app, but no success. pfa
![Capture](https://user-images.githubusercontent.com/82469293/154687247-4b4c29b8-5357-411b-a50f-4e7860ef2266.PNG)

**Comment by shaneo257** [comment]
what OS do you have?

**Comment by akmalwest** [comment]
Windows

**Comment by shaneo257** [comment]
WINDOWS BLOCKCHAIN DATABASE RESET

Close down the Chia app, and open up a PowerShell window, and execute the below command:

`mv ~\.chia\mainnet\db\block* ~\Desktop\`

Then try opening up the Chia app again

If it worked, you can remove the files we put on the Desktop!

**Comment by akmalwest** [comment]
![Capture2](https://user-images.githubusercontent.com/82469293/154787207-9b7e0b51-b814-46f5-bdbd-e9925735d000.PNG)

**Comment by akmalwest** [comment]
@shaneo257 please see the screenshot, it looks like it is not working

**Comment by shaneo257** [comment]
ok, close the client, then go to C:\Users\AS\.chia\mainnet\db and either move or delete the files in this folder, then restart your client

**Comment by zeniff12** [comment]
I have the exact same issue, endless syncing for two days now. I tried going to the beta, seemed to make things worse. Had my chia at 0 and didn't show the Pooling or Keys tabs in the GUI. Also didn't sync and the syncing numbers were orange instead of yellow. Show I reinstalled client 1.2.11 and it still did the endless sync. So I tried the following suggested fix suggested earlier by shaneo257

> ok, close the client, then go to C:\Users\AS.chia\mainnet\db and either move or delete the files in this folder, then restart your client

Now Chia is syncing, but starting from 0. Have to wait for 1,587,000. This will take forever.

Another thing, once I redownloaded the UI it doesn't show me connected to Space Poll any longer. I'm hoping that will be a simple fix.

**Comment by shaneo257** [comment]
> Still the same...

were you able to start syncing, or is it still at 0?

**Comment by shaneo257** [comment]
> I have the exact same issue, endless syncing for two days now. I tried going to the beta, seemed to make things worse. Had my chia at 0 and didn't show the Pooling or Keys tabs in the GUI. Also didn't sync and the syncing numbers were orange instead of yellow. Show I reinstalled client 1.2.11 and it still did the endless sync. So I tried the following suggested fix suggested earlier by shaneo257
> 
> > ok, close the client, then go to C:\Users\AS.chia\mainnet\db and either move or delete the files in this folder, then restart your client
> 
> Now Chia is syncing, but starting from 0. Have to wait for 1,587,000. This will take forever.
> 
> Another thing, once I redownloaded the UI it doesn't show me connected to Space Poll any longer. I'm hoping that will be a simple fix.

once its synced, it'll show you reconnected to spacepool

**Comment by akmalwest** [comment]
It started syncing, it's been syncing since yesterday

**Comment by stefan-lange** [comment]
Maybe https://chia-database.com could help. It is the blockchain endpoint the machiaris app uses for initial download. Can you trust it? I don't know, it's a personal decision.

**Comment by DrakeFS** [comment]
> Maybe ... could help. It is the blockchain endpoint the machiaris app uses for initial download. Can you trust it? I don't know, it's a personal decision.

Please do not link direct downloads of the blockchain file.  Not only is it unsafe but circumvents security measures of the blockchain (not getting the DB from one single source).

**Comment by stefan-lange** [comment]
> > Maybe ... could help. It is the blockchain endpoint the machiaris app uses for initial download. Can you trust it? I don't know, it's a personal decision.
> 
> Please do not link direct downloads of the blockchain file. Not only is it unsafe but circumvents security measures of the blockchain (not getting the DB from one single source).

Yep, it's biggest advantage is - in the same moment - it's biggest disadvantage in point of security.

**Comment by zeniff12** [comment]
So, my situation at least, I just decided to let it go through the sync process and didn't want to try the link that could have a security issue. It was going good for about a day, then just stopped. Then under status it just said 'Not Synced' in red. It showed this same thing before I began trying the fix as well when my internet was out for a bit. Never tried to start syncing again once it showed 'Not Synced' in red, hence when I restarted the GUI to try to get it going again it just went into the current issue of the endless sync of 0/1,587,000. 

So, after seeing the red 'Not Synced' again just now, I restarted the GUI again to see if it would work, and luckily enough it came back with where it had left off at 840,000/1,580,000 (not exact, but just giving numbers as a reference of how far it got after a day of syncing). And it started syncing again as well. 

My worry, though, is that if my internet goes out again or becomes spotty again, or I have to restart because of a windows update, will I have to go through this all over again because the bug seems to still be there. Basically just hoping this bug can get worked out soon. 

Thanks for all the helpful input.

**Comment by akmalwest** [comment]
![Capture4](https://user-images.githubusercontent.com/82469293/154867484-1d7cdafe-3ec0-4943-96f8-bf3b040458c5.PNG)

**Comment by akmalwest** [comment]
@shaneo257 this is what i got after 2 days of waiting it to sync(((. What can i do to get it fixed??

**Comment by zeniff12** [comment]
@akmalwest I have had the same thing happen to me 3 times now while trying to resync. I have shut down the GUI and reopened it. Each time it has started to sync again. But it kinda has me worried that it will continue to do this on a daily basis even once synced.
