### ISSUE TITLE
[Bug] INVALID_FEE_TOO_CLOSE_TO_ZERO

### ISSUE THREAD

**Issue by luis360** [Chia-Network/chia-blockchain#10352]
### What happened?

create_signed_transaction:
{additions: [{amount: amount, puzzle_hash: puzzlehash}], fee: 50000000}

error: INVALID_FEE_TOO_CLOSE_TO_ZERO

### Version

1.2.11

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by ekkyai** [comment]
I has this issue this morning and didn't get pay. How can I get help?

**Comment by emlowe** [comment]
We need to fix some of the error messages here. 
This is when the mempool is full, and your transaction is rejected because the fee is actually too low, at some point all fees below a certain threshold are all treated as zero. The wallet will retry this transaction, so it should eventually go through. If you want you can delete all pending transactions and then retry the transaction but add a larger fee.

**Comment by nbauernfeind** [comment]
It would be helpful if the error message could include some statistics about current fees in the mempool. It should at least show the minimum fee to be included into the mempool. Ideally, it would estimate the expected fee to process the transaction over a few periods of time (e.g. next 5m. 30m, 1hr, 12hrs).
