### ISSUE TITLE
[Bug] Fix strange error message when a transaction would result in using too many coins

### ISSUE THREAD

**Issue by cmmarslender** [Chia-Network/chia-blockchain#10440]
### What happened?

When trying to consolidate extra CH21 CATs to a new wallet, to prepare to melt the rest back to XCH, I got some errors around max send size. The error happening is not an issue (I didn't expect to be able to send them all at once). The issue is more that the number in the error doesn't really correspond to any particular value of the CAT coins.

![Screen Shot 2022-02-24 at 4 25 04 PM](https://user-images.githubusercontent.com/1915905/155813585-978dc3f9-f218-48bc-8ebc-3bf945c2048c.png)

If I take the number and divide by 1000 (assuming its actually the number of underlying mojos I can send), the error no longer shows up, and instead, the UI goes into a "stuck" state. "SEND" button just gets stuck with a spinner. At this point, the logs show:

`2022-02-24T19:30:03.428 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'INVALID_BLOCK_COST'`

Even though the transaction was rejected, the wallet still shows it as pending.

I did some testing at 125,000 CH21 (128 coins), 100,000 (108 coins), and 75,000 (83 coins) and once I got down to 75k, the send was finally accepted by the full node.

I think this is possibly a few issues:

- The "can't send more than" value doesn't appear to correspond to the units of the CAT we're trying to send
- The "can't send more than" value, even when divided by 1000 to get the number of the CAT, is still rejected by the full node - maybe the math for the coin limit doesn't take into account the different cost of sending a cat vs XCH?

### Version

1.3.0-beta3

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
Yes. I believe this actual error is because it selected too many individual coins and the reported number is the total number of mojos from the coins that could be selected (this isn't particularly helpful). I think the number of CAT coins in a single transaction should be around 166 coins. This is based on the logic in `get_max_send_amount()` in cat_wallet.py. The max cost is set as `MAX_BLOCK_COST_CLVM / 2` or `11000000000 / 2` = `5500000000`. Then each coin selected raises the cost by the standard TX for the cat wallet. I have this as `33118915` in one of my log files (it should be output at INFO level). This comes to `5500000000 / 33118915` or 166 coins 

But for sure this error isn't particularly helpful

**Comment by emlowe** [comment]
The problem is that this error `raise ValueError(f"Can't send more than {max_send} in a single transaction")` isn't particularly helpful at all (see instances in wallet.py and cat_wallet.py)

I might suggest something like:

Can not send {amount_requested) in a single transaction. This would require more than {num_coins} coins. You can safely send {max_send} amount.
