### ISSUE TITLE
[Bug]升级1.3正式版后，奖励地址为空 (Manage Farming Rewards)

### ISSUE THREAD

**Issue by heiseshupo** [Chia-Network/chia-blockchain#10587]
### What happened?

升级1.3正式版后，点开管理耕种-耕种奖励发放地址-地址为空，手动添加保存后依旧为空！

错误提示本机没有所输入地址对应的私钥。请确认是否要将奖励发送至非本机钱包。

会影响爆块，收到奖励
![F304A5B93A876A9FEB29512BBB1F6F8F](https://user-images.githubusercontent.com/81500563/157188353-8d418158-6d4e-4751-85fa-a59a8e0468da.jpg)
？

### Version

1.3正式版

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by jackwalk** [comment]
Same question

**Comment by loppefaaret** [comment]
Can you please verify the `xch_target_address:` in your `config.yaml` under both the `farmer:` and `pool:` sections

**Comment by loppefaaret** [comment]
i got this on my own Windows 1.3 release 
it appears to be a display bug, that just shows the 2 reward address boxes empty, even if there is an address present in `config.yaml`
setting a new address using the GUI, will update the address in `config.yaml`
but returning to the "manage farming rewards" pane, shows both address boxes empty again

**Comment by loppefaaret** [comment]
Complete fresh Debian install, with a fresh 1.3.0 release install, results in the same blank "Manage farming reward addresses"

**Comment by xkredr** [comment]
Issue was already was there in the 1.3 Beta’s… I tried Beta 1 on Ubuntu 20.04.
Noticed the not shown reward addresses and the warning on 'no private keys for one or both addresses' but didn’t really pay attention as I figured it would be reported and solved in the final release.
Should have reported a bug on github of course, but I guess nobody did (thinking someone else would).

It appears to be a bug in the GUI itself, you can set and save reward addresses in config.yaml from the GUI, but it does not show them afterwards.

I just wonder what Chia means by Beta testing, is there an installed base of known Beta testers that missed this?
Or are they just throw a Beta in the community and hope for the best…

**Comment by emlowe** [comment]
There is no specific cohort of beta testers - we rely on the community for reports, and as you said no-one reported this.
Also yes we apparently missed this internally as well.
However, your address in config.yaml should be listed properly

**Comment by xkredr** [comment]
@emlowe Thanks for the swift reply. 
Lots of features/changes/improvements otherwise so still a great update I think. 
One thing in the release notes I'm still trying to get my head around is this, specifically the first bullet point.... this added to the confusion from the now identified bug. Better to say what to expect, instead of not not. Makes no sense to me now.

Changed the behavior of what info is displayed if the database is still syncing.

-     It should not be expected that wallet info, such as payout address, should not reflect what their desired values until everything has completed syncing.
-    The payout instructions may not be editable via the GUI until syncing has completed.___

**Comment by emlowe** [comment]
Lol - yea I have no idea what that is trying to say either...

I believe it's trying to say:

Please wait until your wallet is fully synced before checking the correctness of wallet information such as payout addresses and balances, as items may change as the wallet syncs

**Comment by radchenk0** [comment]
Hello, my five cents, hope it could somehow help to resolve the issue.

When I click on "manage farming rewards" it fails to load because of the following error:

```
buildThunks.ts:361 TypeError: Cannot read properties of undefined (reading 'searchForPrivateKey')
    at Object.query (farmer.ts:42)
    at buildThunks.ts:288
    at apiState.ts:34
    at Object.next (apiState.ts:34)
    at apiState.ts:34
    at new Promise (<anonymous>)
    at T (apiState.ts:34)
    at c (buildThunks.ts:266)
    at createAsyncThunk.ts:605
    at index.js:32
```
    
There are a couple of screenshots that could help

![image](https://user-images.githubusercontent.com/23620645/158015035-73fedba0-e1df-48a6-8eb8-ae9a99c32981.png)

![image](https://user-images.githubusercontent.com/23620645/158015026-f5918ff5-1819-4c3f-bdee-2e073383e842.png)
