### ISSUE TITLE
Upgraded main node to 1.3.0 - DB still to large and cannot join pool[Bug] 

### ISSUE THREAD

**Issue by mrxzius** [Chia-Network/chia-blockchain#10667]
### What happened?

I upgraded my main node to 1.3 ( took 36 hs or less...) but i found some issues:
1) DB file is at the same size as 1.2.11 ( 73 GB aprox) - I upgraded on another machine and DB is 40GB
2) cant seem to connect to pool... even when i try to connect, its stays pending ( for a long time)

![image](https://user-images.githubusercontent.com/79389443/157859475-1700ded5-054e-43a5-bba3-8d8533d9de97.png)

### Version

1.3.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by lincolnthalles** [comment]
Are you trying to change pools? This is probably related to [this github issue](https://github.com/Chia-Network/chia-blockchain/pull/10631) , which is already being adressed. It is related to config.yaml writing issues.
Close Chia, delete files within `%USERPROFILE%\.chia\mainnet\wallet\db` and try this build (download Windows-Installers artifact): https://github.com/Chia-Network/chia-blockchain/suites/5617738836/arifacts/182844512

The command `chia db upgrade` doesn't delete any files by itself.
To free up to 70GB, go to `%USERPROFILE%\.chia\mainnet\db` and check if the file `blockchain_v2_mainnet.sqlite` is there. If it is, you may delete `blockchain_v1_mainnet.sqlite`. If the `v2` blockchain file isn't there, it means your upgrade failed. You may run `chia db upgrade` again or copy the v2 blockchain from your other node that is running fine.
Note that if you copy the v2 blockchain manually, you need to edit config.yaml and replace `db/blockchain_v1_CHALLENGE.sqlite` with `db/blockchain_v2_CHALLENGE.sqlite` on full_node.database_path, otherwise it will start syncing the v1 blockchain again.
When everything is synced, it should work as expected.

**Comment by mrxzius** [comment]
I downgraded to V 1.2.11 and it appears to have the wallet stuck at syncing.... will try to do later the instructions you proposed...


![image](https://user-images.githubusercontent.com/79389443/157939901-288790d1-10c2-4f35-80d2-0ca3c9de030b.png)

![image](https://user-images.githubusercontent.com/79389443/157940923-6bf95e97-0fed-40fb-a541-98d02c73d816.png)
![image](https://user-images.githubusercontent.com/79389443/157941144-3ce3b1f2-b991-407c-af07-862c3829ccc6.png)

![image](https://user-images.githubusercontent.com/79389443/157941770-90e5207d-1f08-48bf-8d00-02b9d032fe7b.png)
apparently pool seems to be working... but not the wallet...
