### ISSUE TITLE
Breaking change in `CoinRecord` deserialization from json with v1.3.0

### ISSUE THREAD

**Issue by felixbrucker** [Chia-Network/chia-blockchain#10753]
Before 1.3.0 the `CoinRecord` contained a `spent` property, which was included in the serialized json and required for deserialization from json.
With 1.3.0 this property is now a computed property and deserialization fails, if `spent` is included in the json.

Ideally it would ignore any `spent` in the json starting with 1.3.0 instead of crashing:
```
KeyError: 'spent'
```

**Comment by arvidn** [comment]
I think I may have been responsible for removing this. the `CoinRecord` type is defined in `chia/types/coin_record.py` (rather than under `chia/types/blockchain_format/`) which made me think it wasn't part of a protocol requiring backwards compatibility.

Do you have a stack trace for where that key error is thrown from?
I would expect that using the new version of `CoinRecord`, a json parser wouldn't be looking for a `spent` field anymore either. So I'm curious who the client is, looking for this field.

The new `CoinRecord` class doesn't contain the `spent` field, but instead it has a property that give you the same value, so the class should be backwards compatible, just not the serialization.

**Comment by arvidn** [comment]
oh, I think I misread the issue. The problem is that the parser for the *new* type is failing when reading a stored entry for the *old* type. And the storing of this type is done by a 3rd party, so nothing we have control over. is that right?

**Comment by arvidn** [comment]
@Quexington looking at this a bit. I notice you mitigated this in our RPC by deleting the `spent` field before parsing the json. Did you consider making the json parser tolerate unknown fields but decided against that approach?

**Comment by Quexington** [comment]
I definitely did not think about changing the whole JSON parser to ignore unknown fields I thought that might be taboo since streamable works a very specific way and maybe would like to fail on unknown fields I just wasn't sure.  We could definitely add an override for the CoinRecord object though, I didn't realize that the objects we export are subject to breaking changes as well.

**Comment by arvidn** [comment]
@felixbrucker do you pass in an old CoinSpend json blob to any API call, that's failing? can you describe, more specifically, where this failure happens?

It's not obvious to me that we provide guarantees that our parser will be backwards compatible, but I believe we do for the APIs.

**Comment by felixbrucker** [comment]
I'm not sure if there is a rpc call that accepts coin records in chia-blockchain, i just noticed this unexpected behaviour in my own rpc api using the chia-blockchain as a library for types and serialization/deserialization.

It's not obvious to me a json parser should crash if there are additional unused keys in an object, and really it should not.
