### ISSUE TITLE
update CHIA lost transaction[Bug] 

### ISSUE THREAD

**Issue by Udovan51** [Chia-Network/chia-blockchain#11921]
### What happened?

After update chia to 1.3.5 all transaction between november 9. 2021 and june 3. 2022 are lost. more than 10 XCH.
What should I do to solve this problem?

<img width="706" alt="image" src="https://user-images.githubusercontent.com/107579507/173902396-109ca1fa-ba1c-4c63-8e96-22a856f7c295.png">

### Version

1.3.5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by desenvolvedorze** [comment]
Today when I went to consult my farmer. I had also lost 1.5 xch that I had managed to farm in the last 40 days... Can anyone explain if there was a hack on the network? I'm afraid to stay.

**Comment by mixkelvin** [comment]
use another PC，update wallet，you'll find your coin

**Comment by scrutinously** [comment]
The problem is caused by your wallet requesting coin records from other nodes, then the other node drops the connection between the request for records and actually providing them. Your wallet then does not know about these missing coin records. 

The best solution for this is to only have your wallet sync off your own full node by editing the config.yaml, under the wallet: section you want `connect_to_unknown_peers: false`. If the line is set to true, change to false, if it isn't there at all, add it. After that is set, delete the wallet database (not the full blockchain database) located at `.chia/mainnet/wallet/db` to force the wallet to resync off of your own full node, which should pull all coin records without dropping any.
