### ISSUE TITLE
[Bug] "Series" nomenclature is used in place of the intended "Edition"

### ISSUE THREAD

**Issue by sargonas** [Chia-Network/chia-blockchain#12227]
### What happened?

CHIP-0005 calls for the use of "Editions" on NFTs, where one can establish an "X of Y" count. (Ie 1 of 20, 2 of 20, etc). It also establishes a "Series" is a grouped collection of different NFTs. An Edition is intended to be 1 of either 1 _or_ many of the exact same NFT, within a Series of many Editions.

Example: A Series of pictures of fruit would have 10 unique NFTs, Apple is 1 of the series of 10, a Banana is 2 of 10, and an Orange is 3 of 10 in the Series, etc. The Apple has 50 identical images, and of the Editions of Apples each are 1 of 50, 2 of 50, etc. (This would result in a total of 500 actual NFT objects.)

The Chip-0005 spec calls for proper handling of Editions, and framework was built to support it in both the CLI and RPC. However, somewhere along the way the features was re-labeled as "Series" which is the wrong definition and, as above, has a different meaning. Subsequently, the Wallet GUI also references this on-chain data as "Series number" when it _should_ state "Edition"

Proposed Solution: 

1. Correct all references from "Series" to "Edition" at the core level (--help output, internal code references, etc)
2. Update the GUI to refer to this field as "Edition" and not "Series"
3. Either update the command line flags of -st and -sn to -et and -en, or add them as additional ones for backward compatibility.
4. _(Separate from this repo)_ update all developer documentation to properly reference Editions in place of Series and make clear the intended use-case.

### Version

1.4

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by eFishCent** [comment]
I recommend that the -st and -sn flag gets deprecated with an error message to use -et and -en. This way when we do need to use Series in the future, it can be supported.

**Comment by danieljperry** [comment]
@wriches @cameroncooper @sargonas 
I have updated several documents with these changes.

NFT1 modified since last commit:
https://github.com/Chia-Network/chips/pull/19/commits/9726fdc8924269c70b3a221269a9250445477050

Developer reference:
https://github.com/Chia-Network/chia-docs/pull/132

Developer guide:
https://github.com/Chia-Network/chia-dev-guides/pull/13

For the RPCs, I'm suggesting we Deprecate `series_number` and `series_total` and replace them with `edition_number` and `edition_count`
For the CLI I'm suggesting we Deprecate `--series-number` and `--series-total` and replace them with `--edition-number` and `--edition-count`

The CHIP and references now have a better explanation for what "Edition" and "Series" mean as well.

**Comment by danieljperry** [comment]
Please check with development to make sure these suggested name changes and deprecations make sense.

**Comment by wriches** [comment]
Resolved by #12727 and #12904.
