### ISSUE TITLE
[Bug] stuck loading configuration at programm start

### ISSUE THREAD

**Issue by Hermes88** [Chia-Network/chia-blockchain#12313]
### What happened?

![1](https://user-images.githubusercontent.com/55690272/178341083-62f155ba-bdd0-448c-b841-7f7a7362a5a8.png)
![2](https://user-images.githubusercontent.com/55690272/178341109-14feb08f-83fa-4e26-a2d9-30bc7775319e.png)
I have already tried several times different versions of the installation files for macos from the official chia website. Every time the same problem, when you open the program, the configuration takes a very long time to load and stops there, I tried to leave it for a long time, but nothing changes. Computer operating system and other is below
![MS Paint _ Microsoft Paint Online](https://user-images.githubusercontent.com/55690272/178341688-38828e6d-ad9e-4e7f-9d77-103e2951cad6.png)

### Version

1.4.0

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
Sorry for the confusion. All of the 1.4.0+ Mac Intel builds on the downloads page are for `Catalina 10.15 and later` due to some incompatibilities with the library versions that are included with the version of MacOS that our runners use.

You should still be able to install from source to get things working on your system https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#install-from-source---macos

**Comment by Hermes88** [comment]
so i need to install how here is written? 
https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#install-from-source
why so hard, i am not a programmer, see i need to install python first and then do some hard moves
