### ISSUE TITLE
Created active offers are not displayed after update to 1.5.

### ISSUE THREAD

**Issue by temicus** [Chia-Network/chia-blockchain#12729]
### What happened?

After updating to 1.5. of the Chia GUI for Mac (used as wallet) all my offers are not displayed anymore there. So its not possible to cancel them. If I try to open them there is only option to accept them.

Here is the example of the offer (they are all xch for nft): https://skynft.org/item.php?goback=market&NFTID=nft1ktav676feranp66fsq3u6u6ayae5pmz7kvvy8j47mq043282esfsf4lvje&COLLECTIONID=20220714042138_be371b0cdb4c4703022b9d32004adc25

### Version

Version 1.5.0 | 64 bit For MacOS Intel

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by radchenk0** [comment]
I've experienced the same issue. To be honest I had about 3-4 offers. One was and still be open.
Nothing in the GUI

![image](https://user-images.githubusercontent.com/23620645/182434021-2810c5af-5e44-46ed-8bdb-53a7dda8f085.png)

I mostly interested in open one which id is 5ToPKfAuFVCgo4VsowGDAgkKLNHbRY2M6APQjF3KvsSM

[dexie](https://dexie.space/offers/5ToPKfAuFVCgo4VsowGDAgkKLNHbRY2M6APQjF3KvsSM)

I even tried cancelling it via cli with command

` ./chia.exe wallet cancel_offer -id 5ToPKfAuFVCgo4VsowGDAgkKLNHbRY2M6APQjF3KvsSM`

But I got an error like

**Exception from 'wallet' non-hexadecimal number found in fromhex() arg at position 1**

Side note: 

` ./chia.exe wallet get_offers -id 5ToPKfAuFVCgo4VsowGDAgkKLNHbRY2M6APQjF3KvsSM`

fails with the same error

Can you suggest something? Or tell what I'm doing wrong?

**Comment by wallentx** [comment]
This is expected behavior. You can work around this by 1 of 2 ways:
1) Downgrade to 1.4 and cancel the offer
2) Send all of your coins to yourself, which will change the all offer coins, and invalidate the offer.

**Comment by radchenk0** [comment]
Thanks for the advice. I've managed to transfer it to another address, but still..

I don't understand what means 'expected'. 1.5 version of the UI doesnt show existing offers, is it expected? It seems like a bug, doesn't it?

And pls shed a light why cli commands don't work

**Comment by wallentx** [comment]
I also noticed that the offer ID you were using in the CLI, 5ToPKfAuFVCgo4VsowGDAgkKLNHbRY2M6APQjF3KvsSM, is something unique to Dexie. The offer ID you would use in the CLI would be an ID that is only visible locally to you, which can be found via `chia wallet get_offers` on chia 1.4.
Sorry for the confusion. By "expected", I meant that 1.5.0 uses a new wallet database, and it does not look at the older wallet database for information, therefore it is expected that offers made prior to 1.5.0 are not visible, since that data is in the older database.
