### ISSUE TITLE
[Bug] it is likely that the automatic addition of data layer to a testnet config results in it configured for mainnet

### ISSUE THREAD

**Issue by altendky** [Chia-Network/chia-blockchain#13258]
### What happened?

This came up during a call and has not been verified.  But, if you are configured for testnet without a `data_layer:` section in the config and then you use `chia configure` (need to look back through the code for all relevant cases) I expect it will add a `data_layer:` section configured for mainnet, not testnet.

### Version

release/1.6.0@93354f7ed095285aefbfb54203c4b6f4f520c736

### What platform are you using?

Pi4

### What ui mode are you using?

CLI

**Comment by emlowe** [comment]
This was fixed by #13287 
Tested and confirmed to be working - you can upgrade while configured in testnet and (a) DL files correctly get created with _testnet10 and (b) if you run a `chia configure` command that causes the config.yaml to get written , the data_layer section will have the testnet as `selected_network`
