### ISSUE TITLE
Test Farmer & Harvester in Python3.9

### ISSUE THREAD

**Issue by MumfMeisterT** [Chia-Network/chia-blockchain#13403]
### What happened?

 @wallentx requested this ticket be opened for testing. 

### Version

1.5.1 - 1.6.0

### What platform are you using?

macOS

### What ui mode are you using?

CLI

**Comment by mariano54** [comment]
Can you describe the issue please?

**Comment by wallentx** [comment]
There was some talk in the Whale Farmer Discord about the following scenario:
• A Windows machine with Chia installed via the .exe installer (which is built with Python 3.9) that is running in "Farming mode"
• Remote harvesters running on a different system (OS unknown), with Chia built from source (with Python 3.10).
• Remote harvesters often disconnecting and unable to reconnect consistently, or after reconnecting, no plots showing up

The fix that had been suggested was to downgrade Python on the harvester to 3.9, so that all farmers and harvesters we're running Chia built with the same version of Python.

I had asked around to see if anyone could imagine how this would be a problem, but nobody could say "no" for certain, though they felt it was unlikely.

**Comment by wallentx** [comment]
The issue looks very similar to how https://github.com/Chia-Network/chia-blockchain/issues/13330 is being described.

**Comment by emlowe** [comment]
I'm closing this issue - there isn't enough to debug here and I don't believe there is any problem here. We can reopen if we see further issues.
