### ISSUE TITLE
Add tests for BB2 chia plotters additions

### ISSUE THREAD

**Issue by paninaro** [Chia-Network/chia-blockchain#13521]
Unfortunately we don't have any existing tests to cover the `chia plotters` code. Ideally we would have some tests that cover the new code to whatever extent is possible.

**Comment by wallentx** [comment]
Put em in the venv!

**Comment by ChiaMineJP** [comment]
I considered how to organize test.
I think `pytest` is not appropriate here because how `chia plotters` command works is depending on plotter installation environment.
So I'm now going to update `.github/workflow/test-install-scripts.yml` so that it includes a test for `install-plotter.sh` and `chia plotter` commands.
