### ISSUE TITLE
nft_transfer_nft RPC should be able to resolve an NFT ID to the current coin id

### ISSUE THREAD

**Issue by paninaro** [Chia-Network/chia-blockchain#13861]
Gene was having trouble transferring an NFT on the CLI because he was specifying the NFT ID instead of the current NFT coin id. Ideally the `nft_transfer_nft` RPC should be able to accept an NFT ID and resolve its current coin id.

**Comment by scrutinously** [comment]
Yeah, looking at the wallet_rpc code, it seems like it was initially intended to be the nft_id since it does a check for the nft address type and decodes it, but then it executes `nft_coin_info = await nft_wallet.get_nft_coin_by_id(nft_coin_id)` which uses the coin_name, instead of `nft_coin_info = await nft_wallet.get_nft(nft_coin_id)` which uses the luancher_id. Would be cool if it could use either or so existing scripts would still work too.
