### ISSUE TITLE
Error adding state... list index out of range

### ISSUE THREAD

**Issue by hajes** [Chia-Network/chia-blockchain#14757]
### What happened?

Everything seems to be running without problems. Only thing noticeable is 5-10Wh higher energy consumption after upgrade to 1.7.0, and weird ERROR in log.

### Version

1.7.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... list index out of range
Traceback (most recent call last):
  File "~/chia-blockchain/chia/wallet/wallet_state_manager.py", line 1047, in new_coin_state
    wallet_id, wallet_type = await self.determine_coin_type(peer, coin_state, fork_height)
  File "~/chia-blockchain/chia/wallet/wallet_state_manager.py", line 662, in determine_coin_type
    await self.notification_manager.potentially_add_new_notification(coin_state, coin_spend)
  File "~/chia-blockchain/chia/wallet/notification_manager.py", line 61, in potentially_add_new_notification
    ] = await self.wallet_state_manager.get_wallet_id_for_puzzle_hash(bytes32(coin_memos[0]))
IndexError: list index out of range
```

**Comment by emlowe** [comment]
This is some unfortunate log spam - these `unhinted` coins that don't have memos should be ignored, however, in 1.7.0 we had this logging get fired when we came across these coins. Other than the log entries this should have no impact on your wallet - this is fixed in the next release (see https://github.com/Chia-Network/chia-blockchain/pull/14590)

Thanks for the report!
