### ISSUE TITLE
farmer chia.farmer.farmer : WARNING  No keys exist. Please run 'chia keys generate' or open the UI.

### ISSUE THREAD

**Issue by mace001** [Chia-Network/chia-blockchain#15091]
Hello all, after problem with not sync, i donwload the latest version of chia app and instal in on the machine, durring the instaltion i dont uninstal old block chain and now my app wont start and show this error. Can someone please explain more about this problem becouse i cant start to farm 

Thanks in advance!

**Comment by MumfMeisterT** [comment]
What version did you have before and what version are you updating to? If you have your 24 word mnemonics keys you can import those directly. 
Otherwise, you will need to revert to version 1.6.2 and run through the key migration flow which it will walk you through, At that point you can update to 1.7.1.

**Comment by emlowe** [comment]
Closing due to lack of response
