### ISSUE TITLE
[Bug] NFT invalid hash

### ISSUE THREAD

**Issue by ChiaNyFarm** [Chia-Network/chia-blockchain#15197]
### What happened?

13 out of 35 of my nfts are saying invalid hash

### Version

1.8.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by Marcello-ch** [comment]
Help; have the same problem with blockchain 1.8.2
![invalid hash](https://github.com/Chia-Network/chia-blockchain/assets/94563437/d62ca871-2694-431f-bd5d-2fee6dc1955e)

**Comment by Marcello-ch** [comment]
Thanks for the reply, but I've already tried without success. I noticed a strange Error in the LOG:2023-08-21T19:37:15.608 full_node full_node_server        : WARNING  Banning 39.107.102.241 for 10 seconds2023-08-21T19:37:40.101 wallet chia.rpc.wallet_rpc_api    : WARNING  NFT wallet 9 has DID 74632edf16f258328d9475cef8bbea44aefe28b53ac573xxxxxxxx but no DID wallet2023-08-21T19:37:40.102 wallet chia.rpc.wallet_rpc_api    : WARNING  NFT wallet 10 has DID e0f14c1311994d51f745f809d72fb023b1f34a2e0xxxxxxxxxxxx    but no DID wallet2023-08-21T19:38:00.455 wallet wallet_server              : WARNING  Banning 5.161.111.235 for 10 seconds2023-08-21T19:38:00.456 wallet wallet_server              : ERROR    Exception Invalid version: '1.6.2-sweet', exception Stack: Traceback (most recent call last):  File "chia\server\server.py", line 483, in start_client  File "chia\server\ws_connection.py", line 222, in perform_handshake  File "packaging\version.py", line 198, in __init__packaging.version.InvalidVersion: Invalid version: '1.6.2-sweet' Maybe it's better if I reinstall everything new? who knows if I fix it?Thanks again for your help Von: JeffGesendet: Montag, 21. August 2023 23:30An: Chia-Network/chia-blockchainCc: Marcello-ch; MentionBetreff: Re: [Chia-Network/chia-blockchain] [Bug] NFT invalid hash (Issue ***@***.*** Please try using the "Refresh NFT data" option from the menu:—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
