### ISSUE TITLE
[Bug] Power surge during IP change

### ISSUE THREAD

**Issue by alphatio** [Chia-Network/chia-blockchain#15733]
### What happened?

I have a full node that connects to many harvesters. The harvesters, in turn, connect to a lot of hard drives (HD). These HDs are connected to the same electrical wires via a single MCB Breaker. Under normal circumstances, the electrical load is stable and does not cause any problems. However, if the HDs run up simultaneously, there will be a surge that could trip the MCB.

The issue arises when the IP is changed, which I believe hinders the full node from syncing and farming, causing a power surge that trips the MCB Breaker. This happens once every couple of weeks, probably due to the ISP.

Is there any way to adjust the **config.yaml** file to "stall" and wait for the connection to be restored?
or initiate harvester in a serial, so it does not surge up in parallel

### Version

1.8.2

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by hbroer** [comment]
does not answer your question but I would not let the drives spin down. That's not good for their health and it does not save much energy because they need a lot of energy to spin up and are not accessible for ~5+ seconds. I have one drive which I can not prevent from sleeping, and it causes every hour or so one or two entries of too slow access. Very bad for I/O. Not sure how to set it in windows. In Linux world you can set each drive to not go to sleep.

**Comment by wjblanke** [comment]
we think your remote harvesters may be connecting to your farmers IP, which is then changed by your ISP. So they won't be able to reconnect to the original IP. What does your network topology look like? are they remote? are u using dyndns?

**Comment by emlowe** [comment]
It isn't clear if there is any software change in Chia can help you. I'm not sure why you think something in the chia software might be causing your issue, which seems entirely specific to your setup. Closing issue
