### ISSUE TITLE
[Bug] Accepted offers stay in the `PENDING_ACCEPT` state

### ISSUE THREAD

**Issue by lourkeur** [Chia-Network/chia-blockchain#15898]
### What happened?

When wallet A creates an offer and it gets accepted, wallet A will show that it sent and received the appropriate amounts, but in `get_offers` the offer will still be marked as `PENDING_ACCEPT` indefinitely.

[This script](https://gist.github.com/lourkeur/878092d9f8cbc123ad22a2d4cf3b921a) is able to reproduce the issue in the simulator.

It could be that this only occurs when both wallets are on the same machine and the user switches between them.

### Version

1.8.0 and later

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

https://gist.github.com/lourkeur/edb8c02a3639d77e0b38a60b1bb1fae2

**Comment by trepca** [comment]
Thanks, but I have tested the wallet and this works fine. 

re simulator, autofarming tends to be too fast for the wallet, so I'd recommend you try to turn it off and farm blocks manually in the script.

**Comment by lourkeur** [comment]
> Thanks, but I have tested the wallet and this works fine.
> 
> re simulator, autofarming tends to be too fast for the wallet, so I'd recommend you try to turn it off and farm blocks manually in the script.

Thanks for the suggestion. I have [rewritten the script to farm manually,](https://gist.github.com/lourkeur/893d165d924e647cc9efbba92d218fab) however it does not make the issue disappear.

**Comment by jack60612** [comment]
> > Thanks, but I have tested the wallet and this works fine.
> > re simulator, autofarming tends to be too fast for the wallet, so I'd recommend you try to turn it off and farm blocks manually in the script.
> 
> Thanks for the suggestion. I have [rewritten the script to farm manually,](https://gist.github.com/lourkeur/893d165d924e647cc9efbba92d218fab) however it does not make the issue disappear.

have you tried recreating the simulator?

**Comment by lourkeur** [comment]
> > > Thanks, but I have tested the wallet and this works fine.
> > > re simulator, autofarming tends to be too fast for the wallet, so I'd recommend you try to turn it off and farm blocks manually in the script.
> > 
> > 
> > Thanks for the suggestion. I have [rewritten the script to farm manually,](https://gist.github.com/lourkeur/893d165d924e647cc9efbba92d218fab) however it does not make the issue disappear.
> 
> have you tried recreating the simulator?

I am not sure what you mean by "recreating the simulator". I just reran the script in a clean environment, it creates the simulator from scratch and the bug is reproduced.

**Comment by wjblanke** [comment]
we will have someone try to reproduce the script and get back to you. thanks

**Comment by Quexington** [comment]
Hey @lourkeur I'm not able to pin down the exact issue with your script unfortunately but I'm pretty confident it's an issue with your script and not with the chia blockhain code.  This line https://github.com/Chia-Network/chia-blockchain/blob/0dde80b89a651c25e0e8f9723ac1ccb0ae4322ee/chia/wallet/trade_manager.py#L154 is the cause of the error in your logs and the fact that it is of length 0 (or the full node doesn't have the coins that it's looking for) is a signal that the wallet (or full node) is in a bad state because that should never be the case.

**Comment by lourkeur** [comment]
> Hey @lourkeur I'm not able to pin down the exact issue with your script unfortunately but I'm pretty confident it's an issue with your script and not with the chia blockhain code. This line
> 
> https://github.com/Chia-Network/chia-blockchain/blob/0dde80b89a651c25e0e8f9723ac1ccb0ae4322ee/chia/wallet/trade_manager.py#L154
> is the cause of the error in your logs and the fact that it is of length 0 (or the full node doesn't have the coins that it's looking for) is a signal that the wallet (or full node) is in a bad state because that should never be the case.

Thank you for your time and your explanation. While it is certainly accurate, it does not help me determine how I should correct my code to not break invariants in the node or wallet. In fact it still seems to me like a bug that was introduced in 1.8 (the behavior is correct in 1.7) because the Chia blockchain code should not allow itself to get into an impossible state. Can you provide more information?

**Comment by Quexington** [comment]
Hey @lourkeur unfortunately like I said I was unable to pin down exactly what was going wrong.  The semantics of the trade manager at that spot should guarantee that that list is never of length 0.  This is why I suggested that the problem was likely in your script and unfortunately we don't really support the use of our code as a library.  The only functionality we try not to break is the RPCs.  In the future this may change but as of now that's the state of things.
