### ISSUE TITLE
[Bug] Using chia 2.0.0 as a dependency in pip on windows fails

### ISSUE THREAD

**Issue by felixbrucker** [Chia-Network/chia-blockchain#16151]
### What happened?

When installing chia 2.0.0 as a dependency using pip on windows it crashes on startup as `chiavdf` depends on `mpir` which is not included in the install in pip:
![grafik](https://github.com/Chia-Network/chia-blockchain/assets/5189997/fa1784ca-73e0-448b-a402-42430ba0ae03)

These are the files missing in a pip installed environment:
![grafik](https://github.com/Chia-Network/chia-blockchain/assets/5189997/97285205-3583-4ab9-9975-1445be19f58e)

### Version

2.0.0

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

```shell
File "C:\some_project\venv\Lib\site-packages\chia\types\blockchain_format\vdf.py", line 10, in <module>
    from chiavdf import create_discriminant, verify_n_wesolowski
ImportError: DLL load failed while importing chiavdf: The specified module could not be found.
```

**Comment by felixbrucker** [comment]
The issue only arises when updating chia-blockchain as it seems the new chiavdf version is not updated/replaced properly by pip and the new dll files are not copied over. As a workaround you can remove and reinstall all dependencies in your venv:
```ps
pip freeze > requirements.txt
pip uninstall -r requirements.txt -y
pip install -e .
```

**Comment by altendky** [comment]
Sorry for the hassle.  I think there are going to be two basic aspects to this.  We have some things that we have changed around our wheel layouts and dependencies and some more things we probably ought to do that could help avoid this in the future, if some of my guesses around the topic are correct.

The other aspect is that, pragmatically, pip is simply not good at handling multiple install calls.  It isn't consistently smart about that like, for example, apt is.  Your best bet for a clean env with the proper dependencies is to delete any existing env instead of updating it, create a new env, update pip, install everything you need with a single call to pip.  I would specifically encourage deleting the env instead of uninstalling things.  Your env should be disposable and you should have whatever you want setup to easily recreate it at a whim.
