### ISSUE TITLE
[BUG] Wallet Tab and Farmer Tab are not synced Windows 1.0.3

### ISSUE THREAD

**Issue by N418** [Chia-Network/chia-blockchain#1657]
**Describe the bug**
Last Height Farmed is different than what's displayed in the Wallet Tab, or there was a block reward didn't get to send to wallet.

**To Reproduce**

1. on [Farm] Tab, Last Height farmed is different than 
2. on [Wallet] Tab, it shows a different Height, crossing checking with chiaexpolorer.com, both height are seems to be farmed from my plots (large size).
3. Both heights are past height 70000

**Expected behavior**
Is there a chance the wallet is not syncing right(syncing with delay)?

- OS: Windows 10
- OS Version/Flavor: 
- CPU: AMD Ryzen 9 5900X
- CHIA version : Windows 1.0.3

**Comment by N418** [comment]
It just happened again. 
in 71xxx range. 

Wallet Tab says 71xxx
Farm Tab says 71xxx-3

Previous behavior was 

Wallet Tab says 70xxx
Farm Tab says 70xxx-5

**Comment by N418** [comment]
Same issue, Wallet Tab and Farm tab are not synced, after reboot.

**Comment by mariano54** [comment]
Rewards actually do not get paid out in the height in which they are farmed, they get paid out a few blocks later
Because not all blocks are transaction blocks
There is a block ever 18 seconds on average but transation blocks evert 47 seconds on average

After winning a block, the very next transaction block will not include your reward, but the one after that will.
So lets say:
100 - block
101- block
102 - tx block
103 - block
104 - block
105 - tx block
Rewards get included in the next next tx block
So block 105 will include rewards for 100, 101, and 102
