### ISSUE TITLE
macOS Chia GUI passphrase doesn't work

### ISSUE THREAD

**Issue by hajes** [Chia-Network/chia-blockchain#16927]
### What happened?

macOS 12.7.1, Chia GUI 2.1.1

passphrase is set
auto-login off

after GUI start, no pass asked...anyone with access to PC can play with wallets

### Version

2.1.1

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
@hajes Can you try restarting your Mac to ensure that all Chia services are stopped, then launch the GUI? The `daemon` process is what's actually responsible for unlocking the keyring (where your keys are stored) -- the GUI simply asks for the passphrase if the daemon needs the keyring unlocked.

Also, is it possible that you clicked the "Save passphrase" checkbox when setting a passphrase? If so, that will make it so that you don't need to enter your passphrase at launch. You can try changing your passphrase to reset the "Save passphrase" setting.

**Comment by hajes** [comment]
it was the "save pass" "problem...removed pass, repeat without "save pass"...works as intended...little bit confusing :-P

**Comment by paninaro** [comment]
Thanks for confirming @hajes.
