### ISSUE TITLE
[Bug] Multiple Daemons running in 2.3.0-rc1 Windows GUI

### ISSUE THREAD

**Issue by OverActiveBladderSystem** [Chia-Network/chia-blockchain#17848]
### What happened?

Windows 10 
Chia 2.3.0-rc1 GUI

Two daemon processes are running (rather than the single daemon process in prior releases), shutting down Chia does remove all processes, rebooting and restarting results in the same two daemons running again.

(See attached photo)

![Screenshot (1612)](https://github.com/Chia-Network/chia-blockchain/assets/36348012/9ade134d-93b4-45c8-a592-b522d95f2577)

File location of the processes in photo

1. C:\Users\username\AppData\Local\Programs\Chia
2. C:\Users\username\AppData\Local\Programs\Chia
3. C:\Users\username\AppData\Local\Programs\Chia\resources\app.asar.unpacked\daemon
4. C:\Users\username\AppData\Local\Programs\Chia
5. C:\Users\username\AppData\Local\Programs\Chia
6. C:\Users\username\AppData\Local\Programs\Chia\resources\app.asar.unpacked\daemon

### Version

2.3.0-rc1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by ChiaMineJP** [comment]
I'll try to reproduce this problem. Give me a moment.

**Comment by ChiaMineJP** [comment]
I couldn't reproduce this problem.

|Case|Result|
|-----|------|
|installed for all users. |Not reproducible|
|installed for individual user. |Not reproducible|
|Restart the GUI after<br/> `keep services running in the background`<br/> is checked for both of the above cases|Not reproducible|
|Source install|Not reproducible|
|Run `.\chia.exe start daemon` after launching the GUI|Not reproducible|

There is a mechanism to prevent multiple daemon processes and it is defined here:
https://github.com/Chia-Network/chia-blockchain/blob/main/chia/daemon/server.py#L1586-L1587
I didn't modify this code.

There is only one tcp port available for daemon process (this is defined in config file). If somehow the above multiple daemon process prevention mechanism didn't work, then how they shared a single tcp port with multiple daemon process?

@OverActiveBladderSystem 
Could you provide me with some more info?
- Command Line column for `chia.exe` in taskmanager. This is expected to be `C:\Users\XXXX\AppData\Local\Programs\Chia\resources\app.asar.unpacked\daemon\chia.exe run_daemon --wait-for-unlock`
- Run the GUI from command prompt / powershell and paste the output here.  
```powershell
cd C:\Users\XXXX\AppData\Local\Programs\Chia\
.\Chia.exe
```
- Please describe how you launched the GUI. Double click the icon? Or from command line?

**Comment by ChiaMineJP** [comment]
@OverActiveBladderSystem Thanks for the logs! Finally I managed to reproduce this issue!
The problem is that `chia start daemon` command dispatched from GUI waits for user input for passphrase to unlock keyring when passphrase is not stored OS's credential store.
This makes sense.

The procedure:
1. User starts GUI
2. GUI invokes `chia.exe start daemon` command
3. The above `chia.exe start daemon` command dispatches `chia.exe run_daemon --wait-for-unlock` command
4. `chia.exe run_daemon` starts daemon process and remains as long as GUI is running.
5. `chia start daemon` confirms that daemon successfully starts then it waits for user input for passphrase which never be done because the prompt is hidden in the background if passphrase protection is enabled and it is not stored in OS's credential store.
6. At this time, in task manager, both `chia.exe run_daemon --wait-for-unlock` and `chia.exe start daemon` appear.  

If you don't set passphrase or you save passphrase in OS's credential store, `chia start daemon` won't ask passphrase so this issue doesn't appear.
The good news is that `chia.exe start daemon` won't consume resources because it just waits for user input.
So leaving the `chia.exe` process causes no harm.

But I know it's not clean to leave the process unused for a long time.
I'll make a PR to skip to wait user input for passphrase when calling `chia start daemon`.

Again, thanks for your report!
