### ISSUE TITLE
[Bug] All fund dissapear after update to 2.4.2

### ISSUE THREAD

**Issue by germandiazfuentes** [Chia-Network/chia-blockchain#18337]
### What happened?

After updating to 2.4.2 all fund of the wallet have disappeared.
There were no new transactions since May 23, 2023 5:08 PM. I have rebooted Windows and same issue.
From 3.4 XCH aprox to only 0.000000014315 XCH since update.

But today I have tryed to resync wallet and then it appeared. July 10, 2024 9:42 AM there was a transaction not allowed by me of 
- 3.47125807554 XCH
to the wallet xch1jvmuhj7wf9wehv5y8fhmdwqdxxc47jej204xpn0afkapvj5m3g3qjqse2y

All my passphrases are on a notebook, only handwritten. So I suppose there is a security breach in any way that can access to the keys.
Not so much 3.4 XCH, but there were my XCH since 2021.

### Version

2.4.2

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by BrandtH22** [comment]
@germandiazfuentes , unfortunately it appears someone has gained access to your keyset and/or device and stolen your funds. Since chia is a truly decentralized network there is no way to reclaim the funds or revert the transaction(s). One thing we recommend is ensuring that you and your farm are following security best practices to reduce malicious actors ability to gain access to your keys and/or device, many of these best practices are outlined here: https://www.chia.net/2021/05/28/securing-your-chia-how-to-be-a-hard-target/

The best place to reach our support team is on Discord (https://discord.gg/chia) for any followup questions.

**Comment by wjblanke** [comment]
This happened when you updated to 2.4.2? The balance immediately went to 0 after that? Where did you download this Chia installer?
