### ISSUE TITLE
stuck on "Connecting to Wallet" [BUG]

### ISSUE THREAD

**Issue by henrydark** [Chia-Network/chia-blockchain#1845]
**Describe the bug**
On opening Chia v1.04 the app gets stuck on "Connecting to Wallet"

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [OSX big sur]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by lifelongpatsy** [comment]
I had same/similar problem, and the following fix worked for me on macbook pro: 
1) go into hidden ./chia directory (command + shift + '.' in Finder).
2) delete files in following folders: db and wallet
3) reinstall latest version of chia app

**Comment by berlef80** [comment]
This does not fix the issue for me.  was running 1.0.3 fine.  Went to install 1.0.4 and it is stuck on connecting to wallet.  removed the db wallet  file, restarted installed and still stuck.  uninstalled completely and installed again.  same thing.  Thought maybe reinstalling 1.0.3 may work, but that is now stuck on connecting to wallet as well.  Tried force reload to see if that would help.  I think I am at the point now of just deleting the whole CHIA folder and seeing if I start over...Really frustrating because I've spent hours trying to get this to work

**Comment by henrydark** [comment]
Thanks, this worked for me!

**Comment by oktaysar16** [comment]
Stop Chia (Kill Task)

Delete these folders:
C:\Users\yourusername\.chia
C:\Users\yourusername\AppData\Local\chia-blockchain
C:\Users\yourusername\AppData\Roaming\Chia Blockchain

Reinstall Chia. It should now work.

**Comment by kkabala** [comment]
Occurs on 1.1.5 as well

**Comment by starsfan26** [comment]
I had this happen in 1.1.5 as well.  I attempted to close the application while still syncing and having just started a plot.  The app appeared closed but the process was still running and consuming resources.  I tried simply relaunching the app, which worked, but now I have two Chia apps running simultaneously, both consuming resources so presumably still working.  I can only see one of the instances and the UI is working correctly.

**Comment by Syedinthedell** [comment]
| am having the same issue and this is what I have found, just don't know how to fix:
DevTools failed to load SourceMap: Could not parse content for file:///C:/Users/xxxxxx/AppData/Local/chia-blockchain/app-1.1.5/resources/app.asar/build/renderer/js/80.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///C:/Users/xxxxxx/AppData/Local/chia-blockchain/app-1.1.5/resources/app.asar/build/renderer/js/main.js.map: Unexpected end of JSON input

**Comment by HunterDG** [comment]
same here - 1.1.5 - macOS
