### ISSUE TITLE
[Bug] Pooling on third wallet paying first wallet

### ISSUE THREAD

**Issue by smwhite2** [Chia-Network/chia-blockchain#18492]
### What happened?

Load three wallets.
While in third wallet, make a plot NFT.
Make a plot for said plot NFT.
Join `txch.spacefarmers.io` pool.
Payouts seem to happen to first wallet if at all.

### Version

2.4.3-rc3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by BrandtH22** [comment]
Hey @smwhite2 , as we have been discussing in DM this is expected as those payout rewards addresses are set when the client is first initialized and therefore use the first wallet address. 

The payout addresses can be updated via the farm tabs settings / manage farming rewards. 

Since this is a known mechanism in the chia client to default to using the first wallet address of the first keyset I will close this issue for the time being but feel free to reopen if other questions arise.

Thank you!
