### ISSUE TITLE
sent the chia token from gate.io

### ISSUE THREAD

**Issue by SnegaSnega** [Chia-Network/chia-blockchain#18529]
### What happened?

I sent the chia token 2.74 pcs from gate.io to my chia wallet on adress - xch19a7qn97ds3kakzxacaexfhrzy039hadazyxhkwffrkvup28reqfslq4v0g , but the money didn_t arrive. I don"t see it in my wallet.

### Version

ChiaSetup-1.7.1.

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
0xbc53fd63125d61a7e7e96d563e533cb4682ac49bfad067bb7e1cde64fb62f247
```

**Comment by BrandtH22** [comment]
Hey @SnegaSnega  , as a heads up we can generally provide more timely, thorough support in our discord server (https://discord.gg/chia).

What I recommend trying is a resync of the wallet:

- If using the gui go to settings -> advanced -> resync . This will close the client and upon reopening it will resync.
- If using the cli then I would stop chia, rename the wallet db folder in `~.chia\mainnet\wallet\db` then restart chia.

If the funds are still not visible can you let us know:

- if the wallet icon in the top right is orange or green?
- if orange can you click on the wallet icon and let us know if you see any connected peers?
- can you provide your log file from `~.chia\mainnet\log\debug.log`?

**Comment by SnegaSnega** [comment]
I made the first option and now the tokens are not displayed at all
![Screenshot_1](https://github.com/user-attachments/assets/3fb96926-ef7c-410a-92aa-d38ab962b95d)

**Comment by SnegaSnega** [comment]
There should be three transactions displayed at the bottom
14.66+8.47+2.74
But only two transactions are displayed
And for some reason the total is zero

**Comment by SnegaSnega** [comment]
![Screenshot_2](https://github.com/user-attachments/assets/fc9a7712-f483-45aa-9238-173bda6edf55)

**Comment by SnegaSnega** [comment]
will you help me?

**Comment by wjblanke** [comment]
After the hard fork 1.7.1 is not likely to work at all. You should update Chia to the latest version, 2.4.3. I did look at the address you listed, and the funds are certainly there. I think the issue is that your old version is simply not able to sync the wallet. We just don't test these old versions.

https://xchscan.com/address/xch19a7qn97ds3kakzxacaexfhrzy039hadazyxhkwffrkvup28reqfslq4v0g

Please try with the latest version, and follow Brandt's instructions to resync your wallet.
