### ISSUE TITLE
I can't send my coins to another wallet

### ISSUE THREAD

**Issue by USA-chia-plotter-men** [Chia-Network/chia-blockchain#18617]
### What happened?

I have 

Error
Transaction for [10000000000000](tel:10000000000000) is greater than max spendable balance in a block of [2318074723123](tel:2318074723123). There may be other transactions pending or our minimum coin amount is too high.

I can't send my coins to another wallet, I always get only this error

### Version

Last

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by USA-chia-plotter-men** [comment]
I have 10.65 xch

**Comment by nodesupport1** [comment]
@USA-chia-plotter-men It seems like you're encountering an error due to the transaction amount being greater than the max spendable balance in a block. This could be because of pending transactions or a minimum coin amount issue. To resolve this, I'll have to refer you to the official support live chat with the ticket ID CHI07638
Please see the link below to our dedicated support line:
[Chia Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by BrandtH22** [comment]
Hey @USA-chia-plotter-men , TLDR: you need to send smaller amounts of xch to yourself to combine the coins.


Context - this is due to the coinset model in chia and how that 10.65 xch is split amongst the various coins. The coinset model relies on coins having their own value and all of those coins added together establish your balance similar to how cash itself works. Imagine having $10 in all pennies but wanting to buy something for that $10. Most places will not accept pennies so you would need to go the bank to transfer your 1,000 pennies into a $10 bill.

The chia blockchain works the same, in this case your 10.65 xch is split across multiple small value coins and it takes space in a block for each and every coin that needs to be sent. The error is indicating that you can send a total value of 2318074723123 mojo (~2.3 xch) because the coins that make up that 2.3 xch will fill up a block. To be able to send all 10.65 xch in a single transactions you need to combine those coins into a larger coin which can be done simply by sending the allowed amounts each time to yourself (i.e. start by sending 2.3 xch to the destination then the next allowed amount and so on). This will spend the smaller value coins and create larger value coins in the amounts that are sent. You can repeat this process to continually increase the amounts of the coins and therefore send more xch in each individual transaction.

**Comment by AGHcode** [comment]
In such case. Sent money by parts into your account, and after that you'll be able to sent entire sum of money to your final destination account.
