### ISSUE TITLE
[Bug] 2.4.3 Wallet Coin State Issue & Loading Harvester

### ISSUE THREAD

**Issue by SlightlyNoobish** [Chia-Network/chia-blockchain#18653]
### What happened?

Updated to 2.4.3 
1) getting a coin error continuously on the wallet, wallet keeps toggling between orange and green
![{492F63A5-8F81-427E-BEBB-3D0B6DF8AAC0}](https://github.com/user-attachments/assets/25a747e6-c41f-4d11-854f-573e240b3f87)
2) harvester doesn't launch, gets stuck (only way to unstuck is to just manually launch start_harvester.exe

ERROR    Failed to add coin_state: CoinState { coin: Coin { parent_coin_info:

### Version

2.4.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
OSError: [WinError 740] The requested operation requires elevation
2024-09-30T17:38:51.164 full_node chia.full_node.mempool_manager: WARNING  updating the mempool using the slow-path. peak: 996f29942dfb8415412a54c970a6c8c82b2d518206dd18918f3b8a6dec4b3706 new-peak-prev: 261a3c7019e2c02e2af49e5df24cdcd175d801b3e36c8b27d50db5bef2d74199 coins: not set
2024-09-30T17:38:51.728 farmer chia.pools.pool_config     : ERROR    Failed to update pool config entry for launcher_id 0385d89f4b9adc6696a8f3e07fb46ae009be2460e15592f66e0daef92701c892
2024-09-30T17:38:56.465 wallet chia.wallet.wallet_state_manager: ERROR    Failed to add coin_state: CoinState { coin: Coin { parent_coin_info: c805503aefc04265fc5db4ff1e5817cd4f61c709cb9bf433a2c3fe7646b9a976, puzzle_hash: 1dc31269eb9171adb3140aa3de0440fd7cb2b78bae141945c7828bd1e4de9791, amount: 1 }, spent_height: Some(605251), created_height: Some(604008) }, error: Was not able to obtain solution {'coin_name': '0xab619f7c240757e5d0a639f6e78fb63242e6382bb7ca558ede11862a181227ba', 'height': 605251}
```

To bypass the bug, I just go into root folder and launch harvester manually, then 30-60 seconds later chia starts

I reinstalled, restarted, etc, tried user / machine wide all the nonsense. rotated the wallet address and replaced it

What I noticed is that with 2.4.3 it starts flashing randomly disconnecting, not sure why

![{C5AA62CE-C531-4077-A7E2-71E098B85151}](https://github.com/user-attachments/assets/19d28543-19b1-4537-b090-34562a8b5762)

**Comment by SlightlyNoobish** [comment]
Also getting this weird error every 10 seconds
Farm goes black, not available for some reason :/

![{C5AA62CE-C531-4077-A7E2-71E098B85151}](https://github.com/user-attachments/assets/006df05b-891f-43ca-9333-0a13eb988e2a)

**Comment by BrandtH22** [comment]
Hey @SlightlyNoobish , since this is an issue with the pool config what I would do is:
- stop chia
- rename the config file at `~/.chia/mainnet/config/config.yaml` (I normally rename to config_old.yaml so I can refer back to it for any custom settings)
- rename the wallet db at `~/.chia/mainnet/wallet/db/` (generally I just rename them all for the time being, there will be a different .sqlite file for each of your keysets and they are identified by the fingerprint of the wallet. The main one we need to rename is the one corresponding to your farming keyset so we can resync the plotNFT data)
- start chia and let it sync

Note - once chia is fully synced we will want to verify a few things are added back to the config (always stop chia before manually editing the config file). These can be manually updated in the config or one can use the gui to update them also. Let us know if you need any specific instructions for verification or updating:
- plot directories
- payout addresses (make sure to verify both the farmer and pool payout addresses)
- harvester settings (ex. using GPU, GPU index, etc)
- cat/did names (you might be able to rename the old wallet db back and get rid of the newly created one to have these added without needing to manually name them but if done this way make sure to check the logs)
- any other custom settings (trusted nodes, changes to ports, etc | Sometimes I will use a diff check on the old config to help me identify the changes needed for the new one)

**Comment by SlightlyNoobish** [comment]
same issue, renamed everything

Traceback (most recent call last):
  File "chia\wallet\wallet_state_manager.py", line 1753, in _add_coin_states
  File "chia\wallet\wallet_state_manager.py", line 804, in determine_coin_type
  File "chia\wallet\util\wallet_sync_utils.py", line 348, in fetch_coin_spend_for_coin_state
  File "chia\wallet\util\wallet_sync_utils.py", line 334, in fetch_coin_spend
chia.wallet.util.wallet_sync_utils.PeerRequestException: Was not able to obtain solution 

i don't think that's it

**Comment by SlightlyNoobish** [comment]
redid everything, plots, configs etc, even joined another pool fresh

still same errors and harvester isn't starting with same error output

2024-10-01T21:23:37.908 wallet chia.wallet.wallet_state_manager: ERROR    Failed to add coin_state: CoinState { coin: Coin { parent_coin_info: e36e6fc9fdf5c77f14ed2df49866570a9edc8d1f5cc31b3d081ae9ee2858a2c8, puzzle_hash: f38004f0a8af313c1128b23422d0169ba24b35cfe8dc0fce786ed7374dd7c803, amount: 100 }, spent_height: Some(603883), created_height: Some(542939) }, error: Was not able to obtain solution {'coin_name': '0x3ef30c69cd3dd14265cc4ff9f48cf8b7aa002b06f1612297b80ae83fa43df3a4', 'height': 603883}
Traceback (most recent call last):
  File "chia\wallet\wallet_state_manager.py", line 1885, in _add_coin_states
  File "chia\wallet\util\wallet_sync_utils.py", line 348, in fetch_coin_spend_for_coin_state
  File "chia\wallet\util\wallet_sync_utils.py", line 334, in fetch_coin_spend
chia.wallet.util.wallet_sync_utils.PeerRequestException: Was not able to obtain solution {'coin_name': '0x3ef30c69cd3dd14265cc4ff9f48cf8b7aa002b06f1612297b80ae83fa43df3a4', 'height': 603883}
2024-10-01T21:23:37.939 wallet chia.wallet.wallet_state_manager: ERROR    Failed to add coin_state: CoinState { coin: Coin { parent_coin_info: 3ef30c69cd3dd14265cc4ff9f48cf8b7aa002b06f1612297b80ae83fa43df3a4, puzzle_hash: 707d4cdc371668ae2aa60a662976e6e9240a3d84941d94645e6ee56c0fc07c83, amount: 99 }, spent_height: Some(603888), created_height: Some(603883) }, error: Was not able to obtain solution {'coin_name': '0x623304291fb89bbce10632d51c3b866eb888ff638db0ec83c7379c2a986f88ed', 'height': 603888}
Traceback (most recent call last):

**Comment by BrandtH22** [comment]
Hey @SlightlyNoobish , as a heads up we can generally provide more timely and thorough support in our discord server: https://discord.gg/chia

As for the different key error that generally means you have more than 1 keyset on your machine and you need to log into the correct keyset to make the changes. Do you have multiple keysets on the machine? (you can click the logout button in the top right of the GUI to see all of your keys on the machine)

Also, can you provide the full log file?

What is the error that the harvester is presenting? (I am not seeing a harvester error in the above logs)

**Comment by SlightlyNoobish** [comment]
i dont have more than 1 keyset : 
![image](https://github.com/user-attachments/assets/d0e80535-5858-4eac-a678-221a120a1af8)

and no i dont have failure log for harvester, it straight up doesn't launch with no fail logs, only on 2.4.3 

situation is so much worse now after resynching wallet, everything is broken, 7164 plots all going nowhere, 

i dont even have any critical or warning issues in event viewer on anything..... it just doesn't come up, i launch it manually, then hit reload and chia loads, doesn't matter with admin rights or not, and yes i have all protection off PUA off Smart Screen off, whitelists etc. 

nothing changed other than i upgraded the chia version and it full out bricked me setup

[debug.log](https://github.com/user-attachments/files/17235590/debug.log)

**Comment by SlightlyNoobish** [comment]
Some updates, it seems those DLLs were corrupted from Windows so doing "sfc /scannow" fixed the DLLs and Harvester Launches

However after all the back and forth my plots are somehow now in total limbo. 

On Plots page Chia sees them.

![image](https://github.com/user-attachments/assets/45cbc63b-6334-4cfa-bccb-001c2328c5f4)

But on Pooling Page it's all 0....

![image](https://github.com/user-attachments/assets/b7cc8f0b-0031-424a-928d-6fb695f3827f)

**Comment by BrandtH22** [comment]
Hey @SlightlyNoobish , it is good to know that the crashes were being caused by the DLL files. 

I am thinking that the best next step now that the DLLs have been fixed will be to reinstall chia and perform a full wallet resync again while having a new config file created:
- stop chia
- uninstall the current version
- install the latest version from here (2.4.3): https://www.chia.net/downloads/
- rename the config file at `~/.chia/mainnet/config/config.yaml` (I normally rename to config_old.yaml so I can refer back to it for any custom settings. Renaming this file is what forces the chia client wallet sync to resync the plot NFT data)
- rename the wallet db at `~/.chia/mainnet/wallet/db/`
- start chia and let it sync

Note - once chia is fully synced we will want to verify a few things are added back to the config (always stop chia before manually editing the config file). These can be manually updated in the config or one can use the gui to update them also. Let us know if you need any specific instructions for verification or updating:

- plot directories
- payout addresses (make sure to verify both the farmer and pool payout addresses)
- harvester settings (ex. using GPU, GPU index, etc)
- cat/did names (you might be able to rename the old wallet db back and get rid of the newly created one to have these added without needing to manually name them but if done this way make sure to check the logs)
- any other custom settings (trusted nodes, changes to ports, etc | Sometimes I will use a diff check on the old config to help me identify the changes needed for the new one)

**Comment by SlightlyNoobish** [comment]
> Hey @SlightlyNoobish , it is good to know that the crashes were being caused by the DLL files.
> 
> I am thinking that the best next step now that the DLLs have been fixed will be to reinstall chia and perform a full wallet resync again while having a new config file created:
> 
> * stop chia
> * uninstall the current version
> * install the latest version from here (2.4.3): https://www.chia.net/downloads/
> * rename the config file at `~/.chia/mainnet/config/config.yaml` (I normally rename to config_old.yaml so I can refer back to it for any custom settings. Renaming this file is what forces the chia client wallet sync to resync the plot NFT data)
> * rename the wallet db at `~/.chia/mainnet/wallet/db/`
> * start chia and let it sync
> 
> Note - once chia is fully synced we will want to verify a few things are added back to the config (always stop chia before manually editing the config file). These can be manually updated in the config or one can use the gui to update them also. Let us know if you need any specific instructions for verification or updating:
> 
> * plot directories
> * payout addresses (make sure to verify both the farmer and pool payout addresses)
> * harvester settings (ex. using GPU, GPU index, etc)
> * cat/did names (you might be able to rename the old wallet db back and get rid of the newly created one to have these added without needing to manually name them but if done this way make sure to check the logs)
> * any other custom settings (trusted nodes, changes to ports, etc | Sometimes I will use a diff check on the old config to help me identify the changes needed for the new one)

Already did all that, also there is a nicer way to resynch wallet by using built in feature

My problem is my plots, my plots are not being picked up at all now by anything.....

**Comment by BrandtH22** [comment]
@SlightlyNoobish , the resync option in the GUI does not perform a full resync and it retains data from previous resyncs. Especially when it comes to ensuring the plotNFT data is correctly synced I highly recommend renaming the config file and also the wallet DB. The config file is where the plotNFT data is stored so if that is not renamed then the old data will continue to be used. Renaming the wallet forces a full resync and is what will identify the plotNFT coins onchain in order to populate the config file. 

If both the config file and wallet db are not renamed then allowed to fully sync then one would still be using old data regarding the plotNFTs and would very likely end up in a situation where the plotNFT data is not correct.

Can you confirm whether you used the gui resync option or if you forced a full resync by renaming both the config file and the wallet DB?

**Comment by SlightlyNoobish** [comment]
I just deleted all folders and all files except 175gb db, and uninstalled / reinstalled.

now i have 3 different pools, but at least one of the 3 sees the plots...... i will have to go into config to remove the 2 empty ones

**Comment by BrandtH22** [comment]
Hey @SlightlyNoobish , it sounds like the farmer, full node, and wallet are now starting correctly and the pool plots are properly identified, is that correct?

Note - there is not currently a way to fully remove/delete the additional plotNFTs, you can remove their instances in the config file but once you perform a full resync it will resync those other plotNFTs. Mainly wanted to make sure you were aware of this in case another resync is needed in the future :+1:
