### ISSUE TITLE
[Feature Request] GUI client should delete temp files associated with deleted plot

### ISSUE THREAD

**Issue by CharlesWiltgen** [Chia-Network/chia-blockchain#1871]
**Describe the opportunity to delight**
The Chia GUI client does not delete the temp files associated with a plot when the plot is deleted. As a result, all of the other plots running in parallel remain stalled if the drive containing the temporary directory is full.

Some users may be able to infer which files became orphaned, and rescue the stalled plots. Most users will not, and will likely delete all in-progress plots, eventually determining that they must manually delete all plot temp files.

**Expected behavior**
I expect the Chia GUI client to delete associated temp files when a plot is deleted.

**Desktop (please complete the following information):**
- OS: [macOS]
- OS Version/Flavor: [11.2.3 (20D91)]
- CPU: [3.2 GHz 6-Core Intel Core i7]

**Comment by incbyakya** [comment]
So what to do with all these broken temp files? If i would remove it, it would also remove all the progress of plotting, same as the plot, right? And seems there is no other way to fix it.

**Comment by boner-cmd** [comment]
There is no way to resume plot progress at this time. So if you deleted a plot, interrupted it, et cetera, those temp files are just taking up space and must be deleted. Until Chia has the ability to restart or continue a failed plot, there is no benefit to keeping temp files associated with a failed and incomplete plot.
________________________________

**Comment by Grosbof** [comment]
In case of a failure at the very end: meaning you find yourself with only one final .tmp file. Is it possible to fix that file by deleting the .tmp ending and therefore make a a valid plot file?

**Comment by boner-cmd** [comment]
I have successfully done this before on 1.0.3, but I can't speak to the current version.
________________________________

**Comment by Grosbof** [comment]
Tried it with 1.1.1 and it did work indeed.

**Comment by Eneen** [comment]
Maybe option to put temp files in different subfolders named after plot ID?

**Comment by boner-cmd** [comment]
This is an okay housekeeping idea, but doesn't solve the original issue that deleted plots leave unusable trash temp files taking up space after the plots themselves are deleted. Currently there is no benefit to unusable temp files being left behind when their plot is deleted/interrupted. Maybe this is supposed to dovetail into being able to restart and continue plots in the future? Until then though, there's nothing you can do with the temp plots but delete them.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by irae** [comment]
For the CLI plotters like myself, if you run out of space because of temp files leftover, you can recover the plots by doing some diagnose and cleanup *without stopping your plots*.

For the devs: You can probably skip this to the end, as it is kinda trivial, but I have a suggestion in the end.

Disclaimer: I am only doing chia for about 5 days and figuring out things on my own. Follow at your own risk!

When you run out of space, the following message shows:
```
Only wrote 288 of 1048570 bytes at offset 50331360 to "/mnt/chia-temp/plot-k32-2021-05-08-08-54-4d09...9fb99c.plot.p2.t6.sort_bucket_048.tmp"with length 50331648. Error 1. Retrying in five minutes.
```

You can get the plot ID form there, it is everything after the last dash and before the period. In my case, I had 2 plots running, so I got their IDs (I an redacting part of the ID, as I don't know if it is safe to post it):
```
4d09...fb99c
ffce...fa83
```

Then I found all the files wasting my free space by using grep to exclude the ones that were running:
```
/mnt/chia-temp# ls | grep -v 4d09...fb99c | grep -v ffce...fa83
```

Sure enough there they were, wasting my space. After triple checking everything, looking at dates, to find out they were from yesterday, when I had to stop plotting and killed the processes, I just piped to xargs to remove the unnecessary files:
```
/mnt/chia-temp# ls | grep -v 4d09...fb99c | grep -v ffce...fa83 | xargs rm
```

After that, my plots resumed after their waiting period. I hope everything goes well, as I am posting before waiting for the final result.

### I wonder

I hope when the plotter picks up from the empty space warning, that they do some minimum verification, like checking that the files that will still be used are still there, or something like it. I guess I'll know later and post the results. But even though resuming is not yet supported, at least the retry that is already supported should be very stable as a first step, no?

**Comment by mylastore** [comment]
temp files won't delete every time plot or plots are done I have erase the drive every time is so annoying. I am running on a MacBook Pro M1 the download git version.

**Comment by Swearwolfdoghound** [comment]
It is still persistent as of July 15th. Finished 6 test plots (plots are done and farming), node is fully synced but temp drive nvme is still blocked with .tmp files. Gave it a day to wait if it eventually cleans up automatically but it does not.
