### ISSUE TITLE
[Bug] Version 1.8 stopped syncing

### ISSUE THREAD

**Issue by Leixxington** [Chia-Network/chia-blockchain#18782]
### What happened?

Non Synced  after Peak Height 5,496,001
![Capture d’écran du 2024-10-28 16-45-07](https://github.com/user-attachments/assets/8f9c2185-e96f-454d-b2c0-476e9a5afd95)
Any help will be appreciated !
Thx

### Version

1.8

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by BrandtH22** [comment]
Hey @Leixxington , since the hard fork occurred this past June users need to upgrade to version 2.1 or newer to remain in connection: https://docs.chia.net/consensus-forks/ .

I recommend upgrading to the latest version from here:
https://www.chia.net/downloads/

Once upgraded make sure your node is connecting to peers and syncing, feel free to jump into our discord server if any questions arise or if the latest version is not syncing properly: https://discord.gg/chia

**Comment by wjblanke** [comment]
Yes, probably stuck at a block which honors the new hard fork. This version is so old, there may be other issues with updating. Keep us posted.

**Comment by Leixxington** [comment]
Thank you
Finally restart with the last version and I will see how does it go !
So far all my plots K32 are not recognized yet !

**Comment by emlowe** [comment]
Closing issue as it's expected for version 1.8 to stop syncing - recommend you head over to our discord if you have more trouble getting the new version to work https://discord.gg/chia
