### ISSUE TITLE
Initial synchronisation is slow. ( Suggestion / Feature request )

### ISSUE THREAD

**Issue by staviq** [Chia-Network/chia-blockchain#1935]
This does not seem to be version specific, but started when the network started growing after launch.

Also the issue is not strictly tied to any internet provider or internet speed, as the problem happens on several locations.

Right now, the time to complete initial synchronization is about couple of days.

If i have to powerdown my node for maintenance, it takes about half an hour for the synchronization to catch up.

I have seen several cases when people were actually not being able to keep up the synchronization, and the height was growing faster than they were syncing.

I might be wrong, but from what see, it appears that the initial sync is no different from a normal sync ( as in keeping up with the network on synchronized node ), and every chunk of the data is procesed one by one, which means that this problem will only get worse, day by day.

Chia desperately needs some sort of predownload.

With the current overall network growth rate, is looks like month from now, initial synchronization will take weeks.

**Please consider implementing pre-download, maybe zip up and gpg sing the data weekly and provide for download.**

I believe this problem will only get worse, especially when we go to 1.1 and transactions will start.

**Comment by flotti455** [comment]
I agree.

My 11-year old laptop takes four hours to synchronize a single day of Chia blockchain (including a single wallet).

As of this writing, we are 27 days in since genesis, meaning that laptop would take 4.5 + 0.75 days nonstop running until it caught up to the then up-to-date blockchain state. And this is without any possibly additional required calculations coming when transactions start.

So in one year since genesis, my old laptop would need to run two months + delta time non stop to catch up.

It's apparent that these numbers are already blockers for many people to join in on Chia, hurting decentralization and adoption, both ecologically-friendly old hardware and poorer societies with older computers.

Everyone installing Chia from git-cloning or installing via installers is by definition already trusting the software. For my reasoning, it therefore makes sense to bundle the (_Chia Network Inc_-signed) installers with up-to-date blockchain snapshots.

Arguments such as "but u gotta verify the blockchain urself!!" are therefore IMHO security theater. I'm grateful though to be convinced otherwise.

**Comment by mariano54** [comment]
I agree this needs to be improved, and we are looking at some ways to do this.
We will not provide the blockchain for download, as that is one of the principles of Chia (and bitcoin). You only trust the code, but you don't trust anyone else to tell you which blockchain is the correct one, you verify this yourself.

**Comment by mariano54** [comment]
There are very large possible gains with blueboxing, and with parallelism

**Comment by mariano54** [comment]
Please port forward to 8444 if you need more peers.
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections
