### ISSUE TITLE
[BUG]Failed to create the chia daemon

### ISSUE THREAD

**Issue by NirHeaven** [Chia-Network/chia-blockchain#1996]
I run chia start node on centos 7, I got the error  -- Failed to create the chia daemon

**Comment by iwwwwwwi** [comment]
I've got similar problem last night trying to run a harvester on a new linux box. It turned out I locked my iptables too much. I had only ssh allowed in the INPUT table. Makes sure you haven't done same :) At least permit traffic on the loopback interface - chia services talk to one another via localhost by default.
