### ISSUE TITLE
I can't use the plots

### ISSUE THREAD

**Issue by atyhieu** [Chia-Network/chia-blockchain#2068]
I can't use the plots

in GUI show the message
"Not found Plots 
Caution, deleting these plots will delete them forever. Check that the storage devices are properly connected."

in the debug.log show the some messages like
"...
01:59:17.590 harvester chia.plotting.plot_tools: WARNING  Plot C:\ALL\1\plot-k32-2021-04-17-21-30-a72db5227e4cbe7a4f574da8ee6698b523c327d230737a98905d122db21d3034.plot has a farmer public key that is not in the farmer's pk list.
01:59:17.593 harvester chia.plotting.plot_tools: WARNING  Plot C:\ALL\1\plot-k32-2021-04-18-11-54-ed653537e21f90f68bfb56bf2486c479c4aa7392a20cba81ee878324c296cc2e.plot has a farmer public key that is not in the farmer's pk list.
01:59:17.596 harvester chia.plotting.plot_tools: WARNING  Plot C:\ALL\2\plot-k32-2021-04-17-21-30-d604955876a722b5fe50ec5ebe8a7dc373188c2fc33ac17258c14a7143e1bf22.plot has a farmer public key that is not in the farmer's pk list.
01:59:17.601 harvester chia.plotting.plot_tools: WARNING  Plot C:\ALL\2\plot-k32-2021-04-17-21-30-ff7e808c1caf3fbbe1c2f8f65705e16bafa41cb63be29ccc4121db71695f8137.plot has a farmer public key that is not in the farmer's pk list.
..."

how can I fix it.

__Originally posted by @ywwz in https://github.com/Chia-Network/chia-blockchain/issues/2059__

**Comment by aqk** [comment]
Thank you for posting the log messages!

This error message means that the plots were created with a different key than the farmer you are using now.

This can be because the plots were created on another machine, or after a major uninstall event.

The solution is to load your key (24 words) from the machine that created the plots.

You can see your key on the plotter machine by doing:
```
chia keys show
```

Be sure to back this key up.
