### ISSUE TITLE
no main menu after selecting keys (bug?)

### ISSUE THREAD

**Issue by nerle** [Chia-Network/chia-blockchain#2125]
Hello,

after install I want to view private keys and choosed the entry from the main menu. Now I see the "Chia Select Key" Window and could view the words and my key but I can't go back to the main menu to add a new plot and so. Could you please help. 

THX!

**Comment by marianopw** [comment]
Same here. I went to Keys on the GUI, but i'm not able to see my key either. After that i can't go back to the main menu.

**Comment by GreggHales** [comment]
Even worse is if you bump the "Keys" while plotting, you cannot get back to the GUI at all. And it warns you that if you try to close it to reopen, all plotting and farming will be lost. If this is by design, how about disabling the "Keys" link once you have started plotting, or at least providing a cancel or back button or something???
