### ISSUE TITLE
stderr: [814] Failed to execute script start_full_node

### ISSUE THREAD

**Issue by laurentbillet** [Chia-Network/chia-blockchain#2218]
**Describe the bug**
When opening Chia application, creating keys go well but then when starting Full node (see screenShot)
Error message from log:

_Running python executable: 
child process success
(node:803) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
No cert
Have cert
stderr: Traceback (most recent call last):
  File "chia/server/start_full_node.py", line 65, in <module>
stderr:   File "chia/server/start_full_node.py", line 60, in main
  File "chia/server/start_service.py", line 211, in run_service
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 642, in run_until_complete
  File "chia/server/start_service.py", line 205, in async_run_service
  File "chia/server/start_service.py", line 150, in run
  File "chia/server/start_service.py", line 121, in start
  File "chia/full_node/full_node.py", line 115, in _start
  File "chia/consensus/blockchain.py", line 105, in create
  File "chia/consensus/blockchain.py", line 117, in _load_chain_from_store
  File "chia/full_node/block_store.py", line 317, in get_peak_height_dicts
stderr:   File "aiosqlite/cursor.py", line 65, in fetchall
  File "aiosqlite/cursor.py", line 31, in _execute
  File "aiosqlite/core.py", line 129, in _execute
  File "aiosqlite/core.py", line 102, in run
sqlite3.DatabaseError: database disk image is malformed
stderr: [814] Failed to execute script start_full_node_

<img width="1072" alt="Capture d’écran 2021-04-20 à 22 06 47" src="https://user-images.githubusercontent.com/18393154/115458502-13d33d80-a226-11eb-9da5-e8914db31f23.png">

**To Reproduce**
No sure how to reproduce it since I follow standard process to install and run chia app.

**Expected behavior**
I was expecting full node synchronisation to start

**Desktop (please complete the following information):**
- OS: macOs BigSur

**Additional context**
First opening of chia worked actually well and synchronisation started however application quited before being fulIy synched  have this error
Reinstalling OS and chia app did not help

**Comment by jacomaree** [comment]
i'm having the exact same issue at the moment
macOS Big Sur
just finished my 1st plot and getting the same screen as you've got above under Full Node section.

have made sure port forwarding is enabled to this machine, still no luck :(

**Comment by darkodus** [comment]
I ran into this same issue on MacOS, it was because my laptop lost power while syncing the blockchain which corrupted the database. This can also happen if the app crashes suddenly while it's in the middle of writing something to the database. Sadly SQLite is brittle like that. 😞 

Good news is that it might be fixable (not in all cases, just to warn you).

**And important note: even if this fixes the database file, you might still need to re-sync everything (this happened to me)**

**Here's some important details:**
The chai application data is stored in `~/.chia/mainnet` (or testnet if you're using that one)
There are two separate database folders:
1. `~/.chia/mainnet/db` - I'm guesing this is the "full node" database folder
2. `~/.chia/mainnet/wallet/db` - this is, obviously, the wallet database folder

If you look into those folders they should both have a two distinctly named .sqlite files (and their meta files with dash suffixes), the most likely corrupted ones are the blockchain files which are quite big (~700MB on my machine).

**The fix:**
First make sure you have sqlite3 on your machine. Easy way to check is to type `which sqlite3` in your Terminal and see that it returns a path instead of "not found" message. If you don't have it and you use homebrew, you can just type `brew install sqlite` and that should do it. I won't go into more detail on how to install it if you don't use it as you can probably google that information yourself.

Then:
1. Close the Chia app and make sure it's not running anywhere (you can open Activity Monitor and search for "chia")
2. Open Terminal app
3. Go to the full node database folder (`cd ~/.chia/mainnet/db`)
4. Run `ls` on the folder to see which sqlite files are there. You should see files named something like `blockchain_v1_mainnet.sqlite` and `peer_table_node.sqlite` and they often have two additional files with `-shm` and `-wal` suffixes, you can ignore those
5. Then run:
```sh
# NOTE: The file is quite large so this command will take a minute or two.. or five, depending on your machine
sqlite3 ./blockchain_v1_mainnet.sqlite ".dump" | sqlite3 ./blockchain.fix
mv blockchain_v1_mainnet.sqlite blockchain_v1_mainnet.sqlite.broken
mv blockchain.fix blockchain_v1_mainnet.sqlite
```
(The `blockchain_v1_mainnet.sqlite.broken` will serve as a backup in case you want to go back to it, but if the fix works then you can discard it)
6. Try opening Chia again and you either get the same "Connecting to Wallet" spinner again (this means it's not fixed yet) or you get the wallet selector screen which means it probably worked.

If you still get the "Connecting to Wallet" spinner screen:
1. Close the Chia app
2. Go to the wallet database folder (`cd ~/.chia/mainnet/wallet/db`)
3. Run `ls` again and you should see something like `blockchain_wallet_v1_mainnet_0000000000.sqlite` where the `0000000000` corresponds to your fingerprint, and a file called `wallet_peers.sqlite`
4. Now run:
```sh
# NOTE: Remember to substitute the 0000000000 with the fingerprint in your files!
sqlite3 ./blockchain_wallet_v1_mainnet_0000000000.sqlite ".dump" | sqlite3 ./blockchain.fix
mv blockchain_wallet_v1_mainnet_0000000000.sqlite blockchain_v1_mainnet.sqlite.broken
mv blockchain.fix blockchain_wallet_v1_mainnet_0000000000.sqlite
```
5. Then try opening Chia again

If you still get the same spinner, you might want to try to do the same actions to the other sqlite files individually.

If it still doesn't work, there's always the nuclear option of removing the ~/.chia folder altogether, but I'm not familiar enough with the app to know what you would lose if you do that. I would suggest backing up the folder before deleting just in case.

**Comment by darkodus** [comment]
Another note: If someone with Windows runs into this issue as well it should be possible to do the same thing in Windows as well. You just need to figure out how to install sqlite3 and then you need to figure out where the chia folder is located. It's been a while since I've used Windows so I can't remember if `mv` command is the same or if it works the same way. I'm sure you can also do that in the file explorer as well as the point is just to rename the two files.

If someone manages to do that, do post the steps here so other people can find it too!

**Comment by laurentbillet** [comment]
Thanks for the help !
I was trying to find these DB files but without success, I will try what you suggest. Hopping it will correct everything.
It is strange that Chia reinstallation do not replace the  corrupted DB file

**Comment by darkodus** [comment]
> Thanks for the help !
> I was trying to find these DB files but without success, I will try what you suggest. Hopping it will correct everything.
> It is strange that Chia reinstallation do not replace the corrupted DB file

Actually that is intended. You always want to have the application user specific data in a different place for exactly that reason. You don't want to lose all your things if you have to re-install. Also if your machine has multiple users, they will still share the same application executable so you wouldn't want each user to also share the user data files. 😄

**Comment by jacomaree** [comment]
> I ran into this same issue on MacOS, it was because my laptop lost power while syncing the blockchain which corrupted the database. This can also happen if the app crashes suddenly while it's in the middle of writing something to the database. Sadly SQLite is brittle like that. 😞
> 
> Good news is that it might be fixable (not in all cases, just to warn you).
> 
> **And important note: even if this fixes the database file, you might still need to re-sync everything (this happened to me)**
> 
> **Here's some important details:**
> The chai application data is stored in `~/.chia/mainnet` (or testnet if you're using that one)
> There are two separate database folders:
> 
> 1. `~/.chia/mainnet/db` - I'm guesing this is the "full node" database folder
> 2. `~/.chia/mainnet/wallet/db` - this is, obviously, the wallet database folder
> 
> If you look into those folders they should both have a two distinctly named .sqlite files (and their meta files with dash suffixes), the most likely corrupted ones are the blockchain files which are quite big (~700MB on my machine).
> 
> **The fix:**
> First make sure you have sqlite3 on your machine. Easy way to check is to type `which sqlite3` in your Terminal and see that it returns a path instead of "not found" message. If you don't have it and you use homebrew, you can just type `brew install sqlite` and that should do it. I won't go into more detail on how to install it if you don't use it as you can probably google that information yourself.
> 
> Then:
> 
> 1. Close the Chia app and make sure it's not running anywhere (you can open Activity Monitor and search for "chia")
> 2. Open Terminal app
> 3. Go to the full node database folder (`cd ~/.chia/mainnet/db`)
> 4. Run `ls` on the folder to see which sqlite files are there. You should see files named something like `blockchain_v1_mainnet.sqlite` and `peer_table_node.sqlite` and they often have two additional files with `-shm` and `-wal` suffixes, you can ignore those
> 5. Then run:
> 
> ```shell
> # NOTE: The file is quite large so this command will take a minute or two.. or five, depending on your machine
> sqlite3 ./blockchain_v1_mainnet.sqlite ".dump" | sqlite3 ./blockchain.fix
> mv blockchain_v1_mainnet.sqlite blockchain_v1_mainnet.sqlite.broken
> mv blockchain.fix blockchain_v1_mainnet.sqlite
> ```
> 
> (The `blockchain_v1_mainnet.sqlite.broken` will serve as a backup in case you want to go back to it, but if the fix works then you can discard it)
> 6. Try opening Chia again and you either get the same "Connecting to Wallet" spinner again (this means it's not fixed yet) or you get the wallet selector screen which means it probably worked.
> 
> If you still get the "Connecting to Wallet" spinner screen:
> 
> 1. Close the Chia app
> 2. Go to the wallet database folder (`cd ~/.chia/mainnet/wallet/db`)
> 3. Run `ls` again and you should see something like `blockchain_wallet_v1_mainnet_0000000000.sqlite` where the `0000000000` corresponds to your fingerprint, and a file called `wallet_peers.sqlite`
> 4. Now run:
> 
> ```shell
> # NOTE: Remember to substitute the 0000000000 with the fingerprint in your files!
> sqlite3 ./blockchain_wallet_v1_mainnet_0000000000.sqlite ".dump" | sqlite3 ./blockchain.fix
> mv blockchain_wallet_v1_mainnet_0000000000.sqlite blockchain_v1_mainnet.sqlite.broken
> mv blockchain.fix blockchain_wallet_v1_mainnet_0000000000.sqlite
> ```
> 
> 1. Then try opening Chia again
> 
> If you still get the same spinner, you might want to try to do the same actions to the other sqlite files individually.
> 
> If it still doesn't work, there's always the nuclear option of removing the ~/.chia folder altogether, but I'm not familiar enough with the app to know what you would lose if you do that. I would suggest backing up the folder before deleting just in case.

Thank you for the info!
Will try this and report back as soon as I’ve done it

**Comment by laurentbillet** [comment]
> Thanks for the help !
> I was trying to find these DB files but without success, I will try what you suggest. Hopping it will correct everything.
> It is strange that Chia reinstallation do not replace the corrupted DB file

Ok I see indeed, thanks :) Maybe one additional question, Since I had not the time to plot anything and start farming I guess I simply delete these files right ? and reinstall chia and start with new Key ?

**Comment by darkodus** [comment]
> Ok I see indeed, thanks :) Maybe one additional question, Since I had not the time to plot anything and start farming I guess I simply delete these files right ? and reinstall chia and start with new Key ?

You don't need to re-install Chia, and you at least shouldn't need to start with new key. The same mnemonic should link to your existing wallet. (I'm not 100% sure but you should try before creating new ones)

But yeah, do take a copy of the .chia folder before deleting. And yes you could also go to the db folders and delete all the .sqlite files instead of the full .chia folder, but still, I always recommend taking a backup copy of it. 😄

**Comment by laurentbillet** [comment]
FIx suggestion seems to work for me thank you very much :) !

**Comment by chiauserrich** [comment]
I found the files, but how do I do step 5 and "run"...

I'm on Mac Big Spur 

"
5. Then run:
# NOTE: The file is quite large so this command will take a minute or two.. or five, depending on your machine
sqlite3 ./blockchain_v1_mainnet.sqlite ".dump" | sqlite3 ./blockchain.fix
mv blockchain_v1_mainnet.sqlite blockchain_v1_mainnet.sqlite.broken
mv blockchain.fix blockchain_v1_mainnet.sqlite
"

**Comment by chiauserrich** [comment]
Suggested fix worked for me. Had to change the wallet fingerprint as well. 

Thanks.
