### ISSUE TITLE
My chia node is not synching[BUG]

### ISSUE THREAD

**Issue by EddyERRE** [Chia-Network/chia-blockchain#2469]
After having closed the computer for the night, this morning the synchronization isn't working anymore.I have opened  the port 8444 (TCP) in entrance but nothing changed so I am stuck at 64940 height

**Comment by petrkr** [comment]
And have you open it also on router? Do you have public IP? Maybe there can be NAT propagation problem like Chia node reporting Internal IP instead of External IP? Maybe you can try connect to some public nodes. If they are full of connections, maybe I can connect from my node to you, but for that I need IP where to connect

**Comment by kosyar** [comment]
but how to connect to public nodes?

**Comment by petrkr** [comment]
really something is wrong with peer discovery or it just took long time. I just set up new node, on directly connected public IP, open firewall and no peers connected yet. Only those who I added manually from outside.

you can try to connect to yacp.net:8444

**Comment by bebe1970** [comment]
@petrkr  I tried it , it can help . it was syncing again I find to solve to 3 long hours thank you

**Comment by bebe1970** [comment]
I want to know it can work? @petrkr

**Comment by petrkr** [comment]
> @petrkr I tried it , it can help . it was syncing again I find to solve to 3 long hours thank you

or you can download "bootstrap" sqlite database, I already set-up my 2nd node like that. better than wait 2 days for sync. I just do not undestand why they used SQLite which is so slow for this kind of data. Everyone else using atleast LevelDB or RocksDB for this usecase.

I have to check DB model to move it atleasto MySQL, because now it has like 1.3GB, but I can not imagine 10GB sized SQLite database file

**Comment by petrkr** [comment]
Alreay 60 connections on that node. I think to increase, but do not know how much it will eat resources. Any suggestion from someone ? If 120, 600, 1000 ?

**Comment by dompie** [comment]
Node discovery feels currently something like BitTorrent in 2002

**Comment by petrkr** [comment]
But in those old days almost everybody had public IP and thus been "Active". I remember problem on DC++ 2-4 years later when NAT massivly increased due WiFi ISP and school networks. Then was problem to be passive

**Comment by bebe1970** [comment]
![image](https://user-images.githubusercontent.com/83080381/115943076-0c3abf80-a4d8-11eb-9bfc-8202ae70c8cc.png)
Why the full node it see on chia.yacp.net but dont have my full note ip address when i restart my computor

**Comment by EddyERRE** [comment]
Hello Petr,
I use a router to have access to Internet, It Isn't possibile to open on it
any Port. Should i try to connect with internet with another system ex:
hotspot by iPhone?

Il ven 23 apr 2021, 13:18 Petr Kracík ***@***.***> ha scritto:

**Comment by petrkr** [comment]
> Hello Petr, I use a router to have access to Internet, It Isn't possibile to open on it any Port. Should i try to connect with internet with another system ex: hotspot by iPhone? 

on hotspot you will be behind NAT too. On router you not open port, but forward it to your machine/node. Depends on your ISP you if you have or not public IP.

**Comment by EddyERRE** [comment]
I have a router for me and my family but After some time while the mode was
not synching, now It is working. Thank you so much, now I will not turn it
off before It ends

Il lun 26 apr 2021, 14:24 Petr Kracík ***@***.***> ha scritto:

**Comment by hoffmang9** [comment]
Please update to 1.1.2.
