### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Chrisloko** [Chia-Network/chia-blockchain#2629]
One of my GUI full nodes had been working well for weeks until today, now it is no longer syncing, it just got stuck. The connection status is green and connected. I've tried reinstalling and restarting the node several times with no luck.

Status - Not Synced
Connection status - Connected
Peak height 178538

Running Chia version 1.1.1 but the issue started when on 1.0.5, I figured updating it might solve the problem.

![image](https://user-images.githubusercontent.com/25800953/115971728-c3066200-a50f-11eb-83e8-b87fc99e3851.png)

- OS: W10
- OS Version/Flavor: 19042.928
- CPU: AMD 3000G

**Comment by Crypto-78** [comment]
Hi I also detect this problem since this morning, it no longer synchronizes the nodes.
I have Chia version 1.1.1

Can anyone help us?

![image](https://user-images.githubusercontent.com/83140217/115972221-09ad8980-a51b-11eb-983c-7361ac432e5b.png)


Windows 10
Vs: 19042.928
CPU Intel I7 11° Generation

**Comment by hoffmang9** [comment]
If you get port 8444 open on your router you will get nodes immediately.
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections

Also, there should be a new release shortly that will help but you want 8444 open either way.

**Comment by Crypto-78** [comment]
@hoffmang9 It is not the problem with port 8444 because I am on a corporate connection and I do not have the possibility to open this port. But I uninstalled the program deleting all traces I reinstalled again and now it is synchronizing without problems, even if the door is still closed, so the problem is not that, but of the software

**Comment by hoffmang9** [comment]
You should have 40+ connections and I bet you have ~3

**Comment by Crypto-78** [comment]
@hoffmang9  are you talking about the connections visible on the wallet?

**Comment by Chrisloko** [comment]
@hoffmang9 
My port forwarding doesn't seem to work, I log into my router under port mapping with as far as I know is the same as port forwarding. The problem is that the port isn't opened, I also opened it in the windows firewall and have Upnp enabled. I'll have a chat with the ISP where that node is located. How was the node able to work prior to this? Seems like it happened out of the blue.
