### ISSUE TITLE
Write/Read Speed for SSD

### ISSUE THREAD

**Issue by hhenrry501** [Chia-Network/chia-blockchain#2690]
Would plot speed increase if I switch my SSD PCIE 3 to a PCIE 4? PCIE 4 double the W/R speed. 
And also, my SSD PCIE3 has 3400mbs write/read speed, but in Task Manager, the speed for the disk is only 300mbs on average? why is that?

**Comment by garyhkirk** [comment]
Consumer NVME (PCIE) drives slow down with constant writes. It's normal for that to happen. Additionally, plotting creates lots of medium-sized writes so your write speed may look bumpy. 300MB/s isn't bad for a consumer drive being worked so hard. One major factor to consider is the endurance of your plotting SSD. 1.6TB of data is written with each K-32 plot, many consumer drives have 300TB to 600TB endurance ratings (although it's best to check your model to be certain). If you exceed the Lifetime TBW (TB Written) you'll invalidate the warranty. Manufacturers know that SSD's degrade as more is written to them, hence they stipulate a maximum they are willing to guarantee. It's likely that the drive will still work beyond the TBW value but performance might have already reduced by then and eventually, when enough blocks are retired due to degradation, the drive will become unusable or fail. This is why Chia suggest using Enterprise SSD's, but they are expensive so you need to weigh up the pros and cons along with your risk/reward tendency.

**Comment by hoffmang9** [comment]
No tech support in issues. Use Discussions or Keybase.
