### ISSUE TITLE
message 22[BUG]

### ISSUE THREAD

**Issue by fanarial** [Chia-Network/chia-blockchain#2692]
got 100% plotting and appears a small window with "22"

![image](https://user-images.githubusercontent.com/83170316/115994911-593d9500-a5af-11eb-9483-9cd3b0084f2c.png)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by ChiaPlotter** [comment]
Describe the bug
After connecting to wallet, node shows synced but unable to add plot directories.

To Reproduce
Steps to reproduce the behavior:

When launching error must be acknowledged 4 times before being able to select key. Once after selecting plots. Twice after selecting plot directory to add, directory not added.

Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

    OS: Windows
    OS Version/Flavor: 10 Home
    CPU: i7-8700k

Additional context
Add any other context about the problem here.

**Comment by sergio8864** [comment]
exactly the same whrite ChiaPlotter up: https://github.com/Chia-Network/chia-blockchain/issues/2692#issuecomment-826367005

OS: [Windows 10 pro]
OS Version/Flavor: [windows compilation 19042.928]
CPU: [I7 6700]
Additional context
Add any other context about the problem here.

**Comment by ChiaPlotter** [comment]
@fanarial @sergio8864 

Error 22 references bad plot directories in C:\Users\<username>\.chia\mainnet\config\config.yaml.

Either go into the config file and remove the directory that you know to be problematic or resolve the issue with the previously working directory. My NAS had gone offline when I had updated then rebooted. I was so concerned by 22 I waited to fix the NAS because they wouldn't be farming anyway. Fixed the NAS connectivity and resolved the GUI error and am now farming successfully on 1.1.2.

**Comment by lipalong** [comment]
See the above explanation by @ChiaPlotter 
Also, we've made the wording for this error more clear for the next release.

**Comment by 413303105** [comment]
@狂热的 delete wrong plot_directories in C:\Users\username\ .chia\mainnet\config\config.yaml.

**Comment by 413303105** [comment]
@fanarial @sergio8864 delete wrong plot_directories in C:\Users\username\ .chia\mainnet\config\config.yaml.
