### ISSUE TITLE
BUG~delete plots button is grey!~

### ISSUE THREAD

**Issue by rickyimba** [Chia-Network/chia-blockchain#2784]
Delete plots button is unavalable~~
![4444](https://user-images.githubusercontent.com/58984384/116063090-21217980-a6b7-11eb-931b-e8bba33f288c.PNG)

**Comment by AkiraDX** [comment]
I'm also having the same problem.

**Comment by prewriter** [comment]
That's intentional, see:

https://github.com/Chia-Network/chia-blockchain-gui/blob/3a481b5a1be44ce6867ede5d1f1cd4c5aa285f38/src/components/plot/PlotAction.tsx#L29

and also release notes:

https://github.com/Chia-Network/chia-blockchain/releases/tag/1.1.0:

> We have temporarily disabled the "Delete Plots" button in the Windows GUI as we are still working on debugging upstream issues that are causing it.

You might be able to [delete it using CLI](https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference#other-commands-not-yet-documented).
