### ISSUE TITLE
[BUG] Nvidia Geforce Experience Causing Chia Update Failure in Windows 10

### ISSUE THREAD

**Issue by garyhkirk** [Chia-Network/chia-blockchain#2911]
**Describe the bug**
When updating from 1.0.5 to 1.1.2 on Windows 10 Pro (with Geforce Experience installed, which has now been uninstalled) the update fails without any context information or logging.

I tracked down the issue and can see that the "Nvidia Share" service uses the libssl and libcrypto dlls from the Chia installation - this means that (if Geforce Experience is installed) the deletion of those two files will fail as they are in use by another program. Uninstalling Geforce Experience solved the problem.

I'm not sure if this is the fault of Nvidia but it might be to do with how Chia works, but it probably needs to be documented for users.

**To Reproduce**

1. Install Geforce Experience without Chia on the machine
2. Install Chia 1.0.5
3. Maybe need to restart?
4. Try to update to Chia 1.1.2

**Expected behavior**
I would have hoped to see some information on why the update failed, but I don't know how tricky that is to do

**Desktop (please complete the following information):**

- OS: Windows 10 Pro with all patches
- CPU: Ryzen 5950x
- RAM: 64GB

**Comment by royimous** [comment]
Weird issue. I have GeForce experience on 1.1.2 and have not encountered this.

**Comment by Dan1138** [comment]
I had the EXACT same issue when upgrading from 1.1.4 (which installed fine) to 1.1.5 which failed due to those same two DLL's locked by NVIDIA Share.exe just as you say so I can confirm this issue still exists today.

I resolved this by rebooting into safe mode, deleting the two DLL's mentioned above, rebooting back to normal windows (not safe mode) and running the Chia 1.1.5 installer which then worked fine.

For me, it took me a bit longer to find the error than it otherwise might have because clicking to view log from the failed installer message incorrectly opened log file %LOCALAPPDATA%\SquirrelTemp\SquirrelSetup.log which was created by a months ago Discord install while the real Chia error log was at %LOCALAPPDATA%\SquirrelTemp\Squirrel-Install.log.  Once I figured out the real log, it was pretty easy to see the DLL that would not delete, try deleting it manually and getting the message it was locked by NVIDIA Share.exe and then rebooting to safe mode to terminate those two DLL's with extreme prejudice.
