### ISSUE TITLE
[BUG] Plotting Progress Bar Doesnot Depcit True Picture

### ISSUE THREAD

**Issue by Jai-Khandelwal** [Chia-Network/chia-blockchain#2933]
**Describe the bug**
**A clear and concise description of what the bug is.**

Phase 1 Itself Take 38% to 42% of time but Progress bar of plotting Shows 31% even after Phase 2

**Expected behavior  **

Progress Bar of Plotting Should Depicts True progress plus it would be better if in log Temp files in temp directory also displayed to have better Plotting Management

![image](https://user-images.githubusercontent.com/83308484/116298163-bc027c80-a7b9-11eb-893a-19267c8824c7.png)

**Comment by aqk** [comment]
Hi There,

Thank you for you bug report. We have a Pull request to deal with this issue, but we probably will not integrate it until after the transactions release, partly because the change spans 3 repos (chiapos, gui, and chia-blockchain)

Thank you for your patience.

I have added a card for this issue at https://trello.com/c/NZCRN6dh/1113-minor-plot-progress-bar
