### ISSUE TITLE
Parallel Plotting & Queue

### ISSUE THREAD

**Issue by Elerong** [Chia-Network/chia-blockchain#3052]
Can you please adjust a function for Parallel plotting?

When a user selects Parallel plotting, select the number of plots that should work in parallel and how many plots would you like in a queue?

The issue begins when ME a user creates 6 parallel plots 85min delay there is no queue created (technically).
The application does not register those parallel plots as a part of Queue named "default"

When I create Queue of any size lets say 29 plots with a "default" name, the 1st plot of that queue starts automatically BUT I don't want it to.
Making total of 2 plots running at the same time.

Alternative solution would be stop the 2nd plot "Add Plot to Queue" from starting.
So once 7 plots are declared for parallel with 85 min delay.

Then I do again "Add Plot" followed by "Add Plot to Queue" then it just keeps the plots idle until any of those 7 plots finishes.

I wish I could just create 7 parallel plots with 85 delay and 29 plots after that which are waiting in a que.

**Comment by razamataz** [comment]
используй планировщик

**Comment by Elerong** [comment]
> используй планировщик
What do you mean? 
I am referring to Windows Client with the GUI

**Comment by razamataz** [comment]
используй файл CMD , командная строка, для очереди - n
используй Task Scheduler для запуска по времени.

**Comment by C0braChicken** [comment]
110% agree with Elerong's  post. The que and plot system just doesn't make any sense the way it's setup. It's like a big game as to how to get the right amount of plots going at the same time, due to the exact issue he describes. After you have any plots running, all queued plots should be added to the que, none of them should start until another is finished.

The weird thing is after the system has been running for half a day, the que system works the right way, and you can add as many ques as you like with no issue. But getting the first set of plots running in parallel with timings and queued working is a complete nightmare. due to queued plots starting before any of the parallel plots are finished

Also why is there an option to delete a plot, but it is just grayed out? So if the queued plots are misconfigured, I can't just delete the misconfigured ones, and add new queued plots, I have to kill the whole program, and restart everything. I bet I have lost over 20 plots trying to get the plotting system working correctly.
