### ISSUE TITLE
Support http and socks proxy. [REQ]

### ISSUE THREAD

**Issue by jjjan** [Chia-Network/chia-blockchain#3118]
As we have lost connectivity to peering network because of some firewall and government policy. we need http proxy or socks for reliable connection to network. thanks indeed

**Comment by murat80** [comment]
I am having a similar problem. Did you find a solution?

**Comment by sashka4** [comment]
hi, any traction with the subject? chia runs over websockets so perhaps ws-tunnel can be a solution

**Comment by mcybz** [comment]
Anyone sucessfully got it tunneled / proxied?

**Comment by fullet-tortuga** [comment]
It's funny how all issues are being sistematically closed because of inactivity from the programmers. LOL, never saw such a thing in my life. We're not fixing this, so we're closing this X-D

As I mentioned before, I connect to the blockchain over a proxy (Tor). Specifically over IPv4 for added security. I'd elaborate more on that but I've been banned from the thread where I was giving the solutions to the problem for speaking incomfortable truths. Oh well, sorry.
