### ISSUE TITLE
[BUG]Plot Dont pass from 1%

### ISSUE THREAD

**Issue by heee91** [Chia-Network/chia-blockchain#3133]
I am using linux mint and when i put ploting dont pass from 1%
Im doing something rong?
thanks

**Comment by belov38** [comment]
Have the same error. Stuck on 1% with the following log message

![image](https://user-images.githubusercontent.com/20417446/116666204-ceb1c700-a9ee-11eb-9569-16a7a987b2db.png)

**Comment by henry455168** [comment]
I have the same problem

**Comment by keliew** [comment]
Bad hardware?

**Comment by henry455168** [comment]
I'm already figured out the problem,just change the destination file's name

**Comment by heee91** [comment]
Not work for me. Or I'm doing something rong..

**Comment by henry455168** [comment]
https://youtu.be/5aMhDfJyRsw

**Comment by yingzi-9527** [comment]
I made the same mistake. How did I solve this problem?

**Comment by belov38** [comment]
For me works re-launch plotting

**Comment by SquareMesh** [comment]
Also had issue (1.1.3), Windows 10, AMD Ryzen 5 3600 6-Core, new mobo. Restarting plotting 3 times and no change. Running 4 plots in parallel stopped at 1%.  YouTube link above helped in thinking about paging file.  Noticed that system was not managing paging file and it was set based on earlier memory setup (have since upgraded to 32GB RAM) and so changed to allow system to manage paging file. Rebooted.

Re-ran plotting 4 in parallel, 20GB, 4 processes.  3 of the 4 plots proceed past %1, one however still has error (as per original post) when clicking on View Log against plot.  Plots were delayed to starting at 3 minute intervals.

Unclear why not all 4 worked but at least I have plotting progressing.  Will update if I discover they failed at later stage.

Appears as though I had paging file set to low amount of space compared to 20GB I was trying to use.
