### ISSUE TITLE
[BUG] Challenge times increase during final copy of plots

### ISSUE THREAD

**Issue by Akaino** [Chia-Network/chia-blockchain#3203]
**Might not be an actual bug**
Challenges take longer when new plots are being copied to any plot directory.

**To Reproduce**
Plot something. Wait for final copy. Check challenge times.

**Expected behavior**
Challenge times shouldn't take longer, I guess?

**Screenshots**
Challenges during copy
![Screenshot1](https://i.imgur.com/gv1C8sa.png)

Plot 1/2 copied successfully
![Screenshot2](https://i.imgur.com/kV6i5h6.png)

Plot 2/2 copied successfully
![Screenshot3](https://i.imgur.com/FcAY7KH.png)

**Desktop (please complete the following information):**

- OS: Windows 10 [10.0.19041]
- OS Version/Flavor: Windows 10 [10.0.19041]
- CPU: Intel Core i7 9900k

**Additional context**
The application simply reads logs from the default logs directory and throws data into the graph and table.

Plotting with cli, 2 parallel, staggered by 60 minutes:
> chia plots create -k 32 -b 4000 -r 4 -u 128 -n 28 -t T:\Temp -2 T:\Temp2 -d Q:\
>>T: = TempDir [NVME]
Q; = FinalDir [SATA HDD] or [Synology NAS] (issue exists in both cases).

So far I'm not missing challenges.

**Comment by sargonas** [comment]
This is likely due to the fact that the challenge time is a result of system resource availability, especially drive I/O . If you are peaking some of your I/O on the drive you’re farming from when trying to copy the files into it, then the challenges are going to take a few milliseconds longer while the copy is underway as the threads wait their turn.
