### ISSUE TITLE
[Bug] Daemon Taking up a lot of ram and two more issues. [It cause the system crash, Restart, Black Screen and Frozen]

### ISSUE THREAD

**Issue by BILLFANLL** [Chia-Network/chia-blockchain#3209]
[image](https://user-images.githubusercontent.com/42637312/116683005-5e0ca980-a9f2-11eb-834b-b4115a5a8491.png)
1. Process: daemon. It may not be shut down normally, causing Full Node page cannot update and the RAM usage to keep increasing until the system crashes. Please fix that. Chia 1.1.2
2. And Ploting process can not close when chia have been closed. Processing frozen and RAM is not be clean.
3. When the main chia program is finished, and open it again, it's very difficult find node.

If this helps you, 
Receive Address: xch1ctlr23cxqsky2k452kjm438z6msn9zvx5fu5zanthhpsytcqx03q3unq60

Thank you

**Comment by ddemilla** [comment]
I am experiencing this as well on my Ubuntu 20.04 installation.

I am plotting on multiple ssd's (about 5) and it seems that I can get through one iteration (parallel plots on all SSD's) before the RAM starts to explode. I am usually sitting around 60gb usage for that first round but then it shoots up and up until my system freezes. I have 256gb of RAM installed so clearly it is a memory leak of some sort. This is the second day in a row that this has started. I'm going to try stopping the daemon but it is annoying because I lose plotting process every time I have to restart. 

Is there a safe way to clean out this issue without losing plotting progress?

**Comment by mariorangel777** [comment]
I have a similar issue, when I start the software and tries to sync, my Pc frozen/crash. I don't have time to check if it's the ram.

**Comment by BILLFANLL** [comment]
> I am experiencing this as well on my Ubuntu 20.04 installation.
> 
> 
> 
> I am plotting on multiple ssd's (about 5) and it seems that I can get through one iteration (17 parallel plots on all SSD's using about 48 threads) before the RAM starts to explode. I am usually sitting around 60gb usage for that first round but then it shoots up and up until my system freezes. I have 256gb of RAM installed so clearly it is a memory leak of some sort. This is the second day in a row that this has started. I'm going to try stopping the daemon but it is annoying because I lose plotting process every time I have to restart. 
> 
> 
> 
> Is there a safe way to clean out this issue without losing plotting progress?

It's should be fixed on lasted version. There should be no way to continue plotting when plotting terminates.
