### ISSUE TITLE
Unable to update plots from Windows UI

### ISSUE THREAD

**Issue by A-Caccese** [Chia-Network/chia-blockchain#327]
Hi,
I'm using the Windows version of electron UI. When a new plot is finalized, I expect that it should be automatically detected and added to working plots. Instead, I see this error: `These plots are invalid, you might want to delete them forever`. However, if the UI is restarted, the new plot is correctly added to working plots and the error message is no longer displayed.

**Comment by hoffmang9** [comment]
It's a known issue where harvester reads the plot file before it's fully copied in and then incorrectly blacklists it.

Try again in 20 minutes: https://github.com/Chia-Network/chia-blockchain/pull/326
Atomically copy to try to avoid: https://github.com/Chia-Network/chiapos/commit/7bb45eeafc9f62ed6eac394450b29f5a109b2bd3

Will be fixed in 1.9. Workaround is to restart when it happens for now.
