### ISSUE TITLE
[REQ] Ability to Pause, cancel, resume, start 

### ISSUE THREAD

**Issue by rcamarda390** [Chia-Network/chia-blockchain#3319]
**Describe the request**
I am new to this, and didnt find already requested: 
When I launch windows GUI and there are existing farms, farming starts immediately. 
I'd like more control to be able to start, pause, cancel and resume farming

**Comment by JoNiLiGhT** [comment]
x2

**Comment by sargonas** [comment]
Pause has been confirmed in https://github.com/Chia-Network/chia-blockchain/issues/1772 to be on the roadmap for a future update.

As for canceling/deleting, the Delete Plot function in the GUI was temporarily removed in 1.1.0 due to a bug, and is intended to be restored once resolved.

https://github.com/Chia-Network/chia-blockchain/blob/main/CHANGELOG.md#110-chia-blockchain-2021-04-21

**Comment by rcamarda390** [comment]
thanks all!
