### ISSUE TITLE
[BUG] Temporary space requirement is higher than described

### ISSUE THREAD

**Issue by Ivaylo-Lafchiev** [Chia-Network/chia-blockchain#3405]
**Describe the bug**
According to the docs, to create one plot you need to have 232GB of temp space. However, if I try to create 3, or even sometimes 2 parallel plots on a 1TB SSD (953GB usable), I will often run out of space and all the plots will freeze.

**To Reproduce**

Try to create 3 parallel plots on 1TB SSD

**Expected behavior**
953/232 = ~4, I would expect to easily be able to plot 3 plots without running out of space.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Win 10/Chia 1.1.2

**Comment by gromran** [comment]
This is how (x)LC SSDs work. That doesn't come from the Chia Tool.

**Comment by Ivaylo-Lafchiev** [comment]
> This is how (x)LC SSDs work. That doesn't come from the Chia Tool.

Can you elaborate what you mean exactly?
I've tried googling for this but aside from some small discrepancies caused by small files using the minimum allocation size for the disk, I did not find any explanation for this behaviour. 

 If this is an issue with all QLC/TLC SSDs then it should be clarified in the docs.

**Comment by gromran** [comment]
- Make a note of the free space on your SSD
- Copy a lot of data onto it, let's say 50GB
- See how the free memory develops
  At first, more space is used than the data really needs and it is only released again after a while
This is due to the fact that the cells are not written with multiple levels at the same time, but rather the SLC cache is used first and then cleared up later by the controller

**Comment by Ivaylo-Lafchiev** [comment]
> * Make a note of the free space on your SSD
> * Copy a lot of data onto it, let's say 50GB
> * See how the free memory develops
>   At first, more space is used than the data really needs and it is only released again after a while
>   This is due to the fact that the cells are not written with multiple levels at the same time, but rather the SLC cache is used first and then cleared up later by the controller. In addition, whole blocks always have to be written. Here, too, the controller only distributes correctly later.
> 
> > If this is an issue with all QLC/TLC SSDs
> 
> is not a issue! SSDs work like that

An 'issue' is perhaps not the right word, but the point still stands - this should be clarified in the docs as it is really not obvious how much space plots are actually going to take.

**Comment by lvcivs** [comment]
I was under the impression that ≈ 250 GB should be enough. So your case does definitely sound strange.

During the beta development phase, it once happened to me that the temp dir for a single plot grew to about 3 times as much space as expected, filling up almost the entire disk and leading to a freeze of the process. I thought that it was likely a bug (chia being beta at the time). I had to delete the temp dir and start over. It has not happened again for me since then, though.

**Comment by sdbarrish** [comment]
Phase 4 = 663.614 seconds. CPU (87.060%) Sun May  2 00:41:54 2021
Approximate working space used (without final file): 269.268 GiB
Final File size: 101.315 GiB

2TB raw capacity = 6 concurrent k32 plots if -t, -2, and -d are all on the same drive.

**Comment by Ivaylo-Lafchiev** [comment]
I don't need to read the logs to tell you that my 953GB SSD is 100% full at 32% of the plotting process, with 2 parallel k32 plots.
Before starting the drive was 100% empty.

**Comment by sdbarrish** [comment]
> I don't need to read the logs to tell you that my 953GB SSD is 100% full at 32% of the plotting process, with 2 parallel k32 plots.
> Before starting the drive was 100% empty.

Apology if you thought my response was directed towards you. It was not. I was refuting others by giving demonstrable evidence and where to look to substantiate your claims.

The developers need to modify the temporary storage statement.

**Comment by Daniel-Fan** [comment]
I could also confirm this.

My 960G SSD could do 3 plots parallelly through the GUI.
But if I did it through CLI, the disk will be full.

**Comment by Daniel-Fan** [comment]
Just wanna to be specific, when I am using CLI, the size of 3 parallel plots written into the disk at some points is higher than the description.
and the command is `plot create -k 32 `
```
179.85 GB         
269.39 GB   
269.40 GB
```

**Comment by ShadowXVII** [comment]
I also noticed this, 239GiB was predicted space, but it jumped much higher.
For something like a 256GB SSD, obviously plus filesystem, this won't fit. But the "Peak" usage does seem higher than 239GiB.

Is it perhaps a unit issue setting incorrect expectations -- GiB vs. GB? This might be causing the confusion.
Running another to check.

**Comment by schehata** [comment]
I am having same problem, I am using the GUI, separate 1TB SATA SSD for plotting. running 1 plot at the mean time, its around 30% and used up around 500GB in temp space, As far as I understand it should just use 256GB. I am running 1 plot because I ran 2 in parallel earlier and they failed because all the SSD space was filled up by them. (the drive was empty, no old temp files or anything)

whats the problem here, any idea on how to fix it?

**Comment by Ivaylo-Lafchiev** [comment]
I think the issue for me was that, ironically, compression was enabled on the drive in Windows. After I disabled that I didn't have this issue anymore.

**Comment by schehata** [comment]
@Ivaylo-Lafchiev that must be it! I remember enabling this when I formatted the drive. I will re-format with that option disabled and see report back. thanks!

**Comment by schehata** [comment]
I can confirm that disabling the compression worked for me too.

**Comment by luotinen** [comment]
I checked and I did not have compression on for the affected drive. I did
however now disable indexing and I am monitoring if it has a positive
impact on the space usage.

ke 2. kesäk. 2021 klo 11.00 Islam Shehata ***@***.***)
kirjoitti:
