### ISSUE TITLE
Farmer screen not refreshing

### ISSUE THREAD

**Issue by dkackman** [Chia-Network/chia-blockchain#367]
I have two cases on the Farmer screen where it is not refreshing automatically. 
### Environment
- Windows 10
- Chia beta 10 UI and Farmer
- 1 remote harvester running Chia beta 10 on a Pi4 w Ubuntu (I don't believe that's related)

#### Repro
- start the UI with an active farmer/harvester, go to the farmer screen and leave it open there
- wait until the farmer successfully farms some chia. (of course this is a bit of a chicken and an egg because you won't be able to tell via the UI, but trust me, if you wait long enough)
- Note the **Total chia farmed**, and **Last height farmed** values
- Navigate to any other screen and back to the Farmer screen
- **Total chia farmed** and **Last height farmed** will reflect latest values

#### Repro
- in [the attached screen cap video](https://github.com/Chia-Network/chia-blockchain/files/5106314/Chia.Blockchain.2020-08-20.20-35-15.zip) note the **Up/Down** values for the harvester at `192.168.1.220` before and after the removal of the harvester at `127.0.0.1`, it changes from **154/152 KiB** to **196/207 KiB**.

**Comment by mariano54** [comment]
OK, I think I know the reason for this. in incoming_api.js, we need to create a new object for the wallets array (instead of just updating the previous object) to force the React component to update. 

For the connection refresh issue, we are purposely not updating the connection data number on every request (because this would flood the node with api calls). We could do a periodic update instead (1 min)

**Comment by hoffmang9** [comment]
Should be fixed by the full GUI refactor - https://github.com/Chia-Network/chia-blockchain/releases/tag/1.0beta16
