### ISSUE TITLE
[REQ] Pause & resume plotting w/o losing progress

### ISSUE THREAD

**Issue by auc0le** [Chia-Network/chia-blockchain#3724]
Due to the need to reboot or say a power failure or to even change the drive path being used, the plotter should support pause and resume without a percentage loss.  These are long operations and to expect perfect operating conditions is to betray reality with blind hope.

**Comment by MikhailZelenkov** [comment]
I support. It's a shame when after 15-20 hours the electricity goes out and there is only 5-10% left to complete the work.

**Comment by danktankk** [comment]
+1

**Comment by Georgeibe** [comment]
+1

**Comment by gabcraftia** [comment]
+1

**Comment by nie3e** [comment]
+1

**Comment by tibbon** [comment]
I'd highly recommend a UPS on the system, but still, conceptually being able to pause would be great. Sometimes systems do need restarts for hardware upgrades, software patches, etc... and losing a significant portion of progress is blah. 

The real question, is there something inherently about plotting that doesn't allow for this? What is that, and could it be mitigated?

**Comment by daniel1v4** [comment]
Even if you could mark a plot to pause after it completes a stage, (eg. pause after completing stage 1; or, pause after current stage completes) to allow reboot (eg for updates, hardware changes), without having to kill a dozen or so plots. This would add so much more value to the process.

**Comment by gabcraftia** [comment]
> Even if you could mark a plot to pause after it completes a stage, (eg. pause after completing stage 1; or, pause after current stage completes) to allow reboot (eg for updates, hardware changes), without having to kill a dozen or so plots. This would add so much more value to the process.

that is also a option yes. like we just need a way to pause and resume later

**Comment by matthewjbauer** [comment]
I have my plotting PC and server on a UPS. However, I had an issue where Remote Desktop kept creating a new user instance every time I logged into my plotting PC causing me to lose all my plotting. I use anydesk now to monitor everything except my server. If I can get a decent price on at least 2x 512+ Sandisk portable SSDs, or one of those Sabrent rocket thunderbolt/USB-C drives + a Sandisk portable SSD, I may use my gaming laptop to plot while I am at work (and monitor it with anydesk). That said, I'm scared to do that because I don't want to shorten the life of an expensive piece of tech (most expensive single item besides my house or car I've ever purchased even if you include combined MSRP of all the current parts in my gaming desktop).

**Comment by SurvivingPsycho** [comment]
I would support this.
