### ISSUE TITLE
[REQ]How to open port 8444？

### ISSUE THREAD

**Issue by uwerui** [Chia-Network/chia-blockchain#3836]
How to open port 8444？
win10

**Comment by rangerov** [comment]
If your IP is dynamic, you are in trouble.

**Comment by uwerui** [comment]
> 如果您的IP是动态的，那么您就有麻烦了。

17/5000 
I am a static IP, how to open port 8444

**Comment by ThalesC** [comment]
> I am a static IP, how to open port 8444

It depends on your network setup, you need to port forward 8444 through the computer's network route.

Let's say, for example, that you have a setup like this: `ISP  ->  Router1  ->  Router2  ->  Computer`
You need to configure a port forwarding rule on the `Router1` to point port 8444 to `Router2`'s IP address, and configure another rule on `Router2` to point port 8444 to your computer's IP address on the same port and finally, if you have a firewall on your computer, allow TCP connections on port 8444.

If for some reason your ISP blocks port 8444 you'll have to call them and ask to allow connections through this port, but in general they don't block it, so you should be fine.

**Comment by Deses** [comment]
Try googling: "router brand and model how to open ports".

**Comment by chiabug** [comment]
Be aware that the pop-up that occurs in windows asking to enable the port is just enabling the port in the windows firewall.  You may still need to go to your router and enable the port via a port forwarding rule.  Many people just have one router between them and the isp.  Often that router is at 192.168.1.1 but could other addresses depending on your local configuration.  You would have to login to the router and set the rules to enable incoming traffic on port 8444 to forward to the local ip address of the machine handling the sync and farming.

**Comment by knightcomm** [comment]
@ffarhoosh My router would not allow me to port forward to 8444.  What did work for me was editing my IPv4 Firewall with a new rule to allow TCP traffic on port 8444.  Now, all of my computers on my network have access.  You can verify the port being open with the following site: https://www.yougetsignal.com/tools/open-ports/  Good luck!

**Comment by ari2asem** [comment]
> @ffarhoosh My router would not allow me to port forward to 8444. What did work for me was editing my IPv4 Firewall with a new rule to allow TCP traffic on port 8444. Now, all of my computers on my network have access. You can verify the port being open with the following site: https://www.yougetsignal.com/tools/open-ports/ Good luck!

by ipv4 firewall you mean any software firewall on your cumputer ? or hardware firewall like pfsense or opsense ??

because i have the same problem. port is forwarded in my dsl-modem, but i cann't make connection on port 8444. my computer is also behind a switch. as far as i know switches does not have feature like port forwarding. maybe i am wrong about this. but plz, any reply.

thanks

**Comment by Medya87** [comment]
TCP    127.0.0.1:49980        Medya:8444             ESTABLISHED
  TCP    127.0.0.1:50171        Medya:8444             ESTABLISHED

А вот тут https://www.yougetsignal.com/tools/open-ports/ показывает что порт закрыт 
 Port 8444 is closed 
How it`s fix?

**Comment by Medya87** [comment]
> TCP 127.0.0.1:49980 Медиа: 8444 УСТАНОВЛЕН
> TCP 127.0.0.1:50171 Медиа: 8444 УСТАНОВЛЕН
> 
> А вот тут https://www.yougetsignal.com/tools/open-ports/ показывает что порт
> закрыт Порт 8444 закрыт
> Как это исправить?

Вот это пофиксил, с помощью настройки виртуального сервера в роутере.

**Comment by knightcomm** [comment]
@ari2asem sorry for the delayed response; work has been insanely busy. I allowed port 8444 through IPv4 settings on my hardware portion of my router.  Only managed switches can block ports.  If you are a Windows user, make sure that the app is allowed on your firewall settings if you are using Windows 10 as well.  Sometimes being set to a public network will block everything, including network drive shares.  Otherwise, on Linux, use the "sudo ufw allow 8444" command iirc. (kind of rusty with *nix systems now).  Hope it helps!
