### ISSUE TITLE
[help] argument of type "NoneType" is not iterable

### ISSUE THREAD

**Issue by aresstokrat** [Chia-Network/chia-blockchain#3880]
**Describe the issue**
1.1.4 problem, stuck fo a day
for every action i got

argument of type "NoneType" is not iterable

great update for me )

cant fix it, what to do ?

**Screenshots**
http://prntscr.com/12jvyxc

**Additional context**
update from 1.1.1 to 1.1.4

**Comment by aresstokrat** [comment]
in console::

  File "chia\plotting\create_plots.py", line 155, in create_plots
TypeError: argument of type 'NoneType' is not iterable
[29896] Failed to execute script chia

**Comment by daveeyres** [comment]
Check your **config.yaml** file. 
I had the same issue which was due to my sloppy keystrokes adding a random character on a line where it shouldn't have been.....

If this is indeed same issue I had....Check your logs for the line number and review that line of the config.yaml.
e.g. From aresstokrat's comment, his looks like it was on line 155, so possibly something to do with **chia_ssl_ca**:
