### ISSUE TITLE
Faild to open (invalid plots)

### ISSUE THREAD

**Issue by lexxfreeman** [Chia-Network/chia-blockchain#3892]
I'm sorry, but what does that mean? There were 1.2 TB of rafts. And now I see it!

![image](https://user-images.githubusercontent.com/54878790/117244417-8b7eaa80-ae6b-11eb-9db1-4a78f958a271.png)

**Comment by tspimentel** [comment]
@lexxfreeman  i had the same problem. After search for a solution on internet and lost any chance to recovery my files or resolve the problem i stoped and think..... And if i reboot my computer ?

I restarted my PC and the problema was resolved! 

Try the same and tell me if the problem was resolved.

**Comment by lexxfreeman** [comment]
> @lexxfreeman i had the same problem. After search for a solution on internet and lost any chance to recovery my files or resolve the problem i stoped and think..... And if i reboot my computer ?
> 
> I restarted my PC and the problema was resolved!
> 
> Try the same and tell me if the problem was resolved.

After the reboot, the problem went away. Let's see what happens next
