### ISSUE TITLE
[REQ] Pause the Ploting

### ISSUE THREAD

**Issue by tiny0little** [Chia-Network/chia-blockchain#3905]
would be really good to have ability to pause the plotting process, quit the GUI/reboot PC, and continue. thx!

**Comment by Gohsteu** [comment]
will not work, this is how Chia works or many of other Cryptos

**Comment by olafbuitelaar** [comment]
I wonder if this error mechanism; https://github.com/Chia-Network/chiapos/blob/main/src/plotter_disk.hpp#L416 could be used to pause the plotting temporarily, so you can continue later, of course with-out killing the plotter process it self, but just the "snooze" it for a while if needed.

**Comment by sargonas** [comment]
Pause has been confirmed in #1772 to be on the roadmap for a future update.

As for canceling/deleting, the Delete Plot function in the GUI was temporarily removed in 1.1.0 due to a bug, and is intended to be restored once resolved.

https://github.com/Chia-Network/chia-blockchain/blob/main/CHANGELOG.md#110-chia-blockchain-2021-04-21
