### ISSUE TITLE
Wasn't able to add transaction with id  status 3 error: Err.DOUBLE_SPEND[help]

### ISSUE THREAD

**Issue by exzver** [Chia-Network/chia-blockchain#3917]
Please tell me, what is that? Version 1.1.4.

**Comment by MOVZX** [comment]
Your Internet is too slow to compete with another farmers.

**Comment by exzver** [comment]
My internet is 300 mb/s, in all other programs everything is ok

**Comment by iLexGit** [comment]
This has already been answered by the developers:

"_MEMPOOL_NOT_INITIALIZED happens when you are just starting up your node. If you are still seeing this, restart the node.
I will explain why DOUBLE_SPEND is printed. Let's say you have transactions A, B and C in the mempool. The mempool is where you keep transactions that people send, but have not been included in a block yet.
Let's say you then get a new block, which includes transactions B and C. What do we do with the mempool? We create a new mempool, and try to add all transactions to it. When we add tx A, it validates with no problem. However when we try to add transactions B and C, they are no longer valid because they are trying to spend coins which have already been spent. Those transactions are conflicting with the same transactions that just got included. So that is how we clear the mempool from old transactions.
There are some differences with chia and other coins, because any 2 transactions can be combined. It's possible that the block did not include B and C, but it included another transaction X, which is a combination of multiple transactions (BCD) for example. So in this case, transaction B was never included on chain, but a conflicting transaction was. So B is now considered a "double spend" and is no longer valid. So this is how we filter out things from the mempool when we get a new block: we just try adding them all again one by one.
We can remove these warnings so there is less confusion_
"

**Comment by peachlafun** [comment]
"MEMPOOL_NOT_INITIALIZED happens when you are just starting up your node. If you are still seeing this, restart the node.

How to restart the node ?

**Comment by shaunlourdes84** [comment]
hi team,

So what is the solution for this, show I delete all my 57 plot and replot from start. I am new to this mining buzz and trying to learn all the possible error i see. But from the day i have update to the new version 1.1.5 i am only see this 3 error: Err.DOUBLE_SPEND logs after log which keep generating consistently

**Comment by brause** [comment]
well, i am no expert. But deleting plots is certainly not necessary.  This is a message that pops up when the blockchain is out of sync.  That is all.

**Comment by chevanton1988** [comment]
I have the same problem with this? Same error: status 3 error: Err.DOUBLE_SPEND. Does anybody know what is this?

**Comment by jeff-zone** [comment]
I'm getting this error as well (version 1.1.5), it's not constant but it happens every couple of minutes.  Is there a way to restart the proper services on a windows machine using the chia GUI?  Can I run some commands via the command line to restart the specific services so I don't lose my current plots which are in the process?  What happens if I don't restart anything and take no action?

Thanks in advance.   -Jeff

**Comment by mariano54** [comment]
This is fine. These errors are removed in the next version.

**Comment by jeff-zone** [comment]
Thanks, so you're saying I can ignore them for the time being?

**Comment by chevanton1988** [comment]
> This is fine. These errors are removed in the next version.

Do you mean in version 1.1.6.? Because version of my wallet is 1.1.5.

**Comment by jeff-zone** [comment]
They mean that they are currently working on it and it will be addressed in
the next release.
