### ISSUE TITLE
[help]many error in log

### ISSUE THREAD

**Issue by ywwz** [Chia-Network/chia-blockchain#3926]
I found many error in log
"
2021-05-06T19:12:13.063 harvester chia.harvester.harvester: WARNING  Looking up qualities on C:\ALL\25\plot-k32-2021-05-06-00-23-1653d06646c2b09bf3af1e45722bcdb845cd991c7d1b8805bef1535659fceccf.plot took: 5.342714548110962. This should be below 5 seconds to minimize risk of losing rewards.
2021-05-06T19:12:31.534 harvester chia.harvester.harvester: WARNING  Looking up qualities on C:\ALL\24\plot-k32-2021-05-04-22-55-5ab77d1858d04fefcece7c1f936c5326a95c54d4991991f67d75918fac0784b3.plot took: 5.582074880599976. This should be below 5 seconds to minimize risk of losing rewards.
2021-05-06T19:14:25.926 harvester chia.harvester.harvester: WARNING  Looking up qualities on C:\ALL\19\plot-k32-2021-04-30-09-44-5c1d4f62590f2b522ab75117d029ae5936c83e6881d84dc8f4a6f1e8471726d8.plot took: 5.2639007568359375. This should be below 5 seconds to minimize risk of losing rewards.
"
how can i fix it?

**Comment by hbroer** [comment]
The disk is too slow. Are you parallel plotting with temp folder on the same disk where this plots are? Accessing the plots takes just above 5 seconds, that causes the error message.

**Comment by ywwz** [comment]
> The disk is too slow. Are you parallel plotting with temp folder on the same disk where this plots are? Accessing the plots takes just above 5 seconds, that causes the error message.
thx.
above 5s is very slow?
generally, what  speed is normal?

**Comment by hbroer** [comment]
I don't know. I would say something below 1s. Even over network or USB I personally would expect something ~100ms as normal. My USB hard disc has under a single plotting load ~ 10ms to 1s with peaks up to 3s average response time. Don't know how much you need to add/multiply for the lookup by the harvester.

I would say: don't plot in parallel on HDDs and use it for farming at the same time. It isn't very usefull to plot in parallel on HDDs at all because the HDD heads need much time to switch position. That's the main difference compared to SSDs and the reason why they are much faster for (parallel) plotting.

**Comment by ywwz** [comment]
> I don't know. I would say something below 1s. Even over network or USB I personally would expect something ~100ms as normal. My USB hard disc has under a single plotting load ~ 10ms to 1s with peaks up to 3s average response time. Don't know how much you need to add/multiply for the lookup by the harvester.
> 
> I would say: don't plot in parallel on HDDs and use it for farming at the same time. It isn't very usefull to plot in parallel on HDDs at all because the HDD heads need much time to switch position. That's the main difference compared to SSDs and the reason why they are much faster for (parallel) plotting.

thx for your reply.
I use the usb hub with many poarts,so ... it may be slow.

**Comment by ywwz** [comment]
> I don't know. I would say something below 1s. Even over network or USB I personally would expect something ~100ms as normal. My USB hard disc has under a single plotting load ~ 10ms to 1s with peaks up to 3s average response time. Don't know how much you need to add/multiply for the lookup by the harvester.
> 
> I would say: don't plot in parallel on HDDs and use it for farming at the same time. It isn't very usefull to plot in parallel on HDDs at all because the HDD heads need much time to switch position. That's the main difference compared to SSDs and the reason why they are much faster for (parallel) plotting.

the log means, everything else is normal but these are too slow. or the application reading plots is too slow, no read the all plots.

**Comment by hbroer** [comment]
You can expect all to be too slow on that drive not only one of the plots. I am not sure but I don't think it accesses all plots so it will only pop up if it does access a plot.

But like I said use different drives for plotting and for farming. And you did now write anything about your  setup so I can only guess a potential problem. I have no problems with latency and my plots are on slow daisy chained USB drives.

**Comment by ywwz** [comment]
> You can expect all to be too slow on that drive not only one of the plots. I am not sure but I don't think it accesses all plots so it will only pop up if it does access a plot.
> 
> But like I said use different drives for plotting and for farming. And you did now write anything about your setup so I can only guess a potential problem. I have no problems with latency and my plots are on slow daisy chained USB drives.

thx for your reply.
I read some chia wiki document. I guess the error means reading plots are slow. I don't know the speed greater than 5s, will it effect my farming? as I have 1000- plots but no XCH :(
I don't know what step is correct, may it looks strange. if you want, you can help me to find a correct step.
now, I have 5 PCs, they all installed chia GUI. every day, I create plots in GUI on 4PCs and move plots to another PC, the PC is farming all day, it's my main machine.
all PCs use the same chia account. recently,I found the 4PCs have to disable UPNP feature or else my main machine often has not synced. or other errors.
maybe that why I didn't get anything in chia.
I want to find the way to create plot without GUI, it should be
”chia.exe plots create -k 32 -n 1 -b 3390 -f xxx...xxx -p  xxx...xxx -a xx..xx -u 128 -r 2 -t D:\TEMP -2 D:\TEMP -d D:\“
is my way powerful solo?

**Comment by hbroer** [comment]
That's a lot of plots :D It can happen that you have a ton of plots and don't get any rewards. It is a lottery. Pooling will come this month if I did understand it right.

Your plotting sounds fine. Plotting with CLI will be easier, you found the right way to do that. On my plotting machine I have a script I just start twice (only 8GB Ram):

```
cd ~/AppData/Local/chia-blockchain/app-1.1.4/resources/app.asar.unpacked/daemon
./chia.exe plots create -n 20 -k 32 -b 4000 -f xxx...xxx -p xxx...xxx -t "C:\_Chia Temp" -d "E:\_Chia Farm"
```

It is bash (even on windows I use git bash). But will be similar if you use the Windows CMD.

I don't use the -a flag but I am not 100% sure if it is ok or not. I have installed Chia GUI on that system and booted it up. Hope I did not do that wrong. :D The wiki did not sound like I do need the -a flag when plotting on another machine.

I also let -r the default. But thats fine if you set them to a value. You don't need to set -u too. It should be 128 and thats the default AFAIK.

But your problem in general is the access speed of your USB drives on the farming machine. How many drives are linked together? It can be that the Hub causes the Problem. Also maybe take a look into the Block Diagram in your mainboards manual and check if the ports are dedicated or if they are also internal privided by a hub. Then maybe change the ports on your mainboard to balance it a little. I had also Problems with the USB of my B550 Mainboard. Currently all drives daisychained on one port because of the problems (and only one plotter runing directly on one drive). But I also have only 4 drives on that Port. Thats way less than you have. A cheap solution could be to get a Raspberry PI 4 (the cheapest you can get should be ok likte 1GB or the 2GB version) and check out how many drives can that PI use for farming without any problems. It has 2 USB3 Ports which are internaly provided by one chip conected to the SoC by PCIe 1x. With two 4-Port hubs it may be able to host 8 drives. I think that will be possible. But it is just guessing.

I am not sure if .X seconds above 5 seconds are a big problem. I think they have choosen a random number which is above the typical expected maximum access times. Your machine has less than 30 seconds to answer with a correct result. It can be that everything below 10 sec for plot access is fine. So don't panic and just figure out if you are able to lower the latency. If not just watch and hope you don't get much higher than your current 5.X seconds. Or try a small Pi Setup. :D

**Comment by ywwz** [comment]
> That's a lot of plots :D It can happen that you have a ton of plots and don't get any rewards. It is a lottery. Pooling will come this month if I did understand it right.
> 
> Your plotting sounds fine. Plotting with CLI will be easier, you found the right way to do that. On my plotting machine I have a script I just start twice (only 8GB Ram):
> 
> ```
> cd ~/AppData/Local/chia-blockchain/app-1.1.4/resources/app.asar.unpacked/daemon
> ./chia.exe plots create -n 20 -k 32 -b 4000 -f xxx...xxx -p xxx...xxx -t "C:\_Chia Temp" -d "E:\_Chia Farm"
> ```
> 
> It is bash (even on windows I use git bash). But will be similar if you use the Windows CMD.
> 
> I don't use the -a flag but I am not 100% sure if it is ok or not. I have installed Chia GUI on that system and booted it up. Hope I did not do that wrong. :D The wiki did not sound like I do need the -a flag when plotting on another machine.
> 
> I also let -r the default. But thats fine if you set them to a value. You don't need to set -u too. It should be 128 and thats the default AFAIK.
> 
> But your problem in general is the access speed of your USB drives on the farming machine. How many drives are linked together? It can be that the Hub causes the Problem. Also maybe take a look into the Block Diagram in your mainboards manual and check if the ports are dedicated or if they are also internal privided by a hub. Then maybe change the ports on your mainboard to balance it a little. I had also Problems with the USB of my B550 Mainboard. Currently all drives daisychained on one port because of the problems (and only one plotter runing directly on one drive). But I also have only 4 drives on that Port. Thats way less than you have. A cheap solution could be to get a Raspberry PI 4 (the cheapest you can get should be ok likte 1GB or the 2GB version) and check out how many drives can that PI use for farming without any problems. It has 2 USB3 Ports which are internaly provided by one chip conected to the SoC by PCIe 1x. With two 4-Port hubs it may be able to host 8 drives. I think that will be possible. But it is just guessing.
> 
> I am not sure if .X seconds above 5 seconds are a big problem. I think they have choosen a random number which is above the typical expected maximum access times. Your machine has less than 30 seconds to answer with a correct result. It can be that everything below 10 sec for plot access is fine. So don't panic and just figure out if you are able to lower the latency. If not just watch and hope you don't get much higher than your current 5.X seconds. Or try a small Pi Setup. :D

in the beginning,I use GUI and same chia account without any other configure. so everyday the application show "full node not synced" or "wallet not synced" and so on.  many network problem or other errors. now I found plotting machine disable UPnP may be a key point, and just main machine enable UPnP.
I bought some USB3.0 hub have 16 ports. and my PC's motherboard is X99, I tested, it can connected 16 USB3.0 devices. I read some information(like https://acroname.com/blog/how-many-usb-devices-can-i-connect ), Intel series 8 motherboard limit 32 USB3.0 devices, It sounds like Intel 9 or greater motherboard will solve my program. and then I bought B460 and i3-10100 to be a farming machine, but in my test, it can connect 32 USB3.0 devices too :(  finally I use B460 and some PCI to USB 3.0 card, I can store a lot of plots. in my case, I can't  speed up my disk access. so I want to know what time my machine spend to answer a correct result. I turned log level to "INFO" in config.yaml file. but I see log, there are no changes. do the application need to restart? In view of the fact that I still have no harvest,I want to keep stable. I think everything is correct now, maybe a week I will see the XCH :D

**Comment by ywwz** [comment]
CLI has many default value, I know. 
and I wrote a application to help me do plotting. I wrote it in C#.

**Comment by swissarmybox** [comment]
@hbroer couldn't it be caused also by when writing from the SSD to the HDD after the last phase the farming happens at the same time on that HDD, therefore causing it to slow?

**Comment by jedocampo** [comment]
was this error resolved? as i am getting this problem too on 2 of my external HDD.. one HD only have 4 plots and farming and the other one have 60 plots before it started showing this error... i only use these drives as my final drive and i dont plot in them.. and there are no files being move on my HD drive with less plots but its showing a 18 secs on the error log

**Comment by druum34** [comment]
I am having same issue and I'm not sure what is wrong. The drive is fast a wd 16tb gold...the only thing I can think is I'm using this as the final destination so when a new plot is transferring it is slowing the drive down so it is therefore making the drive response slow?

**Comment by hbroer** [comment]
> @hbroer couldn't it be caused also by when writing from the SSD to the HDD after the last phase the farming happens at the same time on that HDD, therefore causing it to slow?

I had only spics and log entries 5 to ~ 10 sec while plotting on a external disk. After I stoped that plotting task I have never seen any entry again (~5 days). I think that the copy process of the final plod does not make much impact on latecncy because the write is more sequencial.

I am curious how it will perform for me when I move my farmer from my AMD workstation to a PI but I have only 4x 8TB + 2x6TB (all USB). In my opinion it could be a good idea in general to have less disks per farmer and not to add as much as theoretically possible. That's why I will try smaller machine with "low" HDD count like Pi + 2x 4-port USB hub. But maybe it will also perform well with 2x 8-port. (but I have not that much HDDs and I will not add more until pooling is possible)

**Comment by mauricecyril** [comment]
Is the raspberry Pi the bottleneck?

**Comment by sergestina** [comment]
I have the same prolem on raspberry oi 4 with 4 external HDD (10 TB)...

**Comment by digitalillusion** [comment]
I resolved the slow "Looking up qualities issue" with an external hdd that was going to sleep. I created a cron job that keeps it awake

*/5 * * * * /bin/touch /{path_to_the_hdd}/poke
