### ISSUE TITLE
plots create -- make option to not copy or move final file

### ISSUE THREAD

**Issue by chiabug** [Chia-Network/chia-blockchain#3945]
It would be helpful if there was a parameter that allowed the final plot to not be copied or moved at all.  The process would simply rename the end plot to a .plot and leave it alone.  This would be helpful to offline plotters that use some other method of getting the plot to whatever destination is eventually used for farming.  This would generally be used in conjunction with the -x parameter so perhaps -x2 could mean don't insert the the plot into the config and don't move the plot anywhere after creation.

**Comment by Teellcory** [comment]
Adding to this: if you're plotting and farming on the same drive, once hitting 100%, it will still copy (rather than move/rename) the file. This is a completely redundant write.

**Comment by azaryc2s** [comment]
This is redundant and not really needed. If you specify "dest" as exactly the same as "temp", then it simply renames the plot. If you specify another directory, even on the same drive, it will perform a copy, since it cannot know, if a move is possible or not (it could try to default to move tho, in which case the OS would handle the decision if to cp or mv.

This is so low prio, that it won't get pulled for another year even if some1 implemented it and made a pull request. For now, just do something like "... -t /your/plotting/dir -d /your/plotting/dir ..." and it will do exactly what you want - leave the final plot file where it was plotted.
