### ISSUE TITLE
Is there any argument for lucky value?

### ISSUE THREAD

**Issue by BigUncle** [Chia-Network/chia-blockchain#3975]
I have farmed hundred plots --20 TB 10 days ago, and now is about 60 TB-- for 3 weeks, but i got nothing!
I'm very sad about it.
Is there any argument for lucky value?
If not, would you add this feature ?

**Comment by hbroer** [comment]
It means if you are average lucky you get it in 3 weeks. With way more luck you get it earlier. But you can also never get something if you are unlucky. It is a lottery. That's why I dislike solo mining/farming and whish pooling was done from day one. ;-) If you hover over the questionmark next to the title you also get the info it can take 3 or 4 times longer (and for real even your whole life).
