### ISSUE TITLE
[BUG] Temporary solution for no sync problems.

### ISSUE THREAD

**Issue by MtechBasics** [Chia-Network/chia-blockchain#4012]
For all chia miners who always lose sync...

You need to know some frinds who actualy know the IP Adress of a full node and you can manually connect to the full node in your full node home menue. 
Look under connections, if you are not synced you have 2 ips there and this 2 ips are local ip of your own wallet and node.
Press connect to peer and type in a IP adress of a full node you know, then you get synced again.

**Comment by zouyufei1989** [comment]
Could you share some IPs?  I would appreciate that!

**Comment by DatDraggy** [comment]
Port forward TCP 8444 and you'll find more nodes. Your solution does not work when chia breaks because of a disconnect, which is usually the reason for it not syncing. Currently there is no way around it.

@zouyufei1989 
Introducers addresses:

North Asia introducer-apne.chia.net:8444
South Asia introducer-apse.chia.net:8444
Western North America: introducer-or.chia.net:8444
Eastern North America introducer-va.chia.net:8444
Europe: introducer-eu.chia.net:8444

And then add these nodes addresses:
North America: node-or.chia.net:8444
Europe: node-eu.chia.net:8444
Asia: node-apne.chia.net:8444
