### ISSUE TITLE
[BUG] chia explorer wallet shows incorrect net (coins remaining)

### ISSUE THREAD

**Issue by af85** [Chia-Network/chia-blockchain#4072]
**Describe the bug**
I have ONE wallet. I just transferred 2 XCH out of my wallet.
chia explorer shows that my net is a lot lower than it really is
`chia wallet show` shows the correct balance of my total wallet, minus the 2 XCH i transferred

**To Reproduce**

1. chia version 1.1.2
2. send 2 XCH with fee 0 to another wallet address
3. refresh your chia explorer wallet after the transaction completed, and compare to 'chia wallet show'

**Expected behavior**
local chia wallet and chia explorer wallet should show identical information

**Screenshots**

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Ubuntu 20.04
- CPU: 

**Additional context**
n/a

**Comment by af85** [comment]
Worth noting that I upgraded to v1.1.4, synced wallet, and local wallet still shows correct amount, but explorer is still off.

**Comment by freddiecoleman** [comment]
This is due to change going to a different address.

Your wallet is able to add up the coins for all of your addresses, but Chia Explorer is unable to see any link between different addresses.

A feature that would make this easier to understand is for the Chia wallet to display all of your addresses as it currently hides this and gives the net result.

**Comment by ageorge95** [comment]
This should be brought to their attention.

I want to see how much coins I have in my cold wallet via the explorer. I want to see the same value as in the local GUI.
