### ISSUE TITLE
How to recover a Wallet

### ISSUE THREAD

**Issue by MohZou** [Chia-Network/chia-blockchain#409]
Hi,
I have just moved from beta11 to beta13. On beta11 my Wallet was showing the balance, when moved to the new one my Balance has disappeared. I am using always the same Key.
It never happened, I tried all the versions from Beta8 till now, the Balance was always shown in the next version automatically.

I don't understand how to recover the wallet.
Thank you.

![Wallet_11](https://user-images.githubusercontent.com/71387757/93343018-4c460f80-f830-11ea-9ff6-9f1285e7981e.JPG)
![Wallet_13](https://user-images.githubusercontent.com/71387757/93343041-523bf080-f830-11ea-828a-42c2180f9fbc.JPG)

**Comment by hoffmang9** [comment]
The release notes for beta 12 point out that this is a new chain and test chia balances will not be brought forward to this new chain.

**Comment by MohZou** [comment]
Thanks, I missed that.

**Comment by AquilusZero** [comment]
Hi, due to a corruption of the ssd I lost the data of the .chia folder, they contained everything. Once the operating system with the chia app was re-installed, I entered the mnemonic key but once logged in I did not find my coins on the app. They are still present on my online wallet, how can I recover them? I saw a [guide](https://github.com/Chia-Network/wallets/blob/master/docs/recoverable_wallet.md#:~:text=A%20Chia%20recoverable%20wallet%20is,low%20security%20piece%20of%20information.) that refers to a terminal, which one to be exact? Thank you for your time
