### ISSUE TITLE
[help] Wallet won't sync

### ISSUE THREAD

**Issue by Attix2508** [Chia-Network/chia-blockchain#4158]
My Wallet won't sync. 

Windows GUI
Chia 1.14 is running 

![grafik](https://user-images.githubusercontent.com/83858424/117530258-69586a00-afdc-11eb-8a44-ef020ba212dc.png)

Don't want to restart the GUI cause there are many plotting tasks are running.

Is it possible to restart the wallet sync via CLI ? 

Does it have any issues to receive Chia from farming / or to get a"BINGO" - if the wallet is not sync ? 

Node is connected and sync'd - Plotting running fine. 

Thanks for your support 

Attix

**Comment by Attix2508** [comment]
...

**Comment by BassProulx** [comment]
Related issue here, though I am using CLI only (I want to keep everything light on memory).

`(venv) user@machine:~/chia-blockchain$ chia wallet show`
`Wallet height: XXXXX`
`Sync status: Not synced`
`Balances, fingerprint: XXXXXXXXXX`
`Wallet ID 1 type STANDARD_WALLET`
`        -Total Balance: 0.0 xch (0 mojo)`
`        -Pending Total Balance: 0.0 xch (0 mojo)`
`        -Spendable: 0.0 xch (0 mojo)`

The important part here is "Sync status: Not synced", I replaced potentially sensitive info with Xs.

I am running chia-blockchain 1.1.6 on Ubuntu 20.04.2 LTS.

Restarting the wallet and reinstalling the whole OS and chia-blockchain software not working. ( not that I thought the OS caused any problem but because I happen to have accidentally deleted my OS disk partition :-P )

Is it just because I have no mojo ? ;-)

**Comment by BassProulx** [comment]
Oups, nevermind. Something--restarting wallet, reinstalling chia blockchain (which probably updated from 1.1.5 to 1.1.6) or reinstalling the whole OS--got the wallet syncing despite the "Sync status: Not synced". I just did not notice the increasing wallet height.

It went from ~3,000 to fully synced at almost 400,000 between last post and now, so within 12 hours.
