### ISSUE TITLE
[REQ] Is opening port 8444 safe ?

### ISSUE THREAD

**Issue by Mikiish** [Chia-Network/chia-blockchain#4165]
Hello !
I would like to know if having port 8444 open at all time is safe. I have very little knowledge in networking, but I do know that port forwarding is usually not recommended for security. With Chia growing, hackers will definitely try to find some way of using the fact that people are opening port 8444 to find some rifts or whatever black magic that could allow theim to enter our network.

Thanks in advance to whoever may answer my concerns !

Edit: For more details : I'd like to know if opening this port without particular knowledge in network or skills in securing home network is recommended.

**Comment by wirespeed43** [comment]
Your computer already opens a bunch of ports. If you are worried about security, maybe a router with a firewall or something similar can help.

**Comment by lpaln** [comment]
> Your computer already opens a bunch of ports. If you are worried about security, maybe a router with a firewall or something similar can help.

This is a terribly ignorant comment. No your computer does not already open a bunch of ports unless you have UPnP enabled on your router. Then it "can" but I still wouldn't say a bunch of ports. I'm a 20 year IT Pro, and I came to this thread with the same question. I am not sure where I can find information about what type of security is included for the listener service on 8444.

I do not use uPnP on my home network because of the myriad of security issue it presents when a malicious .exe can open any ports it wants into my home network.

So the real question here is where is the documentation to indicate the communication protocols used on 8444. is this connection encrypted? does it require authentication? What type of data can be exposed through the listener process? I don't know and I don't know where to look for this level of technical information.

**Comment by cherymann** [comment]
> > Your computer already opens a bunch of ports. If you are worried about security, maybe a router with a firewall or something similar can help.
> 
> This is a terribly ignorant comment. No your computer does not already open a bunch of ports unless you have UPnP enabled on your router. Then it "can" but I still wouldn't say a bunch of ports. I'm a 20 year IT Pro, and I came to this thread with the same question. I am not sure where I can find information about what type of security is included for the listener service on 8444.
> 
> I do not use uPnP on my home network because of the myriad of security issue it presents when a malicious .exe can open any ports it wants into my home network.
> 
> So the real question here is where is the documentation to indicate the communication protocols used on 8444. is this connection encrypted? does it require authentication? What type of data can be exposed through the listener process? I don't know and I don't know where to look for this level of technical information.

Read the code! 20 years in IT, congratulations. You seem to have a handle on IT. Have a good day!

**Comment by lpaln** [comment]
> Read the code! 20 years in IT, congratulations. You seem to have a handle on IT. Have a good day!

Yes everyone in IT is a developer. I should have to read the source of a compiled application to determine whether it implements appropriate security principles for inbound connections.

Keep digging that hole man. You sound less ignorant with every word.

**Comment by GAS85** [comment]
> Read the code! 

WTFM - write the f.. manual!

**Comment by GAS85** [comment]
Please reopen it.
