### ISSUE TITLE
0 plots were eligible for farming 89ee825a2f... Found 0 proofs. Time: 0.00399 s.

### ISSUE THREAD

**Issue by tksalarzai** [Chia-Network/chia-blockchain#4226]
**Describe the issue**
is this normal that i see alot of these lines in my \.chia\mainnet\log 
"0 plots were eligible for farming 89ee825a2f... Found 0 proofs. Time: 0.00399 s."
like i have never seen any number other inplace 0 in my logs 

**Screenshots**
![Screenshot 2021-05-09 014516](https://user-images.githubusercontent.com/77279839/117552984-3e1b5c80-b068-11eb-8d6a-8cf917640e9b.png)

**Additional context**
can anyone else check and update here please

**Comment by eliliam** [comment]
Yes, that 's completely normal. The "0 plots were eligible" part is in reference to the plot filter(~1/512 chance a plot will pass), and the "Found 0 proofs" means that of the drives that passed the plot filter, none of the plots had a proof.  If you wait long enough, you'll see lines like "1 plots were eligible" and if you're lucky maybe even "Found 1 proofs".

**Comment by tksalarzai** [comment]
https://github.com/Chia-Network/chia-blockchain/issues/4347 brother have a look please , i really need someones help.

**Comment by jonny77** [comment]
> Yes, that 's completely normal. The "0 plots were eligible" part is in reference to the plot filter(~1/512 chance a plot will pass), and the "Found 0 proofs" means that of the drives that passed the plot filter, none of the plots had a proof. If you wait long enough, you'll see lines like "1 plots were eligible" and if you're lucky maybe even "Found 1 proofs".
actually i see Found 1 proofs in my log file , but no chia won,

**Comment by shanjoel** [comment]
> #4347 brother have a look please , i really need someones help.



> Yes, that 's completely normal. The "0 plots were eligible" part is in reference to the plot filter(~1/512 chance a plot will pass), and the "Found 0 proofs" means that of the drives that passed the plot filter, none of the plots had a proof. If you wait long enough, you'll see lines like "1 plots were eligible" and if you're lucky maybe even "Found 1 proofs".

I HAVE THE ISSUE ONCE ITS SHOWS 
2021-05-14T02:49:33.094 harvester chia.harvester.harvester: INFO     1 plots were eligible for farming 4d0f027571... Found 0 proofs. Time: 0.02294 s. Total 25 plots
.
.
.
.
2021-05-14T02:50:25.072 harvester chia.harvester.harvester: INFO     1 plots were eligible for farming 4d0f027571... Found 0 proofs. Time: 0.14070 s. Total 25 plots
.
.
.
2021-05-14T02:54:05.909 harvester chia.harvester.harvester: INFO     1 plots were eligible for farming 4d0f027571... Found 0 proofs. Time: 0.02693 s. Total 25 plots

AND THEN FEW SECONDS LATER

2021-05-14T02:54:21.431 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 4d0f027571... Found 0 proofs. Time: 0.00100 s. Total 25 plots


GOT 25 PLOTS OF 2.58 TiB,WAS THIS NORMAL ? because i'm using Hard Disk-WD 8TB x 2 Sata Red 5400-RPM and Hard Disk-Seagate 8TB x 2 NAS Ironwolf 7200-RPM,25 PLOTS ARE IN THE WD RED HDD,both of HDD Brands are NAS INTERNAL HDD IS THAT OKAY ?
