### ISSUE TITLE
[BUG] "chia plots create -x" does not work

### ISSUE THREAD

**Issue by tiny0little** [Chia-Network/chia-blockchain#4255]
in case of "chia plots create -x" final plot still copied to current location

$ chia plots create -h
-x, --exclude_final_dir         Skips adding [final dir] to harvester for farming

do i understand it right, '-x' should keep the plot in the tmp location?

**Comment by jpattishall** [comment]
No, `-x` or `--exclude_final_dir"` just prevents the `Final Directory` (or `-d`) from being added as a farming directory. For example, when you run:

`chia plots create -t /Volumes/Temp -d /Volumes/Final`, the directory `/Volumes/Final` will automatically be added for farming, if it's not already. You can verify this by doing `chia plots show`, which would output `/Volumes/Final`.

If you're the type that prefers to manually move your plots around, you could do something ilke:

`chia plots create -x -t /Volumes/Temp -d /Volumes/Final`, and assuming `/Volumes/Final` is not already farming, Chia will not add the directory for farming. `chia plots show` will not include `/Volumes/Final` in the directory list.

To accomplish keeping the plots in tmp, just specify the `tmp` directory for both `-t` and `-d`.

`chia plots create -x -t /Volumes/Temp -d /Volumes/Temp`

This will create the plots in Temp and rename the `*.plot.2.tmp` to `*.plot` at the end of phase 4 (if you specify any other folder, Chia will perform a copy, rather than a simple move). It also won't automatically start farming at the end (useful, for when you decide to move the plots to their final dest).
