### ISSUE TITLE
[help]Can I manually connect local network synced computer ?

### ISSUE THREAD

**Issue by never-afk** [Chia-Network/chia-blockchain#4286]
I have  50 computers connected to same router.
I have a static public ipv4 address  and set route redirect tcp & udp 8444 to one of those computers.
The one works goods,but others always can not sync to mainnet.
I make other computer  connect to the one which sync successed manually and other computer sync very quick~
After every computer sync successed,i just keep waiting for farm reward.

But I got 0 xch more than 48 hours. 
BTW, I have 1 PB. Is there something wrong with my connect step ?

**Comment by JaNd3eS** [comment]
I was experiencing synchronization issues as well.      
I was running 2 full nodes under the same LAN, one on MacOs, the other on Ubuntu 20.04, both 1.1.4.     
I set up port forwarding to the one with Ubuntu for port 8444.    
The one with Ubuntu, where I plot and farm, was struggling to keep connections with other nodes, while the one with MacOS was running just fine with 20+ connections.       
In order to keep the one with Ubuntu farming, I set up a cron every 5 min that adds a connection to the Full node node on MacOS. 

*/5 * * * * * cd /path-to-my-chia-blochchain-bin && ./chia show -a 192.168.1.123:8444   

Truth to be told, after a few days, the number of connections on my Ubuntu machine grew and now are stable around 50+.
Hope it helps.

**Comment by never-afk** [comment]
thanks,I'm curious whether this local LAN synchronization scheme will affect the winning

**Comment by milan-patartics** [comment]
@JaNd3eS how did you do that? I am trying to do the same.
I tried to connect from node A to node B and vice versa, but it does not work. My firewall allows communication between the two nodes and I can detect the request packages on the router, but the requested node does not accept the connection.

**Comment by never-afk** [comment]
just click connect other peer button. input ip port . done

**Comment by milan-patartics** [comment]
That's what I did. Have no idea why it does not work for me :\

**Comment by JaNd3eS** [comment]
@never-afk it theory it should not affect the winning probability. The only draw back is that you end having multiple full nodes syncing the whole blockchain altogether, requiring double the bandwidth to do so.    

@milan-patartics as far as i know, there are be some limitations on the number of connections that a node can accept. So, make sure this is not the case. Usually, in my experience, on the LAN, connection to other nodes is always istantaneous.

**Comment by milan-patartics** [comment]
Idk, something is wrong with my nodes. The GUI just hangs until it timeouts. With the router I can log packages from the requester to the requested node, but nothing in the opposite direction. Upnp enabled, and yeah I checked the peer count settings, that should not be a problem.

**Comment by JaNd3eS** [comment]
I'm assuming they are on the same subnet. 
I would try the following: 
1. pick a - let's say - master node of the couple: the one whose connection list is best. 
2. disable upnp for it ( ./chia configure -upnp false )
3. set up port 8444 forwarding to it.
4. restart the node
5. try connect to it again. 

However, from what you're saying, it looks more like a firewall problem. As I said, on LAN connections between nodes is almost instantaneous.

**Comment by never-afk** [comment]
what a fucking day with no xch , again!  
I have 1 pb plots, thress days not win any xch!
Is that normal?
