### ISSUE TITLE
[BUG] farming time more than doubled within 5 hours with almost sme network space

### ISSUE THREAD

**Issue by bunkaq** [Chia-Network/chia-blockchain#4310]
Today morning:
Farming status: Farming
Total chia farmed: 0.0
User transaction fees: 0.0
Block rewards: 0.0
Last height farmed: 0
Plot count: 71
Total size of plots: 7.028 TiB
Estimated network space: 3179.436 PiB
Expected time to win: 2 months and 4 weeks    

Now after about 6 hours:
Farming status: Farming
Total chia farmed: 0.0
User transaction fees: 0.0
Block rewards: 0.0
Last height farmed: 0
Plot count: 74
Total size of plots: 7.325 TiB
Estimated network space: 3109.000 PiB
Expected time to win: 6 months and 2 weeks

Why network spce changed down by 60PB but my luck to win is reduced by 3,5 months ?

**Comment by djdookie** [comment]
Same here. What happened?

**Comment by wrosko** [comment]
Probably related to network problem today. This probably isn't a real bug.

**Comment by adamsky-01** [comment]
I just hope it's a bug not a real estimation.

**Comment by bunkaq** [comment]
same after upgrade to 1.1.5 from 1.1.4 ...

**Comment by ozerozay** [comment]
i've no problem chia 1.1.4, always farming.

**Comment by variableresults** [comment]
Same. See output below. Something seems odd because the netspace has actually gone down.

Yesterday evening:
`Farming status: Not synced or not connected to peers
Total chia farmed: 2.0
User transaction fees: 0.0
Block rewards: 2.0
Last height farmed: XXXXXXXX
Plot count: 136
Total size of plots: 13.461 TiB
Estimated network space: 3242.759 PiB
Expected time to win: 1 month and 3 weeks`

Today 12:46pm Central:
`Farming status: Farming
Total chia farmed: 2.0
User transaction fees: 0.0
Block rewards: 2.0
Last height farmed: 241995
Plot count: 142
Total size of plots: 14.055 TiB
Estimated network space: 3013.512 PiB
Expected time to win: 3 months and 3 weeks`

**Comment by variableresults** [comment]
> same after upgrade to 1.1.5 from 1.1.4 ...

I'm not sure the upgrade is related or not, at least for the local chia client. I'm still on 1.1.4 on my TTW doubled as well.

**Comment by PC101guy** [comment]
maybe the original time was being to "generous" with the time to win estimations and now people are getting frustrated because they are not winning.

**Comment by wrosko** [comment]
TTW estimate may be borked due to the network issues earlier today. Give it several hours or more for things to normalize again

**Comment by kevincwebb** [comment]
The TTW estimate is based on the "average block time", see:

https://github.com/Chia-Network/chia-blockchain/blob/59de4ffe9f98de62d281695d1f519d65ef2e2ece/chia/cmds/farm_funcs.py#L247

With the desync issues today that necessitated 1.1.5, the network is currently slower than normal (presumably due to many nodes not yet being updated), and it's affecting the TTW estimate.

**Comment by PC101guy** [comment]
> 
> 
> The TTW estimate is based on the "average block time", see:
> 
> https://github.com/Chia-Network/chia-blockchain/blob/59de4ffe9f98de62d281695d1f519d65ef2e2ece/chia/cmds/farm_funcs.py#L247
> 
> With the desync issues today that necessitated 1.1.5, the network is currently slower than normal (presumably due to many nodes not yet being updated), and it's affecting the TTW estimate.

I wanna update to 1.1.5 but I don't want to interrupt my current plotting process, they need a way to update the gui without interfering with plots already being plotted.
