### ISSUE TITLE
[help] new upgraded pc plots slower than previous pc

### ISSUE THREAD

**Issue by tephen92** [Chia-Network/chia-blockchain#4323]
**Describe the issue**
hello i just bought a second pc these are the specs for second pc..  
motherboard: x570 msi tomahawk
cpu :amd ryzen 9 3900x
ram: 64gb ddr4 3600mhz trident royal cl16
storage: 2X2tb corsair mp 600 + (os)240gb  kingston ssd
graphics card : gt 1030

its plotting extremely slower compared to my first pc and these are my specs..
motherboard: b550i gygabyte aorus
cpu : amd ryzen 7 3700x
ram: 32 gb g skill neo ddr4 3600mhz cl16
storage: (os) samsung evo plus 1tb+ corsair mp600 2 tb
graphics card :amd rx 6700xt 12gb ram

the ryzen 9 3900x takes double the time to plot the same amount of plots if i set them up.
also if i set both pc to plot only 1 at max threads(pc 1,16threads) (pc 2 ,24 threads) and max ram (pc 1, 30gb) (pc 2, 60gb). the pc 1 with less threads and ram plots 2x times faster.. any idea how to fix it would be helpfull

i would expect the ryzen 9 3900x to plot faster but it isint

**Comment by PC101guy** [comment]
I have a 3900x, and I am getting around 5 hours to do a single plot 10 threads 4000 ram plot to nvme and transfer to 4x raid0 sata drives.  However I notice when plotting more then 1  at a time even with all the available resources the plot times go way down by 2-3 hours each even thou you can do 2 plots in that time frame so its actually faster per plot.  I think its IO bottle necked but if your running 2x 2tb mp600 (I got firecuda 520 2tb x2 on the way) then im not very hopeful.  Let me know if you ever figure it out because I am struggling with getting the 3900x to do more then 4 plots at a time even thou its 24 threads.

**Comment by PC101guy** [comment]
ya same checked the clocks stays cool and stead at 4.1ghz, so im pretty sure its not our cpu's.   Something else must be hindering you, you can try it if you want but I got a feeling its something more then that.  are you 2 nvme's in raid 0 or are you plotting evenly to each one 50/50

**Comment by PC101guy** [comment]
also what is you final copying time?  ;from nvme to your final destination, should say in the logs.

**Comment by tephen92** [comment]
yes my nvme are running on gen 4 because it is giving the same transfer rate as my first pc and they are in raid . and i have the x570 chipset so all should be in gen4. 1 thing i also realized is that on my first pc having the os on the evo plus and plotting goes faster than having the on the mp 600.. which is why i am thinking of cloning my ssd and put in one of the mp 600 for rig 2 and see if it goes any faster

**Comment by tephen92** [comment]
the final hours is at about 11 hours for 1 plot on r9 3900x while on the r 7 3700x it finishes 6-7 plots in parallel in 8 hours

**Comment by tephen92** [comment]
[
<img width="1569" alt="r7 3700x" src="https://user-images.githubusercontent.com/83920808/117583355-07e0ea00-b107-11eb-9ccb-6c0707e94a1c.PNG">
](url)

**Comment by PC101guy** [comment]
dang that 3700x killing it! no idea about the 3900x.  you are gonna have to troubleshoot a bit im guess, motherboard driver updates chipset all that stuff, I just don't know what could be doing it.  isn't a 3700x almost the same as a 3900x except we have 4 more cores 8 threads, that must be fustrating thou just built all that and having issues like this.  should not be taking that long not when im getting 5 hours on a crappy 1tb nvme.

**Comment by tephen92** [comment]
your operating system is on you 1tb nvme?

**Comment by tephen92** [comment]
[
<img width="1771" alt="r9 3900x" src="https://user-images.githubusercontent.com/83920808/117583905-0fee5900-b10a-11eb-8334-2e3964beb132.PNG">
](url) that is my 3900x and as you can see it is not utilizing more than 32 gb of ram no matter the amount of ram i put in it

**Comment by PC101guy** [comment]
may be just tooo much IO work for your motherboard/hard drives.   cpu is getting a good work out there also.  When my 2x 2tb nvme's come in ill test it myself also and see what i come up with.  Also I found that if you put too much temp space on an nvme, fill it over say 80% its slows wayyyy down, I guess nvmes to get their best speed don't like to be over 3/4 full.

**Comment by tephen92** [comment]
i dont completely agree with that  it slows over 80 % my samsung evo plus can take only  1 plot because i already have it at 70 % and it still goes faster even when i plot only 1 with it compared to the corsair mp600 
<img width="1707" alt="r7 3700x1" src="https://user-images.githubusercontent.com/83920808/117587081-682e5680-b11c-11eb-9be5-ccd2940dce03.PNG">

**Comment by variableresults** [comment]
It's hard to say where the bottleneck might be without looking at Performance Monitor between the two. Task Manager isn't as helpful since it obfuscates the system metrics you care about. 

The metric I would check is the Disk Queue under the Disk tab; the higher that is consistently, the more your SSDs are bottlenecking from the load. Has nothing to do with CPU in my experience--once you start parallel plotting on a single SSD, you run the risk of disk queueing no matter how fast the drive is (even my MP600 and my Raid 0 of two Inland PCI-E 4 SSDs will disk queue with too many parallel plots). I've noticed that going over 3 parallel plots on the MP600 disk queues in a way that slows the whole thing down. If you see that number constantly high, it means that Windows is waiting for the drive to have a free R/W cycle. So effectively, it's serializing your parallel writes because it can't keep up. This is why it is helpful to use something like Chia Manager to stagger your plots by time so that you don't have too many in Phase 1 trying to write at the same time. 

It's also possible you got some bad SSDs. Not all silicon is created equal.

**Comment by PC101guy** [comment]
Thanks for the info, good to know, right now my disc queue is bouncing between 0 and 10, not sure if thats high or not.  Waiting on my new nvme's is killing me, I should of just drove down the road and grabbed them lol.   In your experience is raiding nvme worth it? I will have 2x 2tb firecuda 520's and 2x 500gb samsung 970 evo already in raid 0.   I ordered some pci-e riser nvme cards too they were 25 bucks each may come in handy down the line.

**Comment by MatveyFV** [comment]
Friend, do not worry about this issue, I have a very similar configuration with the same 3900x processors and 64 GB of RAM, 570 chipset - the maximum is 40 plots per day, do not squeeze any more.

**Comment by tephen92** [comment]
allright so basically it was my m2 ssd that was not well set up i think somewhere along the line they were really slow after downloading the corsair ssd toolbox and doing a complete wipe and updating firmware and updating everything else that might be updated and reinstalled amd drivers ... i tested by mistake with 1 ssd .. by accident i pressed to open 7 plots at the same time and by my luck it finished all plots within 7 hours which is a huge improvement compared to before it took like like double the amount to finish a few plots in staggered so my problem is solved thanks XD

**Comment by brunobozic** [comment]
so how much are you getting now that you have fixed things?

**Comment by MatveyFV** [comment]
corsair ssd toolbox mmmm this app is 2013 release   
![Corsair — Яндекс Браузер](https://user-images.githubusercontent.com/82934186/117985135-1c102b80-b341-11eb-9e49-b6c2283e8b77.png)

**Comment by florian84z** [comment]
> Friend, do not worry about this issue, I have a very similar configuration with the same 3900x processors and 64 GB of RAM, 570 chipset - the maximum is 40 plots per day, do not squeeze any more.

Hi!

i am really impressed with your 40 plotts / day. I'm so free and speak to you directly and want to ask for help.

First my system:
- Ryzen 3700x
- 32GB RAM (another 32Gb are coming soon)
- 2x 1Tb Sabrent Rocket Pcie 4.0 NVME
- a couple of 8TB WD disks

Can you give me tips about the settings? I currently manage a maximum of 10 plots / day. But only very manually, because I just -still- lack the knowledge.

1. I have read - anywhere - that multithreading is only particularly profitable in phase 1. Can you confirm it?
2. My CPU has 8 cores with 16 threads. How many should run in parallel from your experience?
3. How many threads do you assign to the respective plot processes?

What are your current attitudes like? do you plot via the GUI or via the Powershell?

I look forward to hearing from you.

Greetings from Germany

Florian
