### ISSUE TITLE
[BUG] Kernel task on M1 Mac. And issue with plotting.

### ISSUE THREAD

**Issue by nerirififi** [Chia-Network/chia-blockchain#4335]
Someone use a m1 processor for plotting ?

I got really bad stat comparing with another computer on windows.
Time for plot can do X2.
I make test with plot in queue so pretty sure it s the soft.

I use T7 Samsung . Test tomorrow with TB3 .
I also install apple environment for plotting and I have any intel process .

suggestion . If you didn’t release arm version you have kernel task who write a lot on internal hard disk even if you are not plotting on it.

per day it s 15 TB so you will ruin your internal nand hard drive .

Need advice from expert ! because i don t understand why the speed is so slow.
I make many test . 

1 time is 5:05 hours for 1 plots the best i got.
And new one is 24hours worst I got .

plot are done in queue not parallel in the test I do.
And I have 2 M1 Mac with same config.

**Comment by scotopic** [comment]
Might want to share your plotting scripts and stats for each. For example here are mine:
```
screen -d -m -S chia1 bash -c 'pushd ~/Documents/chia-blockchain/ && . ./activate && sleep 0h && chia plots create -k32 -n20 -t/Volumes/chia-temp -2-t/Volumes/chia-temp -d/Volumes/chiaplot1/chia-plot-main -b3400 -u128 -r2 -a########## | tee ~/.chia/logs/chia1_1_.log'

screen -d -m -S chia2 bash -c 'pushd ~/Documents/chia-blockchain/ && . ./activate && sleep 1h && chia plots create -k32 -n20 -t/Volumes/chia-temp -2-t/Volumes/chia-temp -d/Volumes/chiaplot1/chia-plot-main -b3400 -u128 -r2 -a########## | tee ~/.chia/logs/chia2_1_.log'
```
and my max is 6-8 plots per day on the Apple Mac mini m1 8GB + 1 NVMe external drive (temp plotting) + final transfer to a slow NAS ( I might be able to reach 8 if I can get more external SSDs for final plots )

Here are my plotting times:
```
 cat ~/.chia/logs/chia1_1_.log | grep "Total time"; echo --------------------------------------------------; cat ~/.chia/logs/chia2_1_.log | grep "Total time";
Total time = 23579.965 seconds. CPU (80.930%) Mon May 17 00:36:07 2021
Total time = 23552.310 seconds. CPU (81.940%) Mon May 17 07:37:58 2021
Total time = 24917.668 seconds. CPU (80.770%) Mon May 17 15:04:04 2021
Total time = 24230.730 seconds. CPU (79.130%) Mon May 17 22:15:42 2021
Total time = 23362.854 seconds. CPU (79.680%) Tue May 18 05:12:18 2021
--------------------------------------------------
Total time = 23929.587 seconds. CPU (80.830%) Mon May 17 00:39:21 2021
Total time = 23317.828 seconds. CPU (81.910%) Mon May 17 07:37:18 2021
Total time = 24661.660 seconds. CPU (80.830%) Mon May 17 14:59:06 2021
Total time = 24233.372 seconds. CPU (78.700%) Mon May 17 22:10:44 2021
Total time = 23447.403 seconds. CPU (79.740%) Tue May 18 05:08:41 2021
```
This doesn't take into account the many seconds spent sending the final plots to my slow NAS

**Comment by DrunkenKraken** [comment]
> Someone use a m1 processor for plotting ?
> 
> I got really bad stat comparing with another computer on windows.
> Time for plot can do X2.
> I make test with plot in queue so pretty sure it s the soft.
> 
> I use T7 Samsung . Test tomorrow with TB3 .
> I also install apple environment for plotting and I have any intel process .
> 
> suggestion . If you didn’t release arm version you have kernel task who write a lot on internal hard disk even if you are not plotting on it.
> 
> per day it s 15 TB so you will ruin your internal nand hard drive .
> 
> Need advice from expert ! because i don t understand why the speed is so slow.
> I make many test .
> 
> 1 time is 5:05 hours for 1 plots the best i got.
> And new one is 24hours worst I got .
> 
> plot are done in queue not parallel in the test I do.
> And I have 2 M1 Mac with same config.

Hi, I got same problem and could't find any solution for that. System cpu usage goes %40-60 and plotting gets incredible slow down and then crash. It happens chia 1.1.5 and 1.1.6 as well. Could you find anything? I'd be very happy to hear about it.

**Comment by scotopic** [comment]
@DrunkenKraken : Can you provide your hardware pieces ( which mini M1, external drives and which scripts you run ) ?

I got 4 mac minis M1 running step by step info here: https://github.com/scotopic/chia-guide

**Comment by DrunkenKraken** [comment]
> @DrunkenKraken : Can you provide your hardware pieces ( which mini M1, external drives and which scripts you run ) ?
> 
> I got 4 mac minis M1 running step by step info here: https://github.com/scotopic/chia-guide

I have M1 macbook air with 16GB Ram. I use external ssd Sandisk Extreme Pro 2TB 2000 mbps read/write on thunderbolt. I'm using SWAR and in scripts I played with numbers a lot but couldn't fix this problem. Right now I'm using like this;

- name: ssdplot
    max_plots: 999
    farmer_public_key:
    pool_public_key:
    temporary_directory: /Volumes/Extreme Pro/TempPlots0
    temporary2_directory:
    destination_directory: /Volumes/Seagate0
    size: 32
    bitfield: true
    threads: 4
    buckets: 128
    memory_buffer: 4000
    max_concurrent: 4
    max_concurrent_with_start_early: 4
    stagger_minutes: 120
    max_for_phase_1: 2
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 5
    temporary2_destination_sync: false
    
    What happens is first two plots working perfectly and then when third one starts something happen and kernel_task gets all cpu on itself and make the chia processes so slow. In 1.1.6 version it cause crashes, in 1.1.5 it doesnt, just slow down. I finish just one plot in 22 hours right now. I will check your guide rn.

**Comment by scotopic** [comment]
A couple of things to consider
1. RAM: You are using more than you have. Consider lowering memory_buffer and/or max_concurrent. You have 16GB total meaning you can only use 14-15GB total since macOS needs at least 1GB to operate and avoid swapping memory to your internal disk ( this will drastically slow things down )
2. I believe the MacBook Air has 7 cores ( the term thread isn't used in M1 CPU and AFAIK you technically only have 1=1 core to thread on M1 chips vs Intel/x86 chips have HyperThreading and can do  2 threads per core )
    * That script says use 4 threads/cores x 4plotters =16 cores/threads which might actually make the whole thing slow down.

Here's what I've seen in my own experience on Mac mini M1 with external USB-C MVNe (temp plot) and USB-C HDD (final plot)
1. 1 plot = 7000MB, 6 threads -> 4hr plots ( total about 6 plots/day )
1. 2 plots concurrent = 3400MB, 4 threads -> 6-7hr plots ( total about 6-8 plots/day )

I'd say you need at most you want something like this:
```
name: ssdplot
max_plots: 999
farmer_public_key:
pool_public_key:
temporary_directory: /Volumes/Extreme Pro/TempPlots0
temporary2_directory:
destination_directory: /Volumes/Seagate0
size: 32
bitfield: true
threads: 2
buckets: 128
memory_buffer: 3400
max_concurrent: 4
max_concurrent_with_start_early: 4
stagger_minutes: 120
max_for_phase_1: 2
concurrency_start_early_phase: 4
concurrency_start_early_phase_delay: 5
temporary2_destination_sync: false
```

Or just try to run them manually first to see if you can even get the individual plots to a decent speed such as 
```
screen -d -m -S chia1 bash -c 'pushd ~/Documents/chia-blockchain/ && . ./activate && sleep 0 && chia plots create -k32 -n1 -t/Volumes/chia-temp -2-t/Volumes/chia-temp -d/Volumes/chiaplot-ext-1 -b7000 -u128 -r6 -a########## | tee ~/.chia/logs/chia1_1_.log'
```
and
```screen -x chia1```

**Comment by DrunkenKraken** [comment]
> A couple of things to consider
> 
> 1. RAM: You are using more than you have. Consider lowering memory_buffer and/or max_concurrent. You have 16GB total meaning you can only use 14-15GB total since macOS needs at least 1GB to operate and avoid swapping memory to your internal disk ( this will drastically slow things down )
> 2. I believe the MacBook Air has 7 cores ( the term thread isn't used in M1 CPU and AFAIK you technically only have 1=1 core to thread on M1 chips vs Intel/x86 chips have HyperThreading and can do  2 threads per core )
>    
>    * That script says use 4 threads/cores x 4plotters =16 cores/threads which might actually make the whole thing slow down.
> 
> Here's what I've seen in my own experience on Mac mini M1 with external USB-C MVNe (temp plot) and USB-C HDD (final plot)
> 
> 1. 1 plot = 7000MB, 6 threads -> 4hr plots ( total about 6 plots/day )
> 2. 2 plots concurrent = 3400MB, 4 threads -> 6-7hr plots ( total about 6-8 plots/day )
> 
> I'd say you need at most you want something like this:
> 
> ```
> name: ssdplot
> max_plots: 999
> farmer_public_key:
> pool_public_key:
> temporary_directory: /Volumes/Extreme Pro/TempPlots0
> temporary2_directory:
> destination_directory: /Volumes/Seagate0
> size: 32
> bitfield: true
> threads: 2
> buckets: 128
> memory_buffer: 3400
> max_concurrent: 4
> max_concurrent_with_start_early: 4
> stagger_minutes: 120
> max_for_phase_1: 2
> concurrency_start_early_phase: 4
> concurrency_start_early_phase_delay: 5
> temporary2_destination_sync: false
> ```
> 
> Or just try to run them manually first to see if you can even get the individual plots to a decent speed such as
> 
> ```
> screen -d -m -S chia1 bash -c 'pushd ~/Documents/chia-blockchain/ && . ./activate && sleep 0 && chia plots create -k32 -n1 -t/Volumes/chia-temp -2-t/Volumes/chia-temp -d/Volumes/chiaplot-ext-1 -b7000 -u128 -r6 -a########## | tee ~/.chia/logs/chia1_1_.log'
> ```
> 
> and
> `screen -x chia1`

Thanks for your effort. I appreciate. Macbook Air has 8 core CPU and 7 core GPU so for CPU 8 cores = 8 threads. I've tried parallel 4 plots 2 threads, also 4 threads and nothing changed. I guess it takes whatever it needs as threads but I've never tried ram less than 3900. Now I will try that and if I fail, will turn to one by one plotting. Another thing is I don't understand people who makes 16-20 plots in a day with M1 mini. They are talking about running chia as native apple arch. I'm not expert but my laptop is plotting so slow maybe because on activity monitor I see the chia process running Intel Arch?

**Comment by scotopic** [comment]
> Thanks for your effort. I appreciate. Macbook Air has 8 core CPU and 7 core GPU so for CPU 8 cores = 8 threads. I've tried parallel 4 plots 2 threads, also 4 threads and nothing changed. I guess it takes whatever it needs as threads but I've never tried ram less than 3900. Now I will try that and if I fail, will turn to one by one plotting. 

Right you can only use around 15GB of your RAM so I'd say 3500 per plotter is likely a better setting. Though you are likely still limited by your enclosure if it's USB-C (10 Gbps)  and not Thunderbolt 3 ( 40 Gbps ).

> Another thing is I don't understand people who makes 16-20 plots in a day with M1 mini. They are talking about running chia as native apple arch. I'm not expert but my laptop is plotting so slow maybe because on activity monitor I see the chia process running Intel Arch?

If you built form git then you are running native. You can check in Activity Monitor. It'll say "Apple" instead of "Intel"

Yes, you can plot 16-18 on a Mac mini M1 but you have to remove every limitation of the hardware. Here's the hardware you need: It's all documented on https://github.com/scotopic/chia-guide#phase-3---36-plotsday
       1. Mac mini M1 16GB RAM
       1. 2x Thunderbolt 3 enclosure for NVMe M.2 SSD
       1. 2x NVMe M.2 SSD
       1. 2x USB-C enclosure for NVMe M.2 SSD ( or at least SSD )
       1. 2x NVMe M.2 SSD

You plug your TB3 drives into the TB4 ports for temp plotting. Plug in your USB-C drives into the other 2 USB-C ports for final plots. That's how you get to around 16-18 plots/day.
