### ISSUE TITLE
[BUG] 1.1.5 Wallet Sync Incredibly Slow

### ISSUE THREAD

**Issue by variableresults** [Chia-Network/chia-blockchain#4348]
**Describe the bug**
I had to rebuild my wallet DB as a pending transaction was stuck and not listed on the blockchain explorer and wasn't updating. Deleted the .sqlite files out of the DB directory. Wallet is connected and syncing, but is incredibly slow (only at ~19800 after a couple hours). 

Full node is synced and shows many peer connections. 

**To Reproduce**
See above

**Expected behavior**
My backup of the DB folder shows the wallet size at around 1.54GB. This should be able to download very quickly on most high speed internet connections, but for some reason is taking far too long. This locks me out of being able to use my XCH. 

**Screenshots**

**Desktop (please complete the following information):**

- OS: Win10
- OS Version/Flavor: Fully updated
- CPU: Ryzen 9 3900x

**Comment by Plopsi** [comment]
I experienced the same, the first 50-100k blocks are incredibly slow, then it goes quiet fast. Mostly because there seems to be a node which pushes out blocks to syncers like there is no tomorrow.

But I connected the node to sync with other synced nodes in my LAN, but seems chia preferes external connections? Because it barley downloaded from the local nodes. - 15-30MBit at most, then droppes connections.

**Comment by variableresults** [comment]
> I experienced the same, the first 50-100k blocks are incredibly slow, then it goes quiet fast. Mostly because there seems to be a node which pushes out blocks to syncers like there is no tomorrow.
> 
> But I connected the node to sync with other synced nodes in my LAN, but seems chia preferes external connections? Because it barley downloaded from the local nodes. - 15-30MBit at most, then droppes connections.

Weird. I guess I would expect it to be faster regardless--it is after all founded by the guy who invented Bittorrent.

**Comment by voycey** [comment]
Mine has just completely stalled - I am basically getting 1 block every few minutes - there has to be a faster way?

**Comment by gregoriob** [comment]
ditto, when syncing completes,, there is always more to sync. 3 days later when it gets there, MORE to sync. its as if the network cannot sync its transactions as fast as the transactions are being completed. Port 84444 open on PC firewall & router yet I cannot farm a single plot. Chia team, please fix this.

**Comment by spacewaffles309** [comment]
Happening here as well.  Like the OP, I had to rebuild due to moving files around and the resync is awful.  1.1.5, Win10, port 8444 is open and forwarded properly.  The GUI shows synced for the full node, but my wallet sync is like a slowly leaking faucet.  It's been a week and it still hasn't caught up to current height.

I understand that the team is busy and there are a lot of things that need work, but I'd think this would be a higher priority with transactions now being live.  If my bank told me "hey you've had 10 or 12 deposits and withdrawals this week but you can't see them, we'll get all caught up eventually, just let us reboot things a few times" I'd be.... uh.... "unhappy."

**Comment by gregoriob** [comment]
Had a play around with a 3rd party firewall (Zone alarm)last night and after a reboot it's looking good, peers are connecting with better data rates and looks to have held sync well so far today.

**Comment by socketpair** [comment]
The same issue.

**Comment by jaqif** [comment]
Same here, always 200 or 300 aways from the higher block aand can not have the sync status... Have a lot of plot waiting for farming... please help

**Comment by DanielBeban** [comment]
Same issue, been syncing my wallet for a week straight now, currently on ~147,000. Full node status is fully synced, which took about 2 days. If a regular person like me cant sync their wallet fast enough to keep up with the network, then how can this blockchain even function for the masses it is designed for?

**Comment by cristi71000** [comment]
Node full synced, farming for 2 days, but wallet is syncing really slow (up to height 280826 after two days)

**Comment by grayfallstown** [comment]
Wallet made it from 310,000 to 313,236 in about 3 days.. Node fully synched, currently running 1.1.6, 36.9 MB up to the wallet, plenty of connections.

**Comment by appsheld** [comment]
Same issue on WSL..., Win 10 is faster.

**Comment by ktully** [comment]
Wallet also syncing incredibly slowly for me on 1.2.0.  

node is fully synced (with port open in firewall and about 50 peer connections) and I am farming, but wallet has not caught up with network.

Is wallet syncing not "just" a local walk of the already synced blockchain?

When I upgraded, it wouldn't connect to wallet (possibly due to an issue shutting down cleanly before upgrade), so I exited the app, deleted the db, and restarted.

**Comment by kreaninw** [comment]
> Wallet also syncing incredibly slowly for me on 1.2.0.
> 
> node is fully synced (with port open in firewall and about 50 peer connections) and I am farming, but wallet has not caught up with network.
> 
> Is wallet syncing not "just" a local walk of the already synced blockchain?
> 
> When I upgraded, it wouldn't connect to wallet (possibly due to an issue shutting down cleanly before upgrade), so I exited the app, deleted the db, and restarted.

Me too. It's extremely slow. At this rate, it will never catch up with the full node.

**Comment by ktully** [comment]
It did eventually catch up for me after about a day. However, had a hard crash today (suspect a thermal issue due to Mad Max plotter stressing a few components) and on restart wallet was corrupted.

So ... deleted wallet db, upgraded to  1.2.2, and after a few minutes, wallet db is still showing "not synced (0)". Fingers crossed it will catch up overnight, but it's a bit disconcerting. And this time I'll remember to backup a snapshot of the wallet db once it's synced!
