### ISSUE TITLE
[BUG] launchd on Mac 

### ISSUE THREAD

**Issue by chris92q** [Chia-Network/chia-blockchain#4396]
Hi there,

I'm having issues with the GUI since 1.1.4.
The issue still persists in 1.1.5

For some reason after launching the GUI it causes the root process launchd to use 99% CPU. 

It's and issue because it causes my looking qualities to be above 5sec every once in a while as my Mac is having a hard time working on some deamons... 

Am I doing something wrong?

Cheers

**Comment by chris92q** [comment]
After complete reinstall I'm still having this issue... Shortly after starting the GUI launchd climbs all the way up to the top of all tasks and uses CPU like hell...

**Comment by Mogera** [comment]
I'm seeing similar behaviour on Mac Mini (Late 2014) running Big Sur 11.3.1 (20E241).
OS is fine after reboot, once wallet is selected and full GUI opens `launchd` consumers a lot of resources.
I am using the Mac over 'Remote desktop / Mac Screen Sharing'.

As there is not much horsepower on these devices the load is significant and noticeable.

- I'm not 100% sure this is related to Chia client but it seems likely. Current behaviour is that after a reboot the system is fine but after launching full GUI `launchd` takes 100% cpu (on single thread it seems).

- I have no idea how to debug but, I checked system.log but nothing out of the ordinary is popping out.

**Comment by chris92q** [comment]
Very interesting! 
I had previous versions installed and thought that maybe some process of the previous versions was triggered.
So I created a complete new user on my Mac,  freshly installed chia and his solved the launchd problem. 
However, Chia itself has two processes running (each about 50%CPU) and this still causes my drives to be a bit slow in response as the machine is struggling with only ~30 TiB

**Comment by smiletracer** [comment]
+1 here on a late 2013 MacBook Pro with Big Sur 11.3.1. Using v1.1.5 GUI for farming only. The issue starts off with launchd behaving for a short while, then starts cycling between 0% and ~20% every ~15 seconds. Then in an hour or so, it increases to a cycle of 10% to ~60%. Within a couple hours, it's pegged at 99-100%.

Note once launchd is in this state, quitting Chia won't help. It stays at 100%. I also see four "start_full_node" processes that run constantly, one of which spikes to 100% frequently. I've tried typical maintenance stuff, removing all launch daemons and agents, and reinstalling the OS over itself to no avail. Will try creating a new user account next.

**Comment by Mogera** [comment]
To add on my case above, I tried creating a fresh user, copied over Chia directory to prevent having to do a full sync.
Even on new user I'm seeing the exact same behaviour as @smiletracer describes.

launchd at just under 100% and start_full_node also hovering at just below 100% utilisation.

**Comment by smiletracer** [comment]
I just tried deleting the wallet DB folder (not main DB) and the "peer_table_node" file in the main DB folder, and rebooted. Same result. But have a correction on the timings for launchd to reach 100%. It only takes about 10 minutes to reach the 0% to 60% every 10-15 second cycle behavior. By 15-20 minutes it's already reached the 0% to 100% cycle. Still takes a bit longer to be pegged at 100%.

Here's an interesting observation! After it reached the 0 to 100% cycle, but before it gets pegged, I quit Chia. All the chia related processes shutdown as expected, however launchd remains in the 0 to 100% cycle loop (every 10-15 seconds).. almost like it is still doing some task every 10-15 seconds even while Chia is quit. Hmmm..

**Comment by smiletracer** [comment]
OK getting closer to solving the mystery! I currently have 4 external HDDs mounted for Chia. Two were formatted APFS as I started out thinking I'm going 100% Mac. Later I decided to keep my options open in case I need to move to another system to harvest and formatted the two newer drives as ExFat. The launchd process stopped cycling right after ejecting the all drives! System is now 98% idle. Going to try another test unmounting one at a time to see if it is a particular drive format, or if its just the fact all the drives in general were in heavy use. But my gut says ExFat has something to do with it...

**Comment by Mogera** [comment]
My external drives are Exfat as well, good find. Picking Exfat is a bad dream, had one unclean shutdown and now the drives only mount in RO mode and MacOS tells me to format the drives. Exfat fsck is bugged and cant repair the drives. 

Moving 28TB of plots around is shitty assuming I would have the temp space :-|

**Comment by smiletracer** [comment]
Yep, just confirmed 100% it is ExFat! I launched Chia and only mounted my APFS drives. Launchd stayed under 0.5% for a good 10-15 minute test. Then mounted one ExFat volume and within 5 minutes launchd was hitting 100%. Ejected it, and back to 0%. Now gotta start copying plots over to a temp drive and reformat these two ExFat volumes... At least we now know the culprit!

**Comment by Mogera** [comment]
Specifically picked ExFat for cross platform portability in case I would need it. Back to square one...

**Comment by chris92q** [comment]
It's amazing that this has been traced back to Exfat! In the meantime I switched to a more powerful Mac that can handle this launchd process... I have around 35Tib and no space to shift plots. 

Is this something that can be fixed and targeted easily in 1.1.6?

**Comment by smiletracer** [comment]
Well, not exactly sure Chia is off the hook -- I have my two ExFat volumes mounted now but removed Chia from accessing them as Plot directories. I've been copying files from one ExFat drive to another to start the migration process to reformat and copy back. During this, launchd is behaving fine. So something Chia does with these ExFat drives is causing issues. Normal copy operations, or simply having them mounted is not the culprit -- But after Chia does what it does accessing these drives for harvesting plots causes the Launchd issue. Ejecting the ExFat volumes stops the issue, and remounting then while Chia is using them as Plot directories resumes the issue. So I've removed them as directories and copying files over. I'm testing to see if launchd pegged at 100% slows the copy operation. If not, I'll add them back at plot directories so I can at least harvest the plots while the copy finishes.

So Apple likely never knew this was an issue with ExFat... Seems only Chia triggers it. Of course, I could just decide to switch to Windows to harvest these ExFat volumes... but... no.

**Comment by Mogera** [comment]
I'm just sad I picked ExFat as a solution for a problem that in theory could occur (transfer drive and files cross platform).

ExFat filesystem repair tooling support in OSX is poor at best.

Quote from random StackOverflow post:
"There's no backup of the file allocation table like FAT32 has; with the lack of journaling, one unsafe removal, or system freeze, during a write operation is going to hose the entire drive"

I could argue to avoid ExFt like the plague because it is likely to cause misery down the line one way or the other.
Using a cross platform compatible filesystem has significant trade-offs apparently which I underestimated.

Picking the OpenSource NTFS implementation seems like more successful approach but judging from just the combined concepts of 'open-source', 'mac', 'ntfs' and 'fuse'.... not so sure...

Perhaps best to stick to a native, journaled, apple filesystem.

**Comment by AndyRPH** [comment]
Related to https://github.com/Chia-Network/chia-blockchain/issues/7359 
Perhaps we need to get one of the devs to weigh in if it's Apple's implementation of exFat, or something Chia is doing with it.

**Comment by smiletracer** [comment]
I suspect it is something in Apple's implementation, as technically nothing an app can do when accessing its own files should cause the system to get slower over time -- Especially when the exact same Chia code doesn't have any issues when using the native APFS or HFS+ file systems. But that's not to say Chia devs can't pin down the cause and possibly workaround it somehow.

For example, if the issue is frequently opening and closing files over time, an effort to optimize that by keep files open longer might mitigate issues (or the inverse--Maybe files aren't closing properly and references build up), or possibly switch to a different file system API, as the issue may be an issue in a Python library or system call.

In fact, this makes me wonder if it is an issue running with older Python versions on macOS. The default Python is 2.7.x on macOS, and Chia requires 3.7 or higher. There was an issue recently with Chia 1.2.0 where pooling would not communicate with a pool server due to improper SSL certs due to it running on the default 2.7 Python build, even if the latest 3.9 Python was installed (as "python3"). The fix was to manually system the system default "python" simlink to link to Python 3 and Chia was then happy to connect to pools--Note this is not an issue now that Chia 1.2.2 is out as it fixed #7273.

Anyway, I have not texted exFAT since making sure Python 3.9 was the system default -- Maybe, just maybe, it fixes this issue as well. I'm about to test NTFS, as I've been plotting on an Ubuntu system, and picked NTFS as the drive format for the destination, and planning to move them to the Mac for farming (NTFS is read-only on Mac by default, but that doesn't matter for farming of course.) Haven't finished filling the first drive, so will see if it too has the same issue as exFAT, and if so, I'll either switch to farming on the Ubuntu system or copy them to an APFS drive.
