### ISSUE TITLE
[BUG] SYNC constantly SYNC/UNSYNC

### ISSUE THREAD

**Issue by Nachjoe** [Chia-Network/chia-blockchain#4502]
I know this is a very old issue, and has been posted repeatedly, but I haven't really found an answer yet. I'm using 1.1.4, and throughout the day it Sync and No Sync about 10 times a day.

I have very stable internet service, and there's nothing wrong with my system; I'm running a clean system with no unnecessary apps or software installed, other than the essentials to start plotting and farming.

Please help.

**Desktop (please complete the following information):**

- OS: Win 10 Pro
- OS 20H
- CPU: i5 8th Gen

**Additional context**

**Comment by OdinSun35** [comment]
OSError: [Errno 10048] error while attempting to bind on address ('0.0.0.0', 8444)

**Comment by OdinSun35** [comment]
![image](https://user-images.githubusercontent.com/83725290/117737573-cd5c7780-b202-11eb-89a8-11a3fb8e91af.png)

**Comment by OdinSun35** [comment]
HEEEELP
!!!!

**Comment by gameski** [comment]
I have this issue when using same computer for plotting and farm. It can't keep Synced for long time.
I setup another one (RPi4) just for Farm and it can keep Synced.

**Comment by philipyaya2005** [comment]
this happens when my machine restarted (expected) without closing Chia blockchain gracefully, result in corrupted data. The previous error I can see is 

2021-05-11T20:45:08.563 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id xxxxxx, status 3 error: Err.COIN_AMOUNT_NEGATIVE
2021-05-11T20:45:26.326 full_node chia.full_node.full_node: ERROR    Consensus error 124, not disconnecting

If you delete your ~/.chia, uninstall and reinstall chia. It seems fix the issue, however you lost the full nodes and require resync before start farming.
