### ISSUE TITLE
[BUG] Problem wiht sync, close the app and lost all the plotting in parallel or queue

### ISSUE THREAD

**Issue by TranceDevCode** [Chia-Network/chia-blockchain#4619]
**Bug description problem**
Hello CHIA Team, i have this problem in my desktop computer and laptop too, when i start with CHIA i lost maybe 3 o 5 plot fot this problem, the app start re-sync while i was plotting, a few days ago i install the app in my other computer and the same proble, start to sync again while i plotting and lost 3 plots again, that mean, that means around 6 hours wasted and ssd with less time to live, time wasted. please fix this problem, with another friends in a telegram group we present the same problem...

now i want to talk about aby suggestions:

1.- Fix the problem with sync
2.- Please make a solution for pause a plotting if we need give priority to another plotting that is in parallel.
3.- please add a confirm button if we close the app by mistake, this, because we will lost all the plotting in queue or parallel... we need a solution for this problems, because we lost a long long time plotting and live time for a SSD.

Thank you!

**Desktop information:**

- OS: [Windows 10 64 bits]
- OS Version/Flavor: [Windows 10 Pro]
- CPU: [Ryzen 5 3600X]

**Comment by muratyildiz02** [comment]
I've been trying to sync for the last 8 hours but ı can't

**Comment by s12321** [comment]
Queued or unfinished plot will be lost for sure at version 1.1.4/1.1.5 , also, it wont resume plotting due to reopen/rerun the app.  
Completed/finished plots will be lost in the farming, due to app or OS is crashed and reopen the app. (cost me about a week's time and space)

i'm now backing up all the completed plots in farming, but not sure if this help, because i saw other thread said there is a chance the app wont recognised the plots at this point.
