### ISSUE TITLE
Plotting got stuck at 6% - Urgent !

### ISSUE THREAD

**Issue by yourtechcare** [Chia-Network/chia-blockchain#4633]
Processor : 6 cores (AMD Ryzen 5 3600) with 12 threads
RAM : 20GB
NVME : 1TB Samsung 980
HDD : 24TB - 4TB Each (6)
OS : Ubuntu 21

Whats wrong with the system?

**Comment by yourtechcare** [comment]
More than 12 hours machine was active not it didn't moved ahead.....WHY?

**Comment by fredericoschardong** [comment]
Same here. I am running on ubuntu on RPi4 and an external HD.

**Comment by paulpaul9740** [comment]
+1

**Comment by ivanmgeorgiev** [comment]
same to me.. I  have no solution yet

**Comment by zaileion** [comment]
Same problem here.  2 plots on 2 separate computers.  The 1 computer caught up to the other because it was stuck at 6%, now both are stuck at 6% and have been for like 10 hours and the other for like 12 or 15 hours. 

Computing table 3 bucket 0 is where mine get stuck.

This is the 3rd or 4th time I've tried to create plots and always get stuck at 6%.  I always thought it was my computer or something but now that its on 2 different computers i would have to suggest something to do with the software.

Anyone find a solution?

**Comment by fredericoschardong** [comment]
I don't have any solution yet. Today is the eighth day I am stuck on 6%. I have done a `git pull` and restarted my plot. Will post here if I get pass the 6% or not.

**Comment by zaileion** [comment]
> I don't have any solution yet. Today is the eighth day I am stuck on 6%. I have done a `git pull` and restarted my plot. Will post here if I get pass the 6% or not.

Thanks man.  I appreciate it very much!  Are you running on an ESXi server with Windows 10 and a RAID 5 drive by chance?  I am and was thinking it might be the issue... maybe its the RAID or something?  or the virtually allocated resources...

**Comment by fredericoschardong** [comment]
> > I don't have any solution yet. Today is the eighth day I am stuck on 6%. I have done a `git pull` and restarted my plot. Will post here if I get pass the 6% or not.
> 
> Thanks man. I appreciate it very much! Are you running on an ESXi server with Windows 10 and a RAID 5 drive by chance? I am and was thinking it might be the issue... maybe its the RAID or something? or the virtually allocated resources...

No, I am quite far from that. I am running on a raspbery pie 4 with 4 gb of RAM and on a old 500 GB sata drive through USB.

**Comment by yourtechcare** [comment]
Try to increase swap memory and temp folder must be cleaned before creating new plots that's what I learnt !

Better RAM is always a good option those are using less RAM like 4GB

**Comment by zaileion** [comment]
> Try to increase swap memory and temp folder must be cleaned before creating new plots that's what I learnt !
> 
> Better RAM is always a good option those are using less RAM like 4GB

How do i increase swap memory?  Are you talking about Linux swap partition?  I'm running in Windows but am a Linux guy so i dont know how to increase swap area in Windows.  

Also do you mean chia temp folder?  I deleted all content before making my new plots, or are you talking about the Windows temp folders?  if so which ones?

**Comment by yourtechcare** [comment]
In Windows increase virtual memory.

**Comment by zaileion** [comment]
> In Windows increase virtual memory.

What did you change your virtual memory to that got you through the 6%?

**Comment by yourtechcare** [comment]
Yes, restart your computer after Virtual Memory increase and replotting require.

**Comment by zaileion** [comment]
SO i did what you said and edited the virtual memory to 50000 (double the size), because i have 10 tb storage i did the k35 but further investigation i realized that i don't think 12GB of physical memory is sufficient for such a large plot so i did the minimum plot size which is now working and at 8%.  

I will add more physical memory to the 2nd VM and see if I can manage to get a K34 working and passing the 6% mark.

**Comment by zaileion** [comment]
yeah, so it was the larger plot size that was the issue.  I was trying to do a K35 plot.  Once i reduced it to a K32 it worked no pro.  I am currently plotting 10 - K32 plots and at 18%.  So i dunno if you guys were making larger plots (K34 or K35) or not but if so make multiple K32 plots instead.
