### ISSUE TITLE
[BUG] After update to 1.1.5 (WIN), Plotting slowed down to a crawl.

### ISSUE THREAD

**Issue by ONEK1LO** [Chia-Network/chia-blockchain#4740]
After 1.1.5 update for windows GUI wallet, Plotting became extremely slow. After 8 hours of farming on my PCIe NVMe SSD, I'm at 62%, 32%, and 31% (Plotted in parallel with 1 hour delay between each plot). On two SATA SSDs, 39% and 43% after 8 hours. I don't know if this was caused by the wallet update or something else, but it was not like this yesterday before I updated. Plotting on a gaming machine with Threadripper 2920x and 32GB of RAM. I'm not reaching my RAM and CPU full capacity, using default settings for RAM and CPU Threads.

**Comment by Jared-woodruff** [comment]
Hi OneK1lo, 

Usually this happens for 3 reasons: 
1. The drives dont support Self-Trim.
2. The drives are near end of life.
3. You don't have the latest windows update: KB5003173 which fixes the performance regressions in windows 10 introduced by last months windows update KB5001391.

As a rule of thumb, all my servers stop plotting every 24 hours and execute a maintenance PowerShell script to optimize and repair OS issues caused by high constant IO operations, just posting here if it helps.
`#Maintenance Workflow for Chia Server. 
#Version: 1.4 
#-------------------------------------

# Clean Up Cache Store so we have blocks to delete/Trim. have one for each cache directory you have.
Get-ChildItem -Path T:\Chia\Cache -Include *.* -File -Recurse | foreach { $_.Delete()}

# Optimise Cache & OS, make sure there is a line for all your SSD drives, note the Drive Letter!
Optimize-Volume -DriveLetter T -ReTrim -Verbose
Optimize-Volume -DriveLetter C -ReTrim -Verbose

# System Repair, Detect if the OS has any issues- fix up the basic ones.
sfc /scannow

# Deep System Repair, Detect if the OS has any serious issues and fix the advanced ones.
DISM /Online /Cleanup-Image /RestoreHealth

# Restart Windows to complete the maintenance process.
Shutdown -r -t 5 -f`

**Comment by zeafynx** [comment]
I think you encountered a bug: #4118

**Comment by nzkozar** [comment]
I too am experiencing a major plotting slowdown after update 1.1.5

I'm plotting on Ubuntu 20.04 with cli commands, one plot at a time.

Same plotting params now take 30% to 50% longer than before. (Constant 13.5 hours per plot before, 17-19 hours now after update).

**Comment by ONEK1LO** [comment]
> Hi OneK1lo,
> 
> Usually this happens for 3 reasons:
> 
> 1. The drives dont support Self-Trim.
> 2. The drives are near end of life.
> 3. You don't have the latest windows update: KB5003173 which fixes the performance regressions in windows 10 introduced by last months windows update KB5001391.
> 
> As a rule of thumb, all my servers stop plotting every 24 hours and execute a maintenance PowerShell script to optimize and repair OS issues caused by high constant IO operations, just posting here if it helps.
> 
> **#------------------------------------- #Maintenance Workflow for Chia Server. #Version: 1.4 #-------------------------------------**
> 
> **# Clean Up Cache Store so we have blocks to delete/Trim. have one for each cache directory you have.**
> Get-ChildItem -Path T:\Chia\Cache -Include _._ -File -Recurse | foreach { $_.Delete()}
> 
> **# Optimise Cache & OS, make sure there is a line for all your SSD drives, note the Drive Letter!**
> Optimize-Volume -DriveLetter T -ReTrim -Verbose
> Optimize-Volume -DriveLetter C -ReTrim -Verbose
> 
> **# System Repair, Detect if the OS has any issues- fix up the basic ones.**
> sfc /scannow
> 
> **# Deep System Repair, Detect if the OS has any serious issues and fix the advanced ones.**
> DISM /Online /Cleanup-Image /RestoreHealth
> 
> **# Restart Windows to complete the maintenance process.**
> Shutdown -r -t 5 -f

Hi. Thank you for your response. Drives are new (barely plotted 3tb across 5 drives (2 NVMe and 3 SSDs). Drives got decent TBW and adequate cooling. Drives also trimmed and windows updated. It started after the update. I got second machine running
