### ISSUE TITLE
Log files need auto cleanup

### ISSUE THREAD

**Issue by ByronAP** [Chia-Network/chia-blockchain#4864]
Plotting leaves a slew of logs which should be removed on a regular basis (delete plot logs older than N hours) and it seems that the other logs should have a size limit option (purge entries to keep size < limit or max N days).

**Comment by baizuchong-net** [comment]
赞成

**Comment by sargonas** [comment]
By default, one log file is created for each plot, with detailed logging for the process. This is done for a variety of reasons, but most ideally because it allows for the multitude of community plotting tools out there to interact with the current plot state.

For a large number of people, they like to keep these files around to run calculations on efficiency for their plotting methods. That being said, you do bring up a good point that for people who have no interest in doing this, it does create a slew of logs they have to clean up manually and regularly. Not the end of the world but the ability to do so would be a nice quality of life feature.

There is an existing request issue #3238 that discusses adding a less verbose option to plot logging, so perhaps there is a conversation to be had about potentially adding automatic cleanup/rotation as well to that idea.

**Comment by as1543100166** [comment]
Where can I find the plotting log，I can't even find this

**Comment by sargonas** [comment]
I've always used a custom location, so I am a bit rusty on what the default is for sure but I'm fairly certain it is in ~/.chia/mainnet/plotter/ on Ubuntu and C:\users\USERNAME\.chia\mainnet\plotter\ on Windows.
