### ISSUE TITLE
[REQ] GUI should automatically run weekly checks on plots

### ISSUE THREAD

**Issue by acoleman-apc** [Chia-Network/chia-blockchain#5013]
So when copying plots around you can get errors and the plots are bad.  But the GUI never checks for this so bad data eats up good space.   Apparently you can run a check from the daemon in the CLI to get this info.

Why not run it automatically in the background and show the bad plots in red in the GUI?

**Comment by Wang1558-dragon** [comment]
log will show them

**Comment by centrd** [comment]
This can cause issues for people running a large number of drives via USB, or who are otherwise struggling with congestion. I agree that that exposing options for verifying plots is important to have in the GUI, but I do not think it should be scheduled by default.
An alternative would be to prompt the user about periodic plot checks on first run, but I think a better approach would be to add a maintenance/advanced side-tab to the UI, and expose various plot verification options there (e.g. manual check, schedule periodic checks, etc.) The same sub-tab would probably be a good place to also add upnp and logging related options.
