### ISSUE TITLE
[BUG] Stuck at the rotating icon of connecting to the wallet ##Resolved

### ISSUE THREAD

**Issue by killerfrost22** [Chia-Network/chia-blockchain#5171]
**Describe the bug**
Stuck at the rotating connecting to the wallet

**To Reproduce**
1.My SSD is full and plotting is stuck at 31% 
2. I did a restart and windows updates. 
3,  I am stuck at connecting to a wallet after the restart 
4. I tried reopen and reinstall chia blockchian app
5. still stuck at connecting to a wallet

**Expected behavior**
I was expecting my wallet to show up but it didn't show up 

**Screenshots**
![ss](https://user-images.githubusercontent.com/36581618/118384202-33b21300-b5d2-11eb-9a5d-8b016ecab685.jpg)

**Desktop (please complete the following information):**

- OS: windows 10
- OS Version/Flavor: 10 H2
- CPU: intel i7 9700k

**Additional context**

**Comment by killerfrost22** [comment]
Problem resolved!
Steps I tried：
`Steps to do it:

Stop via task manager or:
C:\Users\username\AppData\Local\chia-blockchain\app-1.1.1\resources\app.asar.unpacked\daemon\chia.exe stop wallet
C:\Users\username\AppData\Local\chia-blockchain\app-1.1.1\resources\app.asar.unpacked\daemon\chia.exe start wallet`

**Comment by Qsnv** [comment]
Hi,
did you run the last line of text in cmd to fix this? or how did you do it because i'm having the same issue, 
Thanks

**Comment by cezse** [comment]
> Problem resolved!
> Steps I tried：
> `Steps to do it:
> 
> Stop via task manager or:
> C:\Users\username\AppData\Local\chia-blockchain\app-1.1.1\resources\app.asar.unpacked\daemon\chia.exe stop wallet
> C:\Users\username\AppData\Local\chia-blockchain\app-1.1.1\resources\app.asar.unpacked\daemon\chia.exe start wallet`

hi mate,
i have same problem
how can i stop wallet ? do you have discord account ? can you help me if i open stream 2 you

**Comment by luotinen** [comment]
Hi!

I tried
C:\Users\**username**\AppData\Local\chia-blockchain\app-1.1.5\resources\app.asar.unpacked\daemon\chia.exe stop wallet
C:\Users\**username**\AppData\Local\chia-blockchain\app-1.1.5\resources\app.asar.unpacked\daemon\chia.exe start wallet

But still stuck at rotating icon

**Comment by LewyMaster** [comment]
you can use 
`C:\Users\username\AppData\Local\chia-blockchain\app-1.1.5\resources\app.asar.unpacked\daemon\chia.exe start -r  wallet` instead of chia stop. but better is close all chia processess, then try to run:
`C:\Users\username\AppData\Local\chia-blockchain\app-1.1.5\resources\app.asar.unpacked\daemon\chia.exe start all`

it works for me. 

ps. earlier i tried to rename `.chia` directory for backup and start chia-blockchain app again. after app open your full node should be not synced (like first time started) but if you close the app now (file->exit) then rename backuped folder to .chia again then all should works fine and will be only not "fully" synced.

**Comment by killerfrost22** [comment]
To friends who are still in trouble on my other machine, I had the same issue but it is resolved in a different way. Hope this is helpful.
Steps tried:
Delete these folders:
C:\Users\yourusername.chia
C:\Users\yourusername\AppData\Local\chia-blockchain
C:\Users\yourusername\AppData\Roaming\Chia Blockchain
