### ISSUE TITLE
[BUG] Win GUI Reload failing - Permanently "Connecting to Wallet"

### ISSUE THREAD

**Issue by zedeyeknight** [Chia-Network/chia-blockchain#5290]
**Describe the bug**
I was having an issue seeing my Harvester on my Main Farmer / Full node , under the Farming page (Advanced). So I thought I'd refresh the screen, via View / Reload. As soon as I did this, the gui screen went blank and then I have got the "Connecting To Wallet and spinning arrow" loop of death.

**To Reproduce**

As above. I refreshed again and same issue. I've not attempted a forced reload, as I don't want to lose my cached data.

**Expected behavior**
I expected to see to see my Chai Farm, Node status etc. - Basically the normal gui!

**Screenshots**
<img width="814" alt="Capture" src="https://user-images.githubusercontent.com/84327253/118497007-90b9e000-b71c-11eb-8026-9bf43d781e43.PNG">

**Desktop (please complete the following information):**

- OS: Win10 64bit
- OS Version/Flavor: 19042.964
- CPU: Intel(R) Xeon(R) CPU E3-1230 V2 @ 3.30GHz   3.30 GHz

**Additional context**
I've checked my chai farm summary and it all look hunkydory.
Nothing untoward in Debug.log either. (At least to my limited noob knowledge)
--------
Farming status: Farming
Total chia farmed: 0.0
User transaction fees: 0.0
Block rewards: 0.0
Last height farmed: 0
Plot count: 160
Total size of plots: 15.838 TiB
Estimated network space: 6107.670 PiB
Expected time to win: 2 months and 1 week
Note: log into your key using 'chia wallet show' to see rewards for each key

**Comment by MadsBoss1** [comment]
Same for me

**Comment by Jason-xy** [comment]
As well as mine

**Comment by JulioImolesi** [comment]
Same here too.. started today when I restarted computer to resync because sync was taking too long (20h+)
Already reinstalled, but without success, 

SOLUTION for me: 
Close app;
Rename or delete  directory c:\users\USERNAME\.chia
WARNING: You will have to type 24 mnemonic words again, import plots directory and sync everything =/

**Comment by Jason-xy** [comment]
Thank you, the solution is fortunately worked for me!

**Comment by zedeyeknight** [comment]
It's pretty much the same issue when I used to try and delete a running plot - it would barf the gui like this too.
 I'm loathed to restart as syncing took 48 hours last time (about 10 days ago) Any guidance on how to avoid a full resync of the blockchain or at least reducing the time to resync, would be appreciated.

**Comment by number435398** [comment]
This same thing happens to me near the end of multiple plots, and then, for one reason or another I delete one and instead of deleting it and moving on, it starts to show that same screen.  Turning it off fixes it, but, without being able to "resume" plotting, I'm out many many hours of plotting every time this happens.

**Comment by kushariforyou** [comment]
Same issue here. But I'm leaving it as I can see activity on my drives, which means the plotting is still going on in the background.  I think there might be some sort of memory leak as after a day or two, things become really slow even when I have lots amount of resources.

**Comment by MadsBoss1** [comment]
I got it to work if you unstall chia, and then after go to "users" and then .chia and remove the folder, it will work when you install it again and you will still have all you plots

**Comment by number435398** [comment]
@MadsBoss1 I haven't had the issue of it not working properly afterwards.  I mean the same problem crops up eventually, but by closing the program and ending all processes in task manager I am able to get it to work again.  At least until I try to delete another plot mid process that is.

**Comment by kushariforyou** [comment]
> I got it to work if you unstall chia, and then after go to "users" and then .chia and remove the folder, it will work when you install it again and you will still have all you plots

That's not the point, you can just close the wallet and open it again and the plots are there. I'm talking about the plots you're currently plotting.

I was able to get it to connect by killing some of the chia instances that handle the webGUI in Task Manager (screenshot attached), then I stopped all the services by running .\chia stop all and then .\chia start all. However I don't see the plotter active, even though it still is in the background. After if finishes the next three plots, I'll shutdown everything and run it again. Seems like the UI needs some work, maybe a memory issue or something.

**Comment by number435398** [comment]
Dev window showed the following information when this happened to me again (Lost a 10+ hour set of plots because of it too):
`DevTools failed to load SourceMap: Could not parse content for file:///C:/Users/(USER)/AppData/Local/chia-blockchain/app-1.1.5/resources/app.asar/build/renderer/js/80.js.map: Unexpected end of JSON input`
and many statements of 
`Already connected, not reconnecting.     main.js:1 `
