### ISSUE TITLE
Chia is gone

### ISSUE THREAD

**Issue by Raaajup** [Chia-Network/chia-blockchain#5312]
Hi Guys,

My wallet the other day was stuck "connecting to wallet", so in the end I deleted .chia file from user folder on c drive and reinstalled chia client (I did copy the file so still have it). I then entered my key which had farmed a few Chia and let it sync back up, however once it had synced it still says my balance is 0 having synced for over a day. Is there any way of getting the Chia that I have farmed back?   

Thank you any help really appreciated.

**Comment by avitron78** [comment]
Check that these three things are in sync. 1 "connection status", 2 "Status", 3 "Wallet" You should have all three things in sync. That was what they told me from the technical support, they told me that the wallet also had to synchronize and since in my case it was a new wallet, it had not synchronized, I have been waiting almost two days for the wallet to synchronize, the numbers advance very slowly, one Once I do, I will check if my issue has been resolved.

**Comment by Raaajup** [comment]
Thank you I'll give it a go and try to be patient..
