### ISSUE TITLE
I have a confused question that the Plot file fill up to max (2TB) my disk, and i have not get any reward from Chia. So the question is how i solve the Plot file on my disk? delete? or change a new disk?

### ISSUE THREAD

**Issue by lixbai** [Chia-Network/chia-blockchain#5367]
I have a confused question that my disk is 2TB, and i farm the Plot file .
Now it will fill up to max (2TB) my disk soon, and i have not get any reward from Chia.

So the question is:
How i solve the Plot file on my disk? delete? or change a new disk?

OR, if the plot file couldn't delete, i think it will be waste to environment. Because everyone that mine the XCH, as the time increasing. We will be couldn't afford the disk fee. 

Please give me your advise.
Thanks

**Comment by handsomedude** [comment]
2tb is not worth it.
I have 17.6tb so far and I have received no rewards at all.
Shows 3 months estimate to a reward.

2tb is not gonna cut it.

I don't hold my hopes up and I have 178 plots currently and still have 4tb left to plot.

Network is growing so fast, it no later never viable to even start plotting now.

I'm filling my last 8tb and giving up.

Personally, it's become a complete waste of time and resources.

The amount of hard drive space, time, CPU and electrical usage to create all the plots for what? The time remaining to go up and receive nothing.

**Comment by Fabiettus** [comment]
Yes, it is a waste of time to design right now. No rewards if you don't have PiB of addressed space and the network is increasingly centralized. Maybe polls can help to get rewards, but you need to re-plot everithing.

**Comment by handsomedude** [comment]
At least other miners, you buy a GPU once and use that its entire life 

Chia, you have to keep adding more and more drives just to keep up. And in turn will kill the plotting drives eventually 
It has to be the dumbest miner I've used so far. 

A total of 1 month using drives, CPU etc and for what, absolutely nothing at all so far.

And as I said, I started when the reward was down to 2 weeks remaining.

I'm still yet to win anything.

The way I see it, before the pools come online, the creater need to send free chia to anyone who's been online farming for a while and got nothing.

Seems the biggest rip off in mining so far.

We all spending on hardware to get nowhere fast lol

**Comment by azaryc2s** [comment]
@handsomedude if you overspent on hardware, that's on you. No1 forced you to. If you think you're gonna get rich in 2 weeks, its the wrong project. Go buy some shit *-Inu token, wait for pump and drop before the dump. You have like 350$ (normal price before china started to buy out all of storage) worth of HDDs and you want to grab 2XCH, each worth over 1k$ already after few weeks? What's wrong with you man...and that argument with the GPU only shows, that you have absolutely no idea how any of this works ^^ how are you not falling behind with a GPU, when the hash-power is also constantly increasing there? If you cannot handle long dry-periods of not receiving Chia, wait for the pooling-support and replot your 17TiB. Even without a SSD this takes under a week without any investment.

**Comment by handsomedude** [comment]
Read what I put.  The way it's growing, you need to keep adding space to keep up otherwise you won't get reward.

Mate of mine has 18 coins so far.  He started early 

But now it's not feasible to even start.

I haven't complained once about spending as I already had the equipment here!!.

I just said it a waste of time now.

The way the network is growing, you could farm for years and never get anything at all.

And when pools come out, you have to re plot everything again killing more hardware 

That's the waste of time.

**Comment by azaryc2s** [comment]
don't give me the "centralized" argument here. I'm all aware of the attacks. But apparently you don't get how things work. "Small farmers" or miners, or whatever never get paid frequently. Do i get paid in BTC, if i run a miner on my shitty old graphics card? I can run it for years and waste tons of electricity, and not get a single $...so what are you on about man? You want pools so that "the small farmers can get paid"? But this invalidates your argument about the centralization, since pools are doing more or less exactly that...centrilize the network. The only problem with the network right now is hpool with their scam-client, and since people over there apparently have no backbone at all, things are as they are right now. Saying things like "chia should pay small farmers this and this way" are childish AF. This is not how things work. If you have any brilliant idea on how to secure the network by limiting every person to lets say 1TiB, then c'mon, share this idea with the world. We would all (well not hpool) be better off if there was no race in hash-power/disk space...even BTC would be eco-friendly if every person was limited to 1 CPU as Satoshi wanted - but it's simply not the reality, so please stop whining.

But sure, be my guest, quit :)

**Comment by handsomedude** [comment]
It's states you are rewarded for the amount of space contributed. 

But you have to keep contributing to even get a chance of reward. 

they should have implemented pools from the start.

And to stop China hpool, they could simply ban the wallet address you'd think. 

And not I'm not stopped because its running on my GPU miner. The one that actually pulls in revenue lmao

**Comment by Fabiettus** [comment]
You are a funny man dude... is yours an analisys?? Why BTC network is comparable with chia network?? In my contries, nobody works for nothing, its simple. and in 2009, i mined BTC with a Pentium 4 minitower pc....
Anyway i can see the problem, you not? for example it's normal a syncing time of days??? What about the continuosly out of sync of nodes? maybe some whale are kicking off clients from networks? I don't have the answer, but it's simple, if i can get a reward with my 85TiB plot because i suspect that someone is manipulating the blochchain, well i'm out. If you are a gambler, this is a game for you, you can watch the screen all the day hoping a couple of chia appears in your wallet!!!. Have a nice farm!

**Comment by handsomedude** [comment]
Who said I'm watching it all day.  Who said I'll get rich fast??? 
You not me. 
I know how it works. 
But you think the size of the network, the amount of rewards would go up 

4032 chances of winning a day from the start.  And now the size of the network and it's still 4032.
Chances of winning get lower and lower the more the network grows which could make it impossible to farm anything given years lol 

And not everyone has 85tb of space.  Wasn't this made for the use of spare hard drive space pmsl.

Yet lots of people are overbuying expecting big rewards.

Just be nice to a single reward. Like I said, mate has 18 coins.
He started 2 weeks before me and I can't catch up.

Even his rewards have gone from days to months the way it's growing.

You'd think, bigger network, more rewards available.

That all I'm saying.

Keep your knickers on😂🤭

**Comment by Fabiettus** [comment]
Handsomedude... i was talkin' about @azaryc2s comments.... did you saw @azaryc2s at top of my answer????
I'm perfectly agree with you about chia farming, even if i have 85TiB of plots.

**Comment by handsomedude** [comment]
Sorry dude.  My bad😜

**Comment by redbaron** [comment]
Please open discussion or ask in a keybase chat.Project is swamped with questions like this, it makes hard to use it as a bugtracker to report and resolve _software_ bugs.
