### ISSUE TITLE
[BUG] Synchronisation problem [BUG]

### ISSUE THREAD

**Issue by mpmarinov** [Chia-Network/chia-blockchain#5389]
Dear Sir or Madam, 

I have a question for the synchronisation. Do you have problems or is something different. I have been running for 1 week and it is still not synchronised.

What is going on at all?

My Chia Blockchain runs under:

 System: Windows 10 Pro
 Edition: 20H2
 Systembuild: 19042.928

Thank you!

**Comment by Herrjehmann** [comment]
Hello,
an issue about that was closed and moved to a discussion. Not to sync with the blockchain is not an issue for chia I guess - ROFL
#5270

**Comment by antst** [comment]
Yeah. At least half of 1k open issues are about the sync and sync is not an issue! )))

**Comment by wbendick** [comment]
change your log level to info and post your log

**Comment by sargonas** [comment]
A multitude of the issues on sync are moved to discussions because the Discussions>Support section is the ideal place to handle most support issues while people troubleshoot. There are a myriad of reasons that can cause this from a multitude of sources, and so tracking every conversation here as a "Bug" is not effective for either the Chia team or for users like you who need clarity. 

By having community sourced support in discussions, folks can help each other troubleshoot the issues, and that vast majority of the time that gets things resolved. In the event that the troubleshooting efforts result in a clearly identifiable bug in the chia code itself that can be documented and outlined clearly, then by all means it can be carried over from the discussions forum into the Issues and tracked.

As wbendick asked, feel free to post your log output in Info mode here, and folks can help see if we can identify any obvious causes. The fact is, there are *many* things that can inhibit sync, blocked ports, broken UPNP configurations, (or conflicts with both open), ISP blocking, ISP's that reset IPs randomly, a multitude of peers around you who did not update to 1.1.5 and are on bad blocks, a corrupted peers database causing you to keep connecting to the same bad nodes, the list goes on. There is no single cause and therefore magic solution to this, unfortunately.

**Comment by mpmarinov** [comment]
Hello, 

I can't post anything right now because it hangs when connecting to Wallet again. It happens from time to time, but today is really bad.

 Maybe later I will post the info you need.

Have a nice day :)

**Comment by mpmarinov** [comment]
Hello again, 

Would someone help me find this log file. I don't see anything in the software that I can use as a log file. I have 3 plots that are ready but the software keeps showing me at farm status: sync. This has been going on for 2 weeks.

![Full_Node_Status](https://user-images.githubusercontent.com/84374112/118833814-09a66c80-b8c2-11eb-8aa9-5ceba1b0e021.jpg)

<img width="272" alt="Farmming_Status" src="https://user-images.githubusercontent.com/84374112/118833821-0ca15d00-b8c2-11eb-9b31-1edbb746a130.png">
