### ISSUE TITLE
[BUG] Cannot add plot directory after moving a drive from one plotting computer to the main node

### ISSUE THREAD

**Issue by pluto2021** [Chia-Network/chia-blockchain#5482]
**Describe the bug**
When moving a drive full of plots from one plotting computer to the main node, and try to add the plotting directories on that drive, the GUI would give the following error,

[Error 13] Permission denied. You are trying to access a file/directory without having the necessary permissions. Most likely one of the plot folders in you config.yaml has an issue.

While I clearly have access to the directories using windows explorer. The folder was actually added to the config.yaml 
But due to the error, the plots are not farmable after the drive is moved.

**To Reproduce**

1. Move the external HDD from a plotting computer to the main node
2. Add directories within the GUI (while it is still plotting)
3. Error will show up.

**Expected behavior**
Moving external HDDs from one computer to another should be easy without experiencing difficulties.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- OS Version/Flavor: latest build and updates
- CPU: Intel

**Additional context**
Folder access permission check to be fine. Manually added the current user on the main node, still not working.

**Comment by room101-dev** [comment]
Edit the config.yaml in .chia/main-net/config yourself, right there enter the dir paths and restart "chia start -r all"

Never use the chia GUI, it doesn't work. It's broken post 1.3 and it appears that all of chia-dev is now hosed. The rushed to main-net 5may2021 without appropriate testing, now they're in a world of shit.

Cut & paste each dir in the config file and do a linux "ls" on that file path, if cmd-linux can't find the path-files & permission ok, then chia will not, 

Seems to be lots of problems with permission, largely because people install with root, where ownership of everything should be user

Don't  use CHIA to harvest your prot's use HPOOL and make some real money, their software is rock-solid, ever since 1EB 2+ weeks ago, chia no longer pays out  to solo-miners unless you have say 10k plots, just use hpool on your plots, and make some real money everyday off CHIA.

Don't use the GUI, use the cmd-line from 'user' consistently start the chia process always same 'chia start -r all'

I would for now keep coins off of the chia wallet it is broken, and has no security. I prefer to keep my coins elsewhere.

At this point in time the only software from chia-dev I use is the plotter, hpool has their own plotter, but its not open source, so I will not use it, but everything is fine, I sign their public-key, with my private and they can mine my plots all is good.

The only Main-Net I have that still runs is my original I setup months ago running on linux mint, in the past two weeks I have tried to bring up two new chia main-nets one on ubuntu 18, other ubuntu 20, both fail to ever sync, and take 3-4 days to get up to block-level. My oldest one even in its best day would always lose sync for 10 minute every hour, the chia-net is shit.
