### ISSUE TITLE
Windows10 Version1.1.6 Installation Failed 

### ISSUE THREAD

**Issue by MaxBill** [Chia-Network/chia-blockchain#5684]
Today, the installation of the latest version 1.1.6 on win10 failed. The error box prompts you to open the error log without responding

![image](https://user-images.githubusercontent.com/16558525/119112687-e095f100-ba13-11eb-84db-ad60e8ef0d82.png)

**Comment by joe159119** [comment]
I have same issue on Windows 10. In my case, I already installed the version 1.1.5 and trying to update to 1.1.6.
Seems "Nvidia Share" locked Chia's 1.1.5 DLLs in %Appdata%/local.
The solution is stop all NVIDIA background program and reinstall it. Or you can reboot to safe mode to install it.

References:
https://github.com/Chia-Network/chia-blockchain/issues/4531#issuecomment-842957390

**Comment by DilshodUzakov** [comment]
> I have same issue on Windows 10. In my case, I already installed the version 1.1.5 and trying to update to 1.1.6.
> Seems "Nvidia Share" locked Chia's 1.1.5 DLLs in %Appdata%/local.
> The solution is stop all NVIDIA background program and reinstall it. Or you can reboot to safe mode to install it.
> 
> References:
> [#4531 (comment)](https://github.com/Chia-Network/chia-blockchain/issues/4531#issuecomment-842957390)

It's work for me. Thanks!

**Comment by AnTaNiAl** [comment]
bingo, thx.

**Comment by r0mac09** [comment]
Had the same issue, ran it as Admin and it worked just fine

**Comment by konsou** [comment]
I had the same problem but the root cause was a running harvester in the background. Didn't spot it a first since it's process name didn't start with "chia".

**Comment by kvizena** [comment]
On Windows open a command prompt (cmd.exe) as an administrator. 

net stop NVDisplay.ContainerLocalSystem
net stop NvContainerLocalSystem

Run the chia upgrade, then start the services again.

net start NVDisplay.ContainerLocalSystem
net start NvContainerLocalSystem

If I wrote the installer I would check to see if any of the files are locked, then bubble up the process/service in the pop-up or at least the logs. 

Nvidia is locking two or three DLL's and stopping the upgrade. It is actually pretty bad since the installer removes the previous files before running into the locked files, and doesn't rollback. I loaded up process explorer and ida to find the locked files parent.
