### ISSUE TITLE
Lost private key with over 30TB of plots created with the same farm and public pool key!

### ISSUE THREAD

**Issue by Qman45** [Chia-Network/chia-blockchain#5747]
hi ... i had to re-install ubuntu on my plotter and I cannot find my private key associated with the public farm and pool keys i input into the plotman.yaml.  To compound the issue, I'm running another 2 plotters whose farm and pool keys are the same as the first plotters i.e. I copied the original farm and pool public keys from the first plotter and entered it into the plotman.yaml's for the next 2 plotters I set up  (as i wanted to keep all my plots with uniform farm and pool keys across all my plotters).  But now that I've misplaced my first plotters private key (which is linked to the farm and pool public keys) does it mean that all my plots are now wasted? 
Am I right in thinking that it doesn't matter as when I assign the plots to the farmer, I don't need the original private key?
Please help as this is 2 weeks of intensive plotting that could be up in smoke!

**Comment by Plopsi** [comment]
You should always keep your private keys - as in the name: private.

Your farmers not really need, and should not, know your private key. The same for plotters. As long as you have the mnemonic - or the private key - of your payout wallet you are fine.

The certificates you copy to your farmers or harvesters are intermediated - and used to allow farmers and harvesters to connect to your full-node. Which then will populate found proofs, if any.

As long as you have entered the public correct key for farmer and pool to your plotter it will create proper plots.
As far as I know you could use plots with different pool keys and farmer keys - as the keys determine the payoutaddress. But here I'm not sure, from my experience at least the farmer key need to fit to a known wallet on the full-node side, but could be, and most probaly is wrong.

As far as you have your private key and/or mnemonic you can recover everytime.

`chia plot check` or even shorter `chia plot check -n 5` will show you the farmer and pool public key of the plots - on cost of time, because it challenges every plot.
If the keys fit, you are fine.

I hope I got the question covered you are questioning... No right for truthiness or completeness... It's the best I can do on this Textwall - please use ENTER next time to format your question - and use the template as far it utilizes.

**Comment by Qman45** [comment]
> You should always keep your private keys - as in the name: private.
> 
> Your farmers not really need, and should not, know your private key. The same for plotters. As long as you have the mnemonic - or the private key - of your payout wallet you are fine.
> 
> The certificates you copy to your farmers or harvesters are intermediated - and used to allow farmers and harvesters to connect to your full-node. Which then will populate found proofs, if any.
> 
> As long as you have entered the public correct key for farmer and pool to your plotter it will create proper plots.
> As far as I know you could use plots with different pool keys and farmer keys - as the keys determine the payoutaddress. But here I'm not sure, from my experience at least the farmer key need to fit to a known wallet on the full-node side, but could be, and most probaly is wrong.
> 
> As far as you have your private key and/or mnemonic you can recover everytime.
> 
> `chia plot check` or even shorter `chia plot check -n 5` will show you the farmer and pool public key of the plots - on cost of time, because it challenges every plot.
> If the keys fit, you are fine.
> 
> I hope I got the question covered you are questioning... No right for truthiness or completeness... It's the best I can do on this Textwall - please use ENTER next time to format your question - and use the template as far it utilizes.

Thanks for this - I think what you are saying is that as long as the farmer and pool public keys have been correctly generated, then I don't need to worry about not having the private key that created/is linked to these farm and pool public keys, as the farmer / harvesters both don't need this private key,  they just need to have access to valid plots which have valid farm and pool public keys.  Any CHIA payouts/wins I receive for these plots will be made to my wallet which is connected to the node network,  - so it's the private key of the wallet that is very important - which you said you're not sure about, but have I understood you correctly?

Thanks again for  your input - and hopefully the format of this question is better!
