### ISSUE TITLE
i am loosing plots. yesterday i had 19 plots in my chia farming and i checked it now it shows only 11 plots can any one give an answer. 

### ISSUE THREAD

**Issue by el17ded** [Chia-Network/chia-blockchain#5760]

**Comment by Plopsi** [comment]
on a network drive? check connection
in (windows) GUI? check the farm tab if it shows the correct number in the last checks (0/xxx) the main UI does not properly update

My 2 cents, as I have up to now don't experience other problems.

PS: the template is here for a reason, please use it and don't write everything in the title - otherwise this should be hardly closed without any answer.

**Comment by el17ded** [comment]
this problem occurred few days ago i used to have 37 plots and all of the sudden were missing. i check my external hard was full but the plots are missing in my chia account i waited few days before i delete and format my  EX HHD. i started again but it seems giving me same problem.

**Comment by jakuba1909** [comment]
@el17ded only happens to me when i overheat my hdds and they lose general connection to my rig.. dont delete plots, usually if they a re finished they get found again.. after cooling down and refreshing given hdd it shows up again and all plots are back in position
