### ISSUE TITLE
[BUG] Added plot does not start, only put in queue

### ISSUE THREAD

**Issue by MrChickenBacon** [Chia-Network/chia-blockchain#5819]
**Describe the bug**
When adding a new plot and go from "Add to queue" and "Recruit in Parallel" and back again to "Add to queue" and complete the rest of the fields. The Plot never starts, it only goes into queue (see screenshot).

**To Reproduce**

1. Go to 'Add a plot'
2. On step [2] Click on "Recruit in Parallel"
3. Enter a number in the "Wait" field
4. Change back to "Add to queue"
5. Leave everything else with default options
5. Fill in step [3] & [4] like you normally would.

**Expected behavior**
That the plot would start plotting.

**Screenshots**
[Confused plotter](https://imgur.com/b9qPdLY)

**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: 10 Pro
- CPU: AMD Ryzen 5 3600 6-Core Processor
- Chia 1.1.6 GUI

**Additional context**
I was going back and forth choosing between parallel and normal queue, when i noticed this.

Restarting Chia and only sticking to one of the 2 options solves the problem.

**Comment by Manakel8** [comment]
Hello

I have almost the same problem.
In my case, the plots are launched for the first time (in "Add Plot to Queue" or "Plot in Parallel" mode), but the plots "Queued" in the tail do not activate at the end of the plotting.
therefore as soon as the initial studs are finished, only the no tail studs remain. And in addition it is no longer possible to remove them.

therefore since the release of 1.1.6 each plot has to be started manually. Suffice to say that it is a priority bug!

This bug appeared in version 1.1.6

System: Windows 10 pro

Expected behavior
That the plot would start plotting.

Screenshots : same as MrChickenBacon

Desktop (please complete the following information):

OS: Windows
OS Version/Flavor: 10 Pro
CPU: Intel 4770k
Chia 1.1.6 GUI

Thank you

Manakel

**Comment by nyczducky** [comment]
Same issue.
First Plot
Step 1: k32
Step 2: Add Plot to Queue + Default Settings
Step 3: Temp Drive 1
Step 4: Final Drive 1

Second Plot
Step 1: k32
Step 2: Plot in Parallel + Wait Time 140 minutes + Default Settings
Step 3: Temp Drive 2
Step 4: Final Drive 2

Queue for first plot runs. Second plot they are all added in queue with no way to delete since that option was removed.
