### ISSUE TITLE
[BUG] wallet sync issues!

### ISSUE THREAD

**Issue by great-huawei** [Chia-Network/chia-blockchain#5951]
chia wallet synced and height done, but UI was showing syncing. I must close CHIA, reopen it and its fine!
![image](https://user-images.githubusercontent.com/35336924/119379843-8e462000-bcf2-11eb-8fe9-841b19faed7b.png)

**Comment by PapiDot** [comment]
Also, GUI synced very slowly. After reboot, even all the nodes were counted up, GUI continued to show unsynced for days. Although eventually being synced, GUI may still fall out of sync for hours, then synced again.

I have stopped plotting to preserved my NVMe SSD. Instead, just watching the network space growing like water filling from a flood gate for fun.

Aha, right at this moment, my GUI turned into "Not Synced" again. Solo mining is virtually impractical, not only because the size of network, but also the GUI constantly going our of sync and slow to re-sync.
