### ISSUE TITLE
Slow Copy Time

### ISSUE THREAD

**Issue by Gnaarki** [Chia-Network/chia-blockchain#6018]
Hello,
I have 8 plots in parallel on 3 SSD , 3 on SSD1 and SSD2 and 2 on SSD3. I´ll start them with a queue with different Names A1, A2 ,A3 for SSD1, B1,B2,B3 for SSD2 etc..
I have the problem that the plots stuck at 100% without an error. It seams that they copy really slow. Until now I´ve tried it two times. The first time every Plott on SSD1 works fine and SSD2 and 3 get stuck for every queue by 100%.. The second time the queue A1, B1, C1 get stuck at 100% and the overs work fine. 
Also the overall copy time is high if it works, something around 2 Hours.
I´ll  copy the plots to a Network attached NAS (DiskStation 2419+ from Synology). 
I´ve tried to copy big files directly to the NAS and it worked with a speed up to 140MB/s, while the plots are stucked.

If a queue gets stuck the harvester didn´t recongnize new Plots until I delete the plots stuck at 100%

I´ve seen one log with a Copy Time of 64000sec.

My System is:
Ryzen 5950x
64GB Ram
Ubuntu 20.04 LTS
Client Version 1.1.6

The plotting parameters are:
7000GiB Ram
4 Threads

No errors or warnings in plotter log and normal log.

Has anyone an idea what can cause the problem? I can´t find anyone with the same problem.

**Comment by room101-dev** [comment]
You must stagger every 'chia plot create ..' by at least 30 minutes, it take 20min to transfer a 108gb file
Say you run all at the same like your doing, then you have 4 threads, all trying to write, its no 4 x 20, 80 minutes, its more like 8 days, because instead of sequential, your doing random access, and the hdd's are NOT designed for this abuse.

Lastly, chia kills drives, remember this, if you continue to do this you kill this target (-d) drives.

The files(108gb) must be transferred one at a time, you can google script for chia that show how to 'wait 1h' between each thread initiation.
THe cmd-line is 'chia create plots -t /dev/ssd-nvme -2 /dev/ssd-sata -d /dev/hdd'

U need to have at least 280GB free for each thread on the nvme, you need to have N x 108gb free on the SSD for temp, you need to have N * 108gb free on the target hdd -d
 Names 
wait 0m; A1,
wait 30m; A2 ,
wait 30m A3 for SSD1, 

wait 30m;B1,
wait 30m B2,
wait 30mB3 for SSD2

SSD1/SSD2 are NVMES, SSD3 is a sata-ssd
