### ISSUE TITLE
[BUG] Some of the plots being created are stopped v1.1.6

### ISSUE THREAD

**Issue by vanthoi** [Chia-Network/chia-blockchain#6044]
**Describe the bug**
I found version 1.1.6 has problems creating plots. While creating the plots, there were a few plots stopped for unknown reasons. The log hasn't been updated with any errors since the standstill. I tried waiting more than 12h with the above plot. But nothing happens to both the log and the files in the temp directory. All the plots I've seen are still running in the background.

**To Reproduce**
Just create plots and wait

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- OS Version/Flavor: 20H2 Build 19042.985
- CPU: AMD Ryzen 9 5950x

**Additional context**
My system is not overloaded with CPU or RAM. I only ran 8 to 14 plots in parallel on one go. 
With RAM 7500, Thread 2, Bucket 128.
I tried running them via CLI still getting the same error as on GUI.

**Comment by keliew** [comment]
There's usually an error message if plotting fails.

**Comment by vanthoi** [comment]
> There's usually an error message if plotting fails.

If there are any errors inside the log I have solved them. Unfortunately in the log all is normal. In the system process the background plots (chia.exe) just lie there. The CPU speed of this process is zero and the disk speed is also zero. I think something went wrong inside chia.exe core causing them to hang.

**Comment by keliew** [comment]
> > There's usually an error message if plotting fails.
> 
> If there are any errors inside the log I have solved them. Unfortunately in the log all is normal. In the system process the background plots (chia.exe) just lie there. The CPU speed of this process is zero and the disk speed is also zero. I think something went wrong inside chia.exe core causing them to hang.

So which phase is it in?

**Comment by keliew** [comment]
There isn't any significant change in 1.1.6 for the plotting module.

Have you tried just plotting 1 and see the results?

Sounds more like a hardware failure somewhere...

**Comment by CityJumperAC** [comment]
Having the same issure.
None of the plots generated by the Windows Harvester are functional.
No valid Plots since Update to 1.1.6

2021-05-26T06:20:52.587 harvester chia.plotting.plot_tools: ERROR    Failed to open file \\10.10.0.5\h$\#Chia\plot-k32-2021-05-25-06-58-4faffc5a9a3d23b2b5cfa5db6bd3e2d055ab3ce9eb0273267db3be2790852358.plot. Invalid plot header magic Traceback (most recent call last):
  File "chia\plotting\plot_tools.py", line 189, in process_file
ValueError: Invalid plot header magic

An the one Plotter LOG: 

	Bucket 127 QS. Ram: 3.240GiB, u_sort min: 0.563GiB, qs min: 0.281GiB. force_qs: 1
	Finished writing C1 and C3 tables
	Writing C2 table
	Finished writing C2 table
	Final table pointers:
	P1: 0x10c
	P2: 0x374810e4e
	P3: 0x6b5ef0865
	P4: 0x9fdb28a4d
	P5: 0xd559d9e11
	P6: 0x10d939c314
	P7: 0x14e9881505
	C1: 0x1909353205
	C2: 0x19094f66dd
	C3: 0x19094f678d
Time for phase 4 = 1177.810 seconds. CPU (83.490%) Sun May 23 04:17:27 2021
Approximate working space used (without final file): 269.325 GiB
Final File size: 101.345 GiB
Total time = 35209.012 seconds. CPU (141.450%) Sun May 23 04:17:27 2021
Copied final file from "D:\\plot-k32-2021-05-22-18-30-db11c22704ecf4e2deaf4c0e52edf49dfa886b18e968c5fb283d7c2190862033.plot.2.tmp" to "Y:\\plot-k32-2021-05-22-18-30-db11c22704ecf4e2deaf4c0e52edf49dfa886b18e968c5fb283d7c2190862033.plot.2.tmp"
Copy time = 302.123 seconds. CPU (17.640%) Sun May 23 04:22:29 2021
Removed temp2 file "D:\\plot-k32-2021-05-22-18-30-db11c22704ecf4e2deaf4c0e52edf49dfa886b18e968c5fb283d7c2190862033.plot.2.tmp"? 1
Renamed final file from "Y:\\plot-k32-2021-05-22-18-30-db11c22704ecf4e2deaf4c0e52edf49dfa886b18e968c5fb283d7c2190862033.plot.2.tmp" to "Y:\\plot-k32-2021-05-22-18-30-db11c22704ecf4e2deaf4c0e52edf49dfa886b18e968c5fb283d7c2190862033.plot"
2021-05-23T04:22:32.093  chia.plotting.create_plots       : [32mINFO    [0m Summary:[0m
2021-05-23T04:22:32.115  chia.plotting.create_plots       : [32mINFO    [0m Created a total of 1 new plots[0m
2021-05-23T04:22:32.116  chia.plotting.create_plots       : [32mINFO    [0m plot-k32-2021-05-22-18-30-db11c22704ecf4e2deaf4c0e52edf49dfa886b18e968c5fb283d7c2190862033.plot[0m


any ideas?

**Comment by vanthoi** [comment]
> There isn't any significant change in 1.1.6 for the plotting module.
> 
> Have you tried just plotting 1 and see the results?
> 
> Sounds more like a hardware failure somewhere...

All plotting process, CPU only running from 35% to 60%, RAM no more than 65%. I also doubt about my hardware. I have 64GB of Corsair pro 3200 RAM. Most recently I added 32GB of Gskill 3200 RAM. The RAM latency is different, I had to change 32GB of low latency for channel A, and Corsair is for channel B. Otherwise my computer will crash at startup. AMD CPUs are really picky about RAM :(

**Comment by keliew** [comment]
> > There isn't any significant change in 1.1.6 for the plotting module.
> > Have you tried just plotting 1 and see the results?
> > Sounds more like a hardware failure somewhere...
> 
> All plotting process, CPU only running from 35% to 60%, RAM no more than 65%. I also doubt about my hardware, Everything else on my machine is running fine without any errors. I have 64GB of Corsair pro 3200 RAM. Most recently I added 32GB of Gskill 3200 RAM. The RAM latency is different, I had to change 32GB of low latency for channel A, and Corsair is for channel B. Otherwise my computer will crash at startup. AMD CPUs are really picky about RAM :(

Probably an issue with overclocking somewhere too...

**Comment by vanthoi** [comment]
> > > There isn't any significant change in 1.1.6 for the plotting module.
> > > Have you tried just plotting 1 and see the results?
> > > Sounds more like a hardware failure somewhere...
> > 
> > 
> > All plotting process, CPU only running from 35% to 60%, RAM no more than 65%. I also doubt about my hardware, Everything else on my machine is running fine without any errors. I have 64GB of Corsair pro 3200 RAM. Most recently I added 32GB of Gskill 3200 RAM. The RAM latency is different, I had to change 32GB of low latency for channel A, and Corsair is for channel B. Otherwise my computer will crash at startup. AMD CPUs are really picky about RAM :(
> 
> Probably an issue with overclocking somewhere too...

I am optimizing to achieve 50 plots per day. So I haven't done OC RAM or CPU yet.

**Comment by canhmai** [comment]
i think you need generate with v1.1.2 , i'm using very stable . and threads more than 2 you never had bad error or something like that . good luck

**Comment by edjosephgr** [comment]
I have a same problem, in cli windows or gui the plotting stop and no show errors, after 14h no cpu o ram o sdd move. With only one plot. 
Cpu amd A10 7890 apu
Ram corsair 16Gb ddr3
NVMe 1tb gigabyte
