### ISSUE TITLE
[BUG] Random 'Not enough memory for sort in memory' plotting failures

### ISSUE THREAD

**Issue by racergoodwin** [Chia-Network/chia-blockchain#6053]
Randomly, either of my dedicated plotting machines will fail with the message: -
'Caught plotting error: Not enough memory for sort in memory. Need to sort...' the amounts have varied from around 5GiB to over 13 GiB.
It seems to be happening as Compressing tables 2 and 3 begins.
Chia versions 1.1.5 and 1.1.6 have both exhibited the same fault.
Plotting using command line with defaults for everything except 3 threads and the temp and final folders. No other no OS processes running. At least 200GiB RAM free this last time.

Plotting machines are Dell R620 servers with 2 x 8 core CPU's and 768GB RAM
OS : Linux
Version: Ubuntu 20.04
CPU: 2 x Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz
RAM: 768GB DDR3 1333MHz Registered ECC
All updates applied daily

**Comment by room101-dev** [comment]
How many plots on the drive you trying to do? **They need about 280gb real,** say a 10TB formatted you only get about 950gb, you 768GB, has less than 750, so you can only do 2 plots in parallel did you do a ram drive? how many how big?

What's your cmd-line? You should have

chia plots create -t /dev/nvme -2 /dev/sata-ssd -d /dev/hdd

In your case, I'm assuming you have the ramdisk as the -t, but you still need another ssd for the intermediate temp plot
At best you can only do two plots in parallel in 750gb, and if you don't have -2, then that's why you can't do 2+ and run out

There is really no info, show us you cmd line you invoked, where is your ssd drives for -2 temp, how have you formatted your ramdisk? NFS? U say 3 threads as -r 3, or 3 plots at a time?

Ramdisk aren't that much faster than top shelf NVME, I get about 6 hrs to plot on NVME, and 5 hrs on ram, hardly a deal breaker, whats better is to plot 16x or 32x per day,  I run 3 nvmes on my mobo, two m2., and one on pcie4x16, need to have that ssd -2 temp for the intermediate plot, between the fast-temp and slow-hdd.

**Comment by racergoodwin** [comment]
@room101-dev as per my post, I am using the command line on dedicated Ubuntu plotting machines, except the threads and folders, so the actual command is 'chia plots create -r 3 -t /mnt/ramdisk -d /mnt/NVME'

Each plotting system has 768GB physical RAM with a tmpfs cache set at 710GB and a 20GB swapfile on the root SSD just in case, but the system has never used any of the swapfile. There is always between 10% and 20% free Memory (that's 75GB to 150GB free + 20GB unused swapfile) and the cache is always less than ~10GB from full. So neither machine is running out of physical RAM.

According the CLI information, there is no need to use an SSD for the -2 (without that option, it defaults to the same location as the first folder), I just use the ramdisk for both, then the final plot goes onto an NVME buffer, before then getting copied across my network to fill my full node server.

I have done quite a bit of testing of various configurations (thread count, memory size, different types and speeds of storage for the different stages, different start times and command options etc.) and with these machines I am getting 4 plots running at a time each, so 8 in total using optimised start timing generating slightly over 29 plots in total in 24 hours.

Regarding your bare minimum, I have 675TB of SAS disk shelves connected to an older but still reasonable Quad CPU file server that runs the full node. I only use a single 1TB SSD in each of the plotting machines as a simple buffer between the fast RAM and slow network transfer so it will last a long time before I need to replace it.

Of the nearly 400 plots I've created only a few have faulted due to the bug that I have reported here, but it is a big enough number to show there is something going wrong with malloc() somewhere in the process.

**Comment by kkovachki** [comment]
@racergoodwin - I have faced the same issue and the only way to fix it is by adding in the crontab -
*/20 * * * * sync; echo 3 > /proc/sys/vm/drop_caches 
to drop cache, also you can try to remount mount points with the following changes, depending on the FS
 mount -o remount,noatime,nobarrier

**Comment by racergoodwin** [comment]
@kkovachki - Thanks for the suggestions.

I've closely watched/logged the cache usage in the memory information and tmpfs expands and contracts as required. Even if the caches weren't being flushed/dropped as needed, they will move to swap as a last resort, but I have always got at least 50GB free and swap has never been touched. I will certainly keep that as a thing to try though if it ever stops working properly, thanks.

noatime is probably a good idea, though it isn't anywhere near as bad as it used to be back before relatime became the default.

I'm not sure, but I think nobarrier was never relevant for tmpfs and reading the [manpage for mount in 20.04](http://manpages.ubuntu.com/manpages/focal/en/man8/mount.8.html) it has been deprecated in all file systems apart from resierfs.
