### ISSUE TITLE
mining is not credited to the balance, but sent

### ISSUE THREAD

**Issue by Alikadiev** [Chia-Network/chia-blockchain#6086]
Hello. chia were sent to my wallet balance but not credited. Accrual did not occur. Mining accrual. It is not in the wallet, but I can see that it was in the inbox. I do not understand why this is so.

xch16ugv58tuzhaajjvyawnx9hw5k00tdhdfj9fhtypxc6vu3hdqnxqscqvaq6

![221](https://user-images.githubusercontent.com/19627389/119748389-81196480-be9d-11eb-966c-32ed4d0dcd7f.jpg)

**Comment by tangdasan** [comment]
I have the same problem, suddenly two more income, but not my address

**Comment by kugewang2022** [comment]
same here

**Comment by lvpcguru** [comment]
@Alikadiev How can anyone assist if you dont provide the full bug report information? Version OS sync status and logs are all needed to actually take a look...

**Comment by Alikadiev** [comment]
> @Alikadiev How can anyone assist if you dont provide the full bug report information? Version OS sync status and logs are all needed to actually take a look...

Are you seriously? what does this have to do with the chia blockchain? transactions do not take place at my home. They are online. It doesn't matter what version I have or the model of my pc

**Comment by Alikadiev** [comment]
if this is so important to you. windows 10 at home. chia 1.1.5 at that time. full synchronization of course.

**Comment by lvpcguru** [comment]
Thanks,

It really does matter. And no, your local machine, daemons and client all
participate in the transaction with the online network. Chia is distributed
and you are as much a part of everyone else's transactions as they are of
yours. this is not paypal.

Also that information really matters because it is an entirely new toolset
and the GUI in particular is really buggy and issues can be OS spesific as
its cross platform. The version you are running 1.1.5 has some syncing
issues that could cause this and version 1.1.6 along with those fixes
updates some of the way the transactions are shown.

However I believe the display total issue may be caused by you having
multiple receive addresses.  The gui totals them incorrectly and has also
been known(in older versions) to send duplicate transfers on the other
addresses if you try to send with your client.

I recommend:
   - updating to 1.1.6
   - trying CLI commands for the wallet to verify your totals and not trust
the GUI until it's stable.

**Comment by fengyezhiwu** [comment]
same here, I can see they are transferred in chia explorer, but I can't see it in my wallet even it shows "sycned"
