### ISSUE TITLE
[BUG] debug.log shows trying to ban localhost

### ISSUE THREAD

**Issue by fusionfoto** [Chia-Network/chia-blockchain#6239]
**Describe the bug**

2021-05-30T11:43:20.234 full_node full_node_server        : WARNING  Trying to ban localhost for 10, but will not ban
2021-05-30T11:53:20.834 full_node full_node_server        : ERROR    Exception:  <class 'asyncio.exceptions.TimeoutError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "/home/ubuntu/chia-blockchain/chia/server/server.py", line 531, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

This may be cosmetic on Ubuntu 20.04LTS, but it seems problematic... particularly with async io timing out.  This is running the latest (as of yesterday) chia. The node sync'd last night and then was out of sync at 10am EDT this morning. ... even with 80+ full node peers.

**Comment by room101-dev** [comment]
SInce 1-2 weeks ago the core code now bans a node if they 'chia plots check' takes over 5 seconds, 
WHAT hhd interface you using for plots?

U can no longer use usb, or lan network, the hdd must be physically on the mobo to mine chia plots with the new software 

HPOOL put out this notice two weeks ago, that it was out of their control, that CHIA-NET pulled this new rule out of their arse, before this we had no time-outs or banning, now they have gone ban-crazy

Best to fall back, last working core code was version 1.3

...

Syncing has always been a problem, even at best I used to see chia lose sync 20% of the time daily, both node & wallet, which are different process, but both must sync. Both have their own database

My solution is to make plots with plotter 1.3, and then mine my plots on HPOOL, now I never have a problem.

I tried for months to get the shit-ware aka chia-net to work, they released it to early, its full of bugs, and only gotten worse since main-net release.

**Comment by fusionfoto** [comment]
Interesting... the files are connected via 10G NFS... they easily read in under a few ms much less 5seconds.

Is plotting with 1.3 faster than 1.6? My 1.6 plots are mostly ok.

I just took a glance at HPOOL but haven't watch the YT on it yet. Will I have to respin my plots or can I use my existing keys?
