### ISSUE TITLE
[BUG] - Received XCH Reward & It Disappeared. Please Help.

### ISSUE THREAD

**Issue by LiuKang6** [Chia-Network/chia-blockchain#6286]
Hey everyone,

I had some issues with the rewards. As you can see in the picture i should have received 4 rewards. The 3rd (0,25) and 4th (1,75) were the first ones, i received both well, it was 2 XCH in total. I made a transaction of 0.5 XCH to another wallet and let the remaining 1.5 XCH in the Chia wallet. 2 Days later i received the 2nd reward which was 1,7489 XCH and it was added to my 1.5 XCH so new balance was: 3,2489 XCH. 
I was happy and confused and asked myself why the 1st reward of 1,24889 was not added to the balance as i have won them at the same time. Somehow the next day the reward disappeared and the 1,7489 was deducted from the total balance of 3,2489 XCH and i had the remaining 1,5 XCH left which i transfered yesterday (1st line) and i never received the first reward of 1,24889. I realy hope there is a possibility to reclaim back the rewards. Lesson learned: as soon as you see you have XCH farmed, quickly transfer it to another XCH wallet!

I appreciate all the help i will get. God bless you all.

![XCH problem1](https://user-images.githubusercontent.com/85136813/120247253-26a04f80-c273-11eb-8337-3bdc8799322f.jpg)

**Comment by tiny0little** [comment]
try to research on [chiaexplorer.com](https://www.chiaexplorer.com/)
or post your receiving address, I'll look

**Comment by room101-dev** [comment]
Like U said, don't leave XCH around, U don't by any chance run any 3rd party tool? Like plot-ware, or the 10K shit-wares for chia?

**"chia keys show --mneumonic"** dumps the key(s) via rpc, virtually every 'free program' for chia, is sending home the keys; Thus its not surprising they get swept as soon you see it,

Couple rules, delete all wallet files on your systems that are plotting, and of course NEVER run SW from 'friends of chia'

**Comment by 24601** [comment]
This is not a bug. This is user error and failure to follow published best practice (sorry if this sounds harsh, I don't mean it that way, but it is factual). 

Always, always, always have your rewards to *straight* to an address that is cold storage and was generated on a machine that was only ever connected to the internet *before* key generation and never is connected again (until a proper wipe, at least). 

The feature to forward farming rewards to another address has been in the GUI and the CLI for quite some time now (well before mainnet). 

https://www.chia.net/2021/05/28/securing-your-chia-how-to-be-a-hard-target.en.html

@room101-dev - I see your tongue in your cheek, but the official chia docs/blog are very clear about how to avoid this, I don't think it's intentional or even careless on the part of Chia Network, it's careless users who don't know better because they didn't take the time to read the docs. I don't expect everyone to be an INFOSEC expert let alone on new tech, but when it's well documented, it is a reasonable expectation that the users RTFM. 

I mean the link above literally says:

"Your XCH is only as secure as your wallet.

If your Chia wallet is not accessible electronically, then it becomes incredibly difficult to compromise and steal (basically impossible). We urge you to store your XCH in a cold wallet.

In broad strokes: You will create a wallet through a new 24 word mnemonic key on a secured computer not connected to the internet. Store the key in a safe place, like a safe, and not in a computer. You will set your XCH receive address to the wallet address associated with this new mnemonic key that’s in cold storage.

Some methods of cold wallet storage include:

writing your key on paper and storing it in a vault
using a metal wallet, where you press your key into pieces of metal
hardware wallets that are basically USB drives that store your key
One way of utilizing wallets in a safe way is this: Most of your XCH is stored in a cold wallet. You then have an accessible wallet (also known as a hot wallet) where you store a little bit of XCH for spending as you need it"
