### ISSUE TITLE
[BUG] github branch "latest" still points at release 1.1.6 

### ISSUE THREAD

**Issue by m4tt075** [Chia-Network/chia-blockchain#6516]
**Describe the bug**
The official upgrade instructions for Ubuntu/Linux do not allow us to upgrade to the latest 1.1.7 release

**To Reproduce**
Executing...
```
git fetch
git checkout latest
git reset --hard FETCH_HEAD
```
...will produce `HEAD is now at 9e9097b1 Chia Blockchian 1.1.6 (#5644)`

**Expected behavior**
HEAD should reference 1.1.7 version.

**Screenshots**
N/A
**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Debian
- CPU: Intel something (doesn't matter)

**Additional context**
N/A

**Comment by rizlah** [comment]
i noticed this too, however i then went back to the main page and it says 1.1.7 for windows and Mac, so I had assumed that the new release was only for those OSs.  On the other hand when you go to the manual download page for 1.1.7 there is an ubuntu 1.1.7, i have no idea how to install it from there.

**Comment by rizlah** [comment]
I just got it working my after . ./activate use the following command "pip install chia-blockchain==1.1.7"

**Comment by Fexiven** [comment]
use `git checkout 1.1.7` and skip `git reset --hard FETCH_HEAD`

**Comment by txr13** [comment]
Duplicate of #6497.

**Comment by djdookie** [comment]
This branch is 5 commits ahead, 30 commits behind main. 
https://github.com/Chia-Network/chia-blockchain/tree/batch_sql_1.1.6

"batch_sql_1.1.6" ist not merged into "main" or "latest" yet, but lot of previous changes and improvements from "main" are also missing in "batch_sql_1.1.6".
So I'll stick to the "main" branch with my Ubuntu farmer until "latest" is updated, because changes seem to primarily hotfix Windows problems as far as I can see.

**Comment by djdookie** [comment]
It seems we at least got the fix on the main branch now:
https://github.com/Chia-Network/chia-blockchain/commit/8946029bbc7d2ff8d747bdecb976a1fa6fc65723
