### ISSUE TITLE
[BUG] Connecting to wallet after upgrade to 1.1.7

### ISSUE THREAD

**Issue by bigvovan** [Chia-Network/chia-blockchain#6595]
Connecting to wallet after upgrade from 1.1.6 to 1.1.7 !

- OS: Win 7

- CPU: [Intel Xeon E31240]

**Comment by KeyserSoze407** [comment]
Same problem, everything has synced. windows gui, node sync at 400,000 and wallet synced days later. After upgrading to 1.17 my 2 xch are GONE. But on chia explorer it still shows in my wallet address and says unspent. Everything synced passed block height etc, I have backup of old database folders but have not tried anything yet in hopes it would find it. But it has been days, and consequently the price dropped in half and I had no access to my coins to sell them at a higher price. PERFECT timing for this *bug*. Would really love to fix it before chia goes to 1 dollar. (obviously being facetious but you can all see how frustrating this problem is, and evidently I’m not the only person having it. Win 7 3950x amd 16 core

**Comment by bigvovan** [comment]
ALARM!!!!!!!!!!!
![image](https://user-images.githubusercontent.com/7887236/121167991-239cf480-c85b-11eb-9101-956547997152.png)
Where is my money?!!!
Where did my coins go? !!!

**Comment by KeyserSoze407** [comment]
I was just about to do what you were saying to do, I woke up, tried to close out of chia and force restart it again to see if that would help. It wouldn't restart. I went in, deleted all of the chia processes in task manager, tried again and it loaded and showed my xch. Thank god. Too bad it's a day too late but way better than not ever having it.

**Comment by bigvovan** [comment]
bug 1.2.2 !!!!
