### ISSUE TITLE
Wallets are not syncing - Bug or Feature?

### ISSUE THREAD

**Issue by Nico-VanHaaster** [Chia-Network/chia-blockchain#6596]
**Describe the bug**
We are running headless Nodes (without a GUI) and for the past 3 days the wallet has not fully sync'd. 

Currently running of the may pools branch.

Can this system actually be run headless? If I run it with the UI the wallet will sync but only if the UI is currently signed into that key. 

This system should sync all wallets regardless of which key is selected and regardless if there is a UI

**Comment by Gnomuz** [comment]
Wallets get synced there, also running headless (ubuntu server) on pools.2021-may-25 branch.
The issue is only one wallet gets synced at a time. So, you have to type 'chia wallet show -f XXX' and wait to get the relevant wallet synced (that can be quite long). Meanwhile, the wallet associated with fingerprint YYY gets out of sync. To get it synced, you need to type 'chia wallet show -f YYY'. And so on, and so forth... And in the end, if you have two or more wallets on a single rig, they can't be all synced at a given time.
So, it's just a workaround, and I think we all hope that a more robust and elegant solution will be implemented shortly !

**Comment by Nico-VanHaaster** [comment]
@Gnomuz are you running these on Docker \ Kubernetes or on baremetal? Also have you forwarded any ports. I have done as you said and over the past 5 hours there has not been a single change to the wallet.

In the logs I have alot of these message:

2021-06-08T23:32:06.989 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 17467-17499. Traceback (most recent call last):
  File "/chia-blockchain/chia/wallet/wallet_node.py", line 522, in sync_job
    await self._sync()
  File "/chia-blockchain/chia/wallet/wallet_node.py", line 621, in _sync
    raise RuntimeError(f"Was not able to add blocks {start_height}-{end_height}")
RuntimeError: Was not able to add blocks 17467-17499

**Comment by jadechip** [comment]
Same here, running in k8 👆
