### ISSUE TITLE
[BUG] install_gui.sh will fail on ubuntu when nodejs is already installed

### ISSUE THREAD

**Issue by guttenberger** [Chia-Network/chia-blockchain#661]
**Describe the bug**
install_gui.sh script will fail on ubuntu and terminate when node js is already installed. 

**To Reproduce**

1. Install nodejs via 'sudo apt install nodejs'
2. Follow [install instructions ](https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian)

>libxss1 is already the newest version (1:1.2.2-1).
nodejs is already the newest version (12.20.1-1nodesource1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 nodejs : Conflicts: npm
E: Unable to correct problems, you have held broken packages.

**Expected behavior**
install_gui.sh should be executed succesfully

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04.5 LTS

**Comment by guttenberger** [comment]
I going to close this since it is related to apt
https://askubuntu.com/questions/1057737/ubuntu-18-04-lts-server-npm-depends-node-gyp-0-10-9-but-it-is-not-going

**Comment by fatalerrortan** [comment]
@guttenberger Great Job!

**Comment by lordrip** [comment]
Hi, sorry for commenting in a closed issue, but, since `npm` comes alongside `nodejs`, couldn't we removed from the `install-gui.sh` script?

**Comment by gilMotta1** [comment]
I got the same issue then I opened the bash file install-gui.sh and saw that the line that is failing is the following:

`sudo apt-get install -y npm nodejs libxss1`

I made sure that npme, nodejs and libxss1 were installed and they were.

npm version 6.14.13
nodejs version 8.10.0
libxss1 version 1:1.2.2-1

I commented out the line above and ran the install-gui.sh again

It installed other dependencies and then when the script was complete; I ran npm run electron &

and it worked! the Chai UI came up and I was able to transfer my keys.

I still don't know what the problem is with the npm and nodejs but Chia should skip installing them, if they are installed already.
