### ISSUE TITLE
[BUG]farmer asyncio: ERROR    Exception in callback BaseSelectorEventLoop._read_from_self()

### ISSUE THREAD

**Issue by wbkys** [Chia-Network/chia-blockchain#6637]
version: 1.1.6-1.1.7

**Describe the bug**
Wallet synchronization is normal
Block synchronization is normal
But the log(mainnet\log\debug.log) shows the error:

2021-06-09T19:17:32.429 farmer asyncio   ERROR    Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "asyncio\events.py", line 88, in _run
  File "asyncio\selector_events.py", line 119, in _read_from_self
ConnectionResetError: [WinError 10054] Remote host is forced to turn off an existing connection.

**To Reproduce**
Normal start

**Desktop (please complete the following information):**

- OS: Windows pro win 10 - 1909
![image](https://user-images.githubusercontent.com/12574291/121347442-c8056080-c959-11eb-870f-12e27f91640a.png)

![image](https://user-images.githubusercontent.com/12574291/121347471-d18ec880-c959-11eb-8eef-4d6e01b0b9b3.png)

**Comment by akloud** [comment]
I can confirm this issue! Can I somehow influence priority? By spamming the debug.log like that, deeper insights into your node are prevented.
This issue is not present directly after reboot, but the behaviour starts after some time. The writing of thr message if with high frequency, e.g.:
`
2021-06-18T05:27:12.851 farmer asyncio                    : ERROR    Exception in callback BaseSelectorEventLoop._read_from_self()
2021-06-18T05:27:12.853 farmer asyncio                    : ERROR    Exception in callback BaseSelectorEventLoop._read_from_self()
2021-06-18T05:27:12.854 farmer asyncio                    : ERROR    Exception in callback BaseSelectorEventLoop._read_from_self()
2021-06-18T05:27:12.856 daemon asyncio                    : ERROR    Exception in callback BaseSelectorEventLoop._read_from_self()
2021-06-18T05:27:12.857 daemon asyncio                    : ERROR    Exception in callback BaseSelectorEventLoop._read_from_self()
`
_(Everything besides timestamps removed...)_

**Comment by wbkys** [comment]
Yes, it is. So, does it affect the harvester?

**Comment by wbkys** [comment]
https://github.com/Chia-Network/chia-blockchain/issues/6637#issuecomment-863728609

> I can confirm this issue! Can I somehow influence priority? By spamming the debug.log like that, deeper insights into your node are prevented.
> This issue is not present directly after reboot, but the behaviour starts after some time. The writing of thr message if with high frequency, e.g.:
> `2021-06-18T05:27:12.851 farmer asyncio : ERROR Exception in callback BaseSelectorEventLoop._read_from_self() 2021-06-18T05:27:12.853 farmer asyncio : ERROR Exception in callback BaseSelectorEventLoop._read_from_self() 2021-06-18T05:27:12.854 farmer asyncio : ERROR Exception in callback BaseSelectorEventLoop._read_from_self() 2021-06-18T05:27:12.856 daemon asyncio : ERROR Exception in callback BaseSelectorEventLoop._read_from_self() 2021-06-18T05:27:12.857 daemon asyncio : ERROR Exception in callback BaseSelectorEventLoop._read_from_self()`
> _(Everything besides timestamps removed...)_

Yes, it is. So, does it affect the harvester?

**Comment by akloud** [comment]
![grafik](https://user-images.githubusercontent.com/10213734/122539015-6dd66080-d027-11eb-9871-f9efcfe659ff.png)

Everything looks green, but since I have no clue about the internals, I as a software developer would say that you cannot really tell. Since everything is spammed, I cannot really tell if e.g. my USB HDD is too slow and that is why no proof was found in my plots that far.

**Comment by akloud** [comment]
Is there any possibility to modify the log level? I would prever to suppress the debug logs and just concentrate on the warnings/infos telling me much more about my system.

**Comment by 1002753959** [comment]
I also have this problem. Even when I disconnect from the network and use standalone mode, this situation still occurs. At the beginning, there is no error message, but after running for a period of time, the error message suddenly appears and the program freezes. I am using Python version 3.10
