### ISSUE TITLE
[BUG] Is it possible to cheat to get coins through fast plot technology?

### ISSUE THREAD

**Issue by benqwu** [Chia-Network/chia-blockchain#6710]
If someone can use challenge hash as input and plot a file in a very short period of time (such as using GPU for plot, less than 30s), can he get coins?

**Comment by gromran** [comment]
Plotting is only part of it. You also need HDD space for the plots. And then lucky that one of your plots has a proof

**Comment by WyattLiu** [comment]
This is stated in the white paper and it is a key to make chia successful, basically, if we do not have VDFs, simple PoSpace has a trade-off of sqrt(space) and sqrt(cpu time). However, VDF brings that impossible and caused huge players to be unhappy about it because the HW they have is not very useful.

**Comment by Kikicaj** [comment]
you would need few things: an (1) AI system learning on top of already won blocks (hpool gets the most chances here) that could learn potential answer to the challenges, (2a) farmer / harvester hacks that instead of asking plots for response would ask the AI system for response    OR   (2b)   a couple of friendly connected full nodes chain that could prove the fake proof for the blockchain .... i bet hacking a solution is a matter of year or two (knowing the AI brand, not hacking... dont get me wrong :) )

**Comment by emlowe** [comment]
Closing issue as this is not a defect
