### ISSUE TITLE
Banning [IP] for 10 seconds and Invalid plot header magic

### ISSUE THREAD

**Issue by uxrobinson** [Chia-Network/chia-blockchain#6913]
**Describe the bug**
I am seeing this repeated in the log. An IP that is being banned for 10 seconds, followed by Invalid plot header magic relating to a single plot. I am wondering if this is blocking anything relating to proof and rewards?

**To Reproduce**
Running dev version on Mac Mini M1

**Comment by Elyasin** [comment]
This is a very good question. Unfortunately it takes a long time to get an answer in my experience and there is no list of explanation of log messages somewhere to find.

I see these messages too and read about other users who see these messages also.

As far as I can see there is usually no issue with this message. Some IP address was banned for some time for some reason. That is all it says. Not sure what the cause is. I cannot make assumptions about the intent, I tend to say that there is no malicious intent behind that log output.

I would consider relabeling this issue. I don't think it is a bug, it is simply a Warning Level Log output to inform about what the system does.

**Comment by mariano54** [comment]
See the log reference:
https://github.com/Chia-Network/chia-blockchain/wiki/Logging-Messages-Reference

I agree it's probably not an issue. If it's your harvester or farmer getting disconnected from your node, I recommend you check out that plot, you might have a faulty plot. You can confirm this with `chia plots check`.
