### ISSUE TITLE
stuck on "connecting to wallet" startup page for hours now

### ISSUE THREAD

**Issue by soderpop** [Chia-Network/chia-blockchain#694]
not sure whats up with that

**Comment by Kaal1990** [comment]
Do you have soome more informations about your hardware?
Which OS do you use and more?
Because i have the same problem yesterday at the same time whit my Raspbian 64bit OS. I stuck on "connect to wallet" for hours and think that was a problem of my build. But if you have the same problem, maybe its not a problem of us.

**Comment by wallentx** [comment]
@soderpop I noticed this with the latest 1.0b21.
Try to pull down the latest release, blow away venv, and reinstall. Then run `chia configure --enable-upnp True` and see if it works.

**Comment by hoffmang9** [comment]
If you're stuck "Connecting to wallet" for more than a minute or two, you'll need to delete your wallet database. See Item 6 here: https://github.com/Chia-Network/chia-blockchain/wiki/Windows-Tips
