### ISSUE TITLE
After clean reinstall chia client 0 ballance and 0 win[BUG]

### ISSUE THREAD

**Issue by gnukleus** [Chia-Network/chia-blockchain#7003]
Go to uninstall chia Latest Version: 1.1.7 - 2021-06-06, delete chia default folder. Then install and full sync.
I had something like 0.00000045XCH and I won a 2 xch

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:Windows 10 
- OS Version build: 19042.1052
- CPU: AMD 5800x

![image](https://user-images.githubusercontent.com/83652452/123558654-bdd7c480-d797-11eb-94fb-1b1f00f8318e.png)

**Comment by gnukleus** [comment]
![image](https://user-images.githubusercontent.com/83652452/123558669-cc25e080-d797-11eb-9372-1ece2fcb7eb1.png)

**Comment by gnukleus** [comment]
![image](https://user-images.githubusercontent.com/83652452/123558677-d5af4880-d797-11eb-897b-572631ded45c.png)

**Comment by gnukleus** [comment]
My address xch1d4f0y7tm2ux8z7xk5tzj6legx7dvxssh4m7m3z9xrsp5may4nxgqz363vd

**Comment by stevenvegar** [comment]
Hi gnukleus, this happends because your wallet information within the chia client you installed is not synchonized. You have already synchonized the chia node, but not the wallet, so you can't see your earnings there. It doesn't mean your coins have disappear.

You can check chiaexplorer to see your wallet information:
https://www.chiaexplorer.com/blockchain/address/xch1d4f0y7tm2ux8z7xk5tzj6legx7dvxssh4m7m3z9xrsp5may4nxgqz363vd

There you can see the first transaction your wallet had, this was registered on the height 278.843, but, if you pay attention on your wallet syncronization (the first screenshot attached) it is syncing the height 226.878.

So, let the chia client finish to sync the wallet info and you'll see your complete wallet content. Don't worry, it's a matter of time.

It's not a bug, it's lack of sync.

**Comment by mariano54** [comment]
That is correct, thank you for the comment @stevenvegar
