### ISSUE TITLE
[BUG]Warning such as below frequently:

### ISSUE THREAD

**Issue by jamescjw** [Chia-Network/chia-blockchain#7034]
Warning such as below frequently:
Looking up qualities on V:\plot-k32-2021-06-06-04-55-f2011be3f2a8bddcc2c7a785c4a148234941fd032e593c3fb704c94c8200df62.plot took: 8.77606987953186. This should be below 5 seconds to minimize risk of losing rewards.

Harddisk's status is good and the harddisk temperture also low...

how to reslove this warning?Any one knows?! Thank you!!

**Comment by pangchia** [comment]
have same issue

**Comment by mariano54** [comment]
You might have a very slow hard drive. I suggest disconnecting hard drives and see which one has the issue. If you are on a NAS, that might also cause issues.

**Comment by joelrb** [comment]
Keep your disks awake. Or wake them up every 2 seconds. That solved my problem with below 5 secs. I'm using a mac mini as my main farmer and I installed the Amphitamine app to keep alive the disks.  My other harvester machines are installed with Ubuntu and I keep the disks awake too. I didn't have such issue since. I have both internal disks and external disks connected via USB port.

**Comment by jamescjw** [comment]
> Keep your disks awake. Or wake them up every 2 seconds. That solved my problem with below 5 secs. I'm using a mac mini as my main farmer and I installed the Amphitamine app to keep alive the disks (2 seconds check). My other harvester machines are installed with Ubuntu and I keep the disks awake too. I didn't have such issue since. I have both internal disks and external disks connected via USB port.

thank you for your suggestion , i will try it soon.
