### ISSUE TITLE
[BUG] Node status Not synced

### ISSUE THREAD

**Issue by krispipeleers** [Chia-Network/chia-blockchain#705]
Having this issue where note status remains Not synced. Height keeps going up, but node status is still saying Not synced.
Connection status = connected
Farm status = wait for synchronization

OS: Win10
node 12.13.0
Chia 0.1.20

Tried to uninstall, deleted the 2 folders, re-installed without success.

**Comment by krispipeleers** [comment]
In the meantime upgraded to Chia 0.1.21

**Comment by krispipeleers** [comment]
Still the same problem after following the instructions on Reddit https://www.reddit.com/r/chia/comments/kz5lwp/chia_network_beta_21/

**Comment by krispipeleers** [comment]
After another hour or 2 it is fully synced.

**Comment by dorkmo** [comment]
It just slowly synced finally? im still having the same issue. on windows 21 and ubunutu 21 also

**Comment by hoffmang9** [comment]
Node has performance issues related to the handful of transactions stuck in the mempool plus the wallet being mostly broken. You can try `chia stop wallet-only` to help. We know what's wrong, but it's a long weekend. Beta 22 will be soon.

**Comment by krispipeleers** [comment]
> It just slowly synced finally? im still having the same issue. on windows 21 and ubunutu 21 also

Indeed after 2 hours (after downloading the database), it caught up and timestamp of block and status look good now.

**Comment by dorkmo** [comment]
its funny, my node keeps adding blocks, but its doing it slower that they are being created. slowly become further and further out of sync.

**Comment by krispipeleers** [comment]
> its funny, my node keeps adding blocks, but its doing it slower that they are being created. slowly become further and further out of sync.

It worked fine yesterday, but indeed started to slow down this morning. I'm on block 31021 now. I saw Gene's note that with beta 22 this should be resolved. So waiting.

**Comment by dorkmo** [comment]
today i updated to beta 22 on ubunutu, sorta had the same issue. The node connected, then successfully synced with the network. It was synced for a few blocks, then the machine won a farming award. Then it slowly began falling behind from the network again. After a few hours of losing sync, the peak time is about 40 minutes behind the network.

**Comment by krispipeleers** [comment]
Syncing is

**Comment by dorkmo** [comment]
i restarted my system and am back in sync. seeing some unfinished blocks again. won a block again, still in sync. ill keep an eye on it.

**Comment by dorkmo** [comment]
it ran a little longer that time, but im out of sync again.

**Comment by krispipeleers** [comment]
I'm plotting so cannot restart :)

**Comment by dorkmo** [comment]
i feel ya! i got a rasberrypi 400 desktop a few weeks ago. running ubuntu gui on there just for farming and node. running windows 10 on my gaming pc where ive been plotting on external drives. I just shut down the node .exe after the gui boots.

i restarted my node system again and im staying synced once again. seems to be running much longer now.

**Comment by krispipeleers** [comment]
Sorry but stuck again after syncing for an hour. Let me know if you need anything to further analyze.

**Comment by GBourb** [comment]
Same here. My system stop syncing at random time. Did reboot now i'm at 131222/134705
Connection status still connected.

**Comment by mariano54** [comment]
Can you try on beta23? There were some large improvements regarding syncing.

**Comment by krispipeleers** [comment]
Beta 23 is got stuck multiple times today. Restarting the app solved the problem each time. Let me know if I can send you additional information to analyze if needed!

**Comment by Erni** [comment]
Same here. I am with version 0.1.26:
![image](https://user-images.githubusercontent.com/725315/108045659-0215c400-7044-11eb-9a67-b32a5dcfcdc9.png)
And the Status shows as `Not Synced`:
![image](https://user-images.githubusercontent.com/725315/108045824-325d6280-7044-11eb-8612-335d3f2a9980.png)
I have tries to reload and restart the application but it remains like that. I will leave the application open for a few hours and check.

**Comment by hoffmang9** [comment]
The Beta 26 chain died a couple of days ago. Upgrade to beta 27 and things will be much better.

**Comment by Erni** [comment]
thanks @hoffmang9 . I just upgraded to `0.1.27` and started Syncing from the beginning. Let´s see how it goes.
![image](https://user-images.githubusercontent.com/725315/108047053-a4827700-7045-11eb-923a-e0449afe9360.png)

**Comment by beykovskyb** [comment]
@Erni how did you restart syncing from the begining? is there a way to do it manually?

**Comment by hoffmang9** [comment]
You can delete your wallet database in `~/.chia/VERSION/wallet/db`

The Beta 27 chain is likely to be dead very shortly and everyone should upgrade to RC-2

**Comment by coding-horror** [comment]
Per comments above, I 

- closed the client
- downloaded latest client
- installed it

Now it is syncing, so that solution (basically, close, upgrade to latest, re-launch) seems to work!

**Comment by hesen2006cn** [comment]
(venv) [uchia@localhost ~]$ chia show -s
Current Blockchain Status: Full Node syncing to block 194826 
Currently synced to block: 12242
Current Blockchain Status: Not Synced. Peak height: 12242
      Time: Sun Mar 21 2021 19:52:35 EDT                  Height:      12242

Estimated network space: 124.196 PiB
Current difficulty: 8
Current VDF sub_slot_iters: 112197632
Total iterations since the start of the blockchain: 39003237584

  Height: |   Hash:
    12242 | e4f9b8859d1cd9cc530b864c5e70c6f3edcd2d99c85a8a8ad51cab22f9a633c6
    12241 | 5a436455a8d14d978f3b2e98a8a442f6e394c997a16a51c6671a8394f79f8c5b
    12240 | e78575fa4a373bb857d0b45717cefe60e43148900308e7137358acbe2b554118
    12239 | fb0b779ff70a42d9e7f948ad49b7e622fa0eb24f470ea434031a2e1784af6ebc
    12238 | 24f04f1ae90851302e1a4071c071eefe4a0f842988d71998dc4f5c6482517491
    12237 | 4c196d69a954d90821cf1948b2bd72126d751c66126362bab76129ca1aaa6936
    12236 | 65aa7dcd09fd5a047ee8add2b65a3a6e464960f2fc11c2e6b149f37ae1389774
    12235 | edf0f478014c4629e30ac3e3418943baa6118fa6faffde8b4aa3b26a3e4b7f3a
    12234 | 9f3cf54ab39dfaa04745754bde88c8308a0f4ca71fa470cc4c3a5ace0f4e2df0
    12233 | beea424ee291f03270ce6e186da7e9557d9de3e41d2c41f459d5029ac1bc0017
(venv) [uchia@localhost ~]$ chia farm summary



my system: centos7.9  chia-v1.1.2

**Comment by totaldev** [comment]
Debian 10.

$ chia version
1.1.2.dev41

$ chia show -s
Current Blockchain Status: Not Synced. Peak height: 199075
      Time: Wed Apr 28 2021 18:45:35 MSK                  Height:     199075

Estimated network space: 968.155 PiB
Current difficulty: 56
Current VDF sub_slot_iters: 99614720
Total iterations since the start of the blockchain: 653378065998

  Height: |   Hash:
   199075 | d5bb6d79cc2043acf77f81813fcde1008f437801728ad605ce05df0d883f043b
   199074 | 968aa4c66b2a85c10605922d937be6da34c21d0eb6891e795646d07d8b44c231
   199073 | 6e26a81e13c6ff54817f4850ec9bcd089938a293048cffe25224189a256f8a2b
   199072 | 05566dddc784acdb7e51b20c2a4687dbc60384c6c80117bb9666031679413b98
   199071 | 1f28630c139b4bcafc48576a9f862377d15a41b25ecb1bb27f850ef98b1a95c4
   199070 | e7208563d5d95f88580bb830f317f853e7aed8132b9f1220e6329d1680442405
   199069 | b2fdc683698723b6df73836c05dcf319c6ce37ce2442587182f7bbb4886a667b
   199068 | 2faf73b6226d6294e28a68208a0851dd209c2555eaa0ea501a66c3474a8867f9
   199067 | 835efc336f79a24b8f94829eb634c4cdbe44441ae1c39d9aa908fca7a6a39913
   199066 | 3f9258d99b563022e2fec594a079698c18352196f5c5e2046020c1df06e6b065

**Comment by shobukle** [comment]
This appears to still be an issue. Why is it closed?

```
$ chia version
1.1.5.dev0
$ chia show -s
Current Blockchain Status: Not Synced. Peak height: 249513
      Time: Sat May 08 2021 09:22:47 UTC                  Height:     249513

Estimated network space: 2.852 EiB
Current difficulty: 197
Current VDF sub_slot_iters: 111149056
Total iterations since the start of the blockchain: 807887958018

  Height: |   Hash:
   249513 | 964b6a8873eb5c49013cec90b7204803aedea3361002964a0f0c311366a885f5
   249512 | 0e40bee97480a4bb1f0f4376b987a970828830ca58186924b95336440064efbb
   249511 | afca3b7e726ab80e43c024193c04d1e45e33bbc0ad98ea9264987427fb0cd699

```

**Comment by LaFouine25** [comment]
i have the same issue. Any solution ?
`Current Blockchain Status: Full Node syncing to block 254550
Currently synced to block: 193536
Current Blockchain Status: Not Synced. Peak height: 193536
      Time: Tue Apr 27 2021 11:42:21 CEST                  Height:     193536

Estimated network space: 907.359 PiB
Current difficulty: 54
Current VDF sub_slot_iters: 110624768
Total iterations since the start of the blockchain: 635507339856

  Height: |   Hash:
   193536 | 85aa575df9e1569a8930e6162cf08514c00efbcd8a4cffc259b4f215c6ed570c
   193535 | 92254bd4886c86ec604fa0f0241816704fa4a1c64a11f12383db854ccaf9321c
   193534 | fb66324b32670627a154c80f27181af86e47c1ba1a36075cb6a6caab2e60584e
   193533 | 3a03e75feaf6c2d73deb187ab5571d91a4ad1e5819072b77b8554f629abc9a99
   193532 | 2c657226da5db848e986b6331dfff2c205a2ee7e8c80fe335dc4f8db92127615
   193531 | 58a27b69bfc98c7122ef6aa277450cc3b0d5c9deb1d70816d29b45573ef4130c
   193530 | 005bb7dc06f6a700862e720eccb683c7e1197cc3bed913b3e4a6ca93879ae195
   193529 | 84aca63df61980f5ba6fe5227deb770dcd609542c5992f258fa5b9d7b070c961
   193528 | 5b9c28735ceebb496987f3686bede7a58023a2c3566deda64d1135deebad6070
   193527 | bd0032ae671d873f399defe41edbb7137495b8a0af36a3cbcb5f964aa847de57
`

**Comment by phlanglois** [comment]
Hello there
Same issue on 1.1.3.
Plotting, but Sync lost for almost an hour.

Is there any way (logs?) to track sync activity?

```
 ~ % chia version
1.1.3
```

```
% chia show -s
Current Blockchain Status: Not Synced. Peak height: 255108
      Time: Sun May 09 2021 14:48:15 CEST                  Height:     255108

Estimated network space: 3.167 EiB
Current difficulty: 215
Current VDF sub_slot_iters: 110624768
Total iterations since the start of the blockchain: 825985294247

  Height: |   Hash:
   255108 | 426a2b5971b94dd8a5038e88763e37c78c44db3356cf700e9d64fae9236f120c
   255107 | 6ee7599a94ccd121d455af3661ca8fe33d393812fd5e9bd5c657bc0436324177
   255106 | be0f1bc5b16381c33d8283b7b01de72a87f5d4f589ffbe363fcfd3a35a66c854
   255105 | f14b093e1511e9febeb7c2f44d500d4e10f3ff4aeab419fdfbb2de6cba35c736
   255104 | 7822d6c2437f4a3622749cf4c0bf3101edeb95c21c24adabdf7aacd5b4864dc0
   255103 | 2583ee3b5ceefc87b1a538b6d0284de2dc29a1bddcfdaea066b4026716c7ba23
   255102 | b52183c5fa71616525c8890f019c3299c7ae0243924c5a8343ea7ccaf4b9edac
   255101 | 1e307559425c3bfa8eb3969d15054c97ebfb0e2053233a8a689a34cf392afeb7
   255100 | d89c8b1f673c4a4f1fa588cdf5ddfb0cfe27e8bafb0b28c208f0616409601899
   255099 | ec19431deaafe546fbac2255ff38a554a577f474035090cc2fa454aae427df26
```

**Comment by dimitri-razine** [comment]
Same issue on Windows on latest version. Happened after crash

**Comment by Zeesy** [comment]
Same issue. My PC is able to sync with some difficulty, my Pi isn't syncing at all. In May, PC had synced after a few hours. An issue that's come up in a few places is making sure that port 8444 is open. I'm behind a GCNAT, so port 8444 is open when my current (dynamic) IP is the same as my remote IP, but closed when my current IP is the same as my Pi. Port forwarding for 8444 is set to my Pi's IP.
Details for my Pi4:
raspbian 10 64-bit
chia v1.1.7

**chia show** is stuck in Not Synced (running for 24 hours):
```
Current Blockchain Status: Full Node syncing to block 470721
Currently synced to block: 121920
Current Blockchain Status: Not Synced. Peak height: 121920
      Time: Mon Apr 12 2021 23:26:57 EDT                  Height:     121920

Estimated network space: 285.021 PiB
Current difficulty: 20
Current VDF sub_slot_iters: 121634816
Total iterations since the start of the blockchain: 406913865410

  Height: |   Hash:
   121920 | b7322a358a53f72745cd5ded8a34531fa03c3c3ac9a906140731b73bcd40f951
   121919 | fcca881150a86e010bbcd7c7c2321c407cdccd9f23934f36b06ab64101bf7336
   121918 | 7bfe280b43d738d90662b907ef3c003d1bedb956d430440584bffd7521b0786e
```
**chia farm summary** Farming status stuck in Syncing:
```
Farming status: Syncing
Total chia farmed: 0.0
User transaction fees: 0.0
Block rewards: 0.0
Last height farmed: 0
Plot count: 0
Total size of plots: 0.000 GiB
Estimated network space: 285.118 PiB
Expected time to win: Unknown
```
