### ISSUE TITLE
[BUG] GUI plotting percentage issue 

### ISSUE THREAD

**Issue by baturman** [Chia-Network/chia-blockchain#7227]
When a plotting process starts, progress bar finishes (%100) before even phase 4 starts. Chia 1.2.0 version. 

**Desktop**
- OS: Linux
- Kubuntu 21.04
- CPU Intel Xeon e5-2678v3
- 128 GB Ram

**Additional context**
Plotting process is started with following params:

**Starting plotting progress into temporary dirs: /media/m2/tmp01 and /media/m2/tmp01
ID: b692854868fe04079a56fd52a69b3350bcbd90df75bc866db5ffda551c30a4f1
Plot size is: 32
Buffer size is: 5999MiB
Using 128 buckets
Final Directory is: /media/disks/wdpurple-p08/chia-farm-01
Using 4 threads of stripe size 65536
Process ID is: 10359**

![Screenshot_20210708_171415](https://user-images.githubusercontent.com/6068433/124939900-2d5c7800-e012-11eb-9c72-83e3f18b30bc.png)

**Comment by whgipt** [comment]
Same here on Windows

**Comment by scriper88** [comment]
Same on Mac.

**Comment by loppefaaret** [comment]
transferring this to `chia-blockchain-gui`

**Comment by sampellino** [comment]
Same on Windows. I have three plots that have been at 100% for hours. I've also noticed that my other plots' percentages move significantly faster after upgrading to 1.2.0, even though it's the same drive/cpu/ram configuration (presumably because the percentage calculation is bugged).

![image](https://user-images.githubusercontent.com/5458241/125067842-c4611880-e082-11eb-8d08-9b7825c8b22c.png)

**Comment by loppefaaret** [comment]
the progress bar calculation was changed - supposedly we tried to make them better - but didnt quite hit the spot and have to re-evaluate

**Comment by gregoriob** [comment]
Ditto to all of the above on windows. 
Initially the bar moves a lot quicker but 100% is reached before the end of phase 3 plots. I now also need to increase time between parallel plots so something is out with the plotter.
