### ISSUE TITLE
[BUG] loading plot NFTs

### ISSUE THREAD

**Issue by jakihong75** [Chia-Network/chia-blockchain#7361]
**Describe the bug**

**To Reproduce**

1. Go to 'pool tab.'

not load pool screen but compelete sync.
at 1.2 v
for the 24 h

plot tab have same error

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/39257561/125181877-22892980-e244-11eb-9174-78ec481c3b3d.png)

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by guntoro2001** [comment]
same case

**Comment by Lazymin3r** [comment]
I am having the same issues....
My wallet and Node are both synced to the same full height.
When I open up the pool to see my NFT Plots(solo mining) I get loading screen below.
![Plot NFT loading](https://user-images.githubusercontent.com/85452577/125368797-aa545e00-e340-11eb-9efa-f6f558768e8c.PNG)

I also can't see my regular plots in the farm or plot tabs.
![image](https://user-images.githubusercontent.com/85452577/125368855-c526d280-e340-11eb-8ec1-b2527c902275.png)
![image](https://user-images.githubusercontent.com/85452577/125368897-d4a61b80-e340-11eb-9d98-e1954a194638.png)

Running CHIA 1.2.0

Desktop

OS: Windows 10
OS Version/Flavor:  19042.1052
CPU: Intel Core-i5-7600k

**Comment by kihcl** [comment]
I am having the same issues. even if I reinstall it, the situation also exist.

Running CHIA 1.2.1

Desktop

OS: Windows 10
OS Version/Flavor: 19042.1083
CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz   3.19 GHz

**Comment by Lazymin3r** [comment]
I was able to fix my issue, not sure if it is the same for you but in my chia config file (usually found for windows under: C:\Users\username\.chia\mainnet\config, it is a config.yaml file, make sure CREATE A COPY of this file before making changes to it) I found that under the Key named xch_target_address: (easiest way to find is ctrl+F, please be aware you may have more than one Key named xch_target_address: and you need to update the address for both otherwise this will not work) I had "null" for the value of this key. I added my chia wallet address and got my miner working including my NFT plots. Below is one of the sections that I had to update. Hope this helps!



logging: *id001
min_mainnet_k_size: 32
network_overrides: *id002
outbound_rate_limit_percent: 30
ping_interval: 120
pool:
  logging: *id001
  network_overrides: *id002
  selected_network: mainnet
  xch_target_address: null(replace null with your key here)
private_ssl_ca:

**Comment by x134a** [comment]
Worked for me thank you

**Comment by heshelk2** [comment]
Where are you Brahm? and your team? YOU HAVE TO FIX ALL THE ISSUES THAT THE 1.2.3 VERS HAS

**Comment by ppsirius** [comment]
@Lazymin3r find the solution and bot closed this issue. Developers handling this project wtf?
