### ISSUE TITLE
I have over 40 drives and I feel like the GUI doesn't help with that[Request]

### ISSUE THREAD

**Issue by number435398** [Chia-Network/chia-blockchain#7383]
I think we need 2 things, a "check the root folder of all connected drives" button (so I don't have to manually add each one of the over 40 drives I have) as well as a list of "this folder has this many valid plots" list.  I have over 40 drives and after looking over it, there are well over 100 plots that aren't showing up in just plots or in "invalid plots".  I have no idea which are the case as the GUI doesn't help me with that at all.  If there was a list, I could see, per identified plot folder, that said how many, I could more easily discern the error in this situation.

**Comment by number435398** [comment]
This is still an issue.

**Comment by preto677** [comment]
i would love to see some grouping of drives instead of full list, or make it an option how user want to display drives.. I dont need to see list with all the plots all the time.. it would be enough if I saw list of drives with most important details like Label of that drive, how big is it, and how many valid plots is on that drive.. and only after clicking it, it would show a list with all plots from that drive

please do something with that :(
