### ISSUE TITLE
.chia/mainnet/db/blockhain_v1_mainnet.sqlite-wal is 67 GB [BUG]

### ISSUE THREAD

**Issue by aschueth** [Chia-Network/chia-blockchain#7431]
I left town for a few weeks and let my computer plot while I was gone. Upon returning, I had 0 bytes left on my C:/ which is on a small SSD. The issue turned out to be that .chia/mainnet/db/blockchain_v1_mainnet.sqlite-wal ballooned to 64.2 GB and .chia/mainnet/db/blockchain_v1_mainnet.sqlite is 6.64 GB. I restarted my computer thinking the cache files may be automatically deleted but that is not the case. I tried opening the chia GUI back up and it initially failed, throwing a disk/IO error. I cleared up some space on C:/ drive and tried again and it is syncing. The sqlite-wal file is getting larger with time while syncing, gaining 1370 bytes over 20 minutes.

First and foremost, I wanted to raise this as a bug. I, unfortunately, am unaware of what caused it since I was out of town. I am willing to share the logs if need be.

Second, I am wondering where to go from here and how to resolve this issue.The easiest solution would be to delete the files, but I am leary of doing that in case it corrupts my wallet or the chia program.

OS: Windows 10 v1909
CPU: INTEL CORE i7-6700k @ 4.00 GHz
RAM: 32 GB
CHIA: v1.1.7

**Comment by mariano54** [comment]
Yes it should not be this large. You can delete the wal file and restart your node.

**Comment by aschueth** [comment]
ok, good to know, and doing so shouldn't corrupt anything?

**Comment by mariano54** [comment]
nope

**Comment by aschueth** [comment]
After deleting just the wal file, I opened the GUI and every readout had a forever spinning loading icon (status, peaktime, difficulty, etc...). I left it overnight and it was still spinning the next morning. I uninstalled my CHIA 1.1.7 and downloaded and ran CHIA 1.2.1 and still had the same issue. I then moved my .chia folder to a different location and reopened the chia gui. I was able to use the same wallet but did not import any files from the directory I moved. As expected it created a new .chia directory and is now syncing. I didn't have any XCH, so it's no big loss, but I don't want the issue to happen again.

**Comment by emlowe** [comment]
The wal file is a sqlite write-ahead log - all transactions are first written to the WAL file and then checkpointed into the DB at regular intervals, so it's expected to grow first. The wal file will grow to about 1000 pages of data before "checkpointed" into the DB. This is all handled by sqlite internally. The max size of a page is 64k - so ideally the WAL file should grow to about 64MB before checkpointed and reduced. However, there are edge cases where checkpoint starvation can occur. It's possible there was some corruption in the DB that was preventing checkpoint, so resyncing was likely the fix for this. Please let us know if you see further related issues
