### ISSUE TITLE
[BUG] Pool protocol on many machines

### ISSUE THREAD

**Issue by SeruousMax** [Chia-Network/chia-blockchain#7464]
Harvester don't add points in 2 machines
machine 1 has 15 plots - increase pool point
machine 2 has 56 plots - don't increase pool point
machine 3 has 243 plots - don't increase pool point

all machines has proofs and log is ok:

Example machine 3:
![image](https://user-images.githubusercontent.com/19412710/125522362-5d9675f3-741d-4569-b6cb-4049e42bb553.png)

Points always equals 2 in all machines:
![image](https://user-images.githubusercontent.com/19412710/125522450-f1fa0a1f-3b0f-4591-b3e0-c91331884ea4.png)

In pool https://mainnet.pool.space only show one harvester:
![image](https://user-images.githubusercontent.com/19412710/125522560-d66a8268-6743-4ce6-809b-74c51b8cd4c4.png)

- OS: Windows, CentOS
- OS Version/Flavor: windows 10, centos 8.2
- CPU: Ryzen 5 2700, Intel 10700kx, vps with 4 vcpu Xeon

Version 1.2.1

**Comment by mariano54** [comment]
Hmm this might be an issue with space pool. have you tried on another pool?

**Comment by jasonyzs** [comment]
I am observing the same thing where the "Current Points Balance" is the same on both my harvesters. I think that is the total points you have earned from all harvesters under the same Launcher ID. The other stats, "Number of Plots", "Points found since start", "Points Found in Last 24hrs" though are unique to each harvester.  The last part, about only one harvester showing up, yes that I agree is an issue. Mine shows both.
