### ISSUE TITLE
syncing

### ISSUE THREAD

**Issue by delmajid** [Chia-Network/chia-blockchain#7568]
Each two days it doesn't sync and it stops on a number and does nothing.
what can I do to solve this problem?
![image](https://user-images.githubusercontent.com/85966895/125957479-b7013395-9bb9-4aed-93db-da56be6be547.png)
![Chia](https://user-images.githubusercontent.com/85966895/125957629-5c07fad2-ca3f-44ed-be5a-0680aa0ab601.jpg)

**Comment by keliew** [comment]
what does `debug.log` say?

**Comment by delmajid** [comment]
Dear Sir, Madam
As I wrote before it doesn't sync and it pauses on a specific number like
the photo I sent you before.
Thank you in advance.


sincerely
M.D

**Comment by keliew** [comment]
> Dear Sir, Madam As I wrote before it doesn't sync and it pauses on a specific number like the photo I sent you before. Thank you in advance. sincerely M.D

Good to check the logs...
https://github.com/Chia-Network/chia-blockchain/wiki/How-to-Check-If-Everything-is-Working-(or-Not)

**Comment by madrigo64** [comment]
Yes sometimes it's happens. #5308
Just restart few times, check connection by this command `ping -t google.com`,  wait a hour
If problem is still there then:
Check if you have free space on drive where config folder of chia
See logs and find errors. https://github.com/Chia-Network/chia-blockchain/wiki/How-to-Check-If-Everything-is-Working-(or-Not)
Try to run this bat file if after this problem is still there then possible problem with port 8444 or DB
Create empty file with name pears.bat
insert this code
`echo off
cd /d %LOCALAPPDATA%\chia-blockchain\app-1.2.2\resources\app.asar.unpacked\daemon

chia show -a node-apne.chia.net:8444

chia show -a introducer-apne.chia.net:8444

chia show -a introducer-apse.chia.net:8444

chia show -a introducer-or.chia.net:8444

chia show -a introducer-va.chia.net:8444

chia show -a introducer-eu.chia.net:8444

chia show -a chiadb.net:8444

chia show -a pyl.dk:8444

chia show -a node.chia.net:8444

chia show -a 81.83.5.50:8444

chia show -a 118.189.201.184:8444

chia show -a 63.86.188.28:8444

chia show -a 70.67.4.75:8444

chia show -a 159.28.171.166:8444

chia show -a 37.145.52.144:8444

chia show -a 123.57.42.226:8444

chia show -a 76.251.32.219:8444

chia show -a 70.224.19.232:8444

chia show -a 73.252.215.180:8444

chia show -a 205.134.173.77:8444

chia show -a 84.107.167.248:8444

chia show -a 86.57.236.161:8444

chia show -a 211.227.132.15:8444

chia show -a 72.39.161.212:8444

chia show -a 201.131.68.254:8444

chia show -a 90.222.8.93:8444

chia show -a 178.82.152.5:8444

chia show -a 24.24.132.82:8444

chia show -a 80.212.44.58:8444

chia show -a 37.193.78.56:8444

chia show -a 65.24.91.237:8444
