### ISSUE TITLE
[BUG]xch_target_address not changed after create a new wallet

### ISSUE THREAD

**Issue by programsalon** [Chia-Network/chia-blockchain#7633]
I install Chia and create a wallet for test, and delete the test wallet and create a new wallet, but xch_target_address in the config.yaml file not changed, it's still test wallet ID. version 1.1.7

**Comment by prichiyak** [comment]
See related topics: #4556 #3141

**Comment by mariano54** [comment]
That is expected behaviour. Your xch_target_address will point to your first key, and can be changed in the farmer page, or in the config directly.

**Comment by BH509er** [comment]
I've lost 3 proofs I think since I noticed and haven't found any proof since changing the address in config.yaml. Still solo mining too, so that's everything I've got since end of April, beginning of May up until now. So I'm pretty happy about that obviously... Is there any way possible way to recover those or is it all just gone??

**Comment by BH509er** [comment]
No way. I'm on the same seed I'm pretty sure though. I'll check...

**Comment by BH509er** [comment]
I'm gonna try to re enter it, but yeah I'm on the same seed, just a different wallet address
![CHIA_GUI_Wallets+Not_Receiving_Rewards](https://user-images.githubusercontent.com/92582023/137644062-15d4e03f-8d7d-4826-8ae2-926af2a8a439.jpg)
.

**Comment by BH509er** [comment]
Unless you manually go in and change it. Actually.... what if I go and do that in reverse?? Put the old address in the config file, it should then show up on the GUI!! I'm tryin it....
