### ISSUE TITLE
Chia Wallet Sync stuck [BUG]

### ISSUE THREAD

**Issue by GiverDead** [Chia-Network/chia-blockchain#7777]
**Describe the bug**

Chia wallet synced 446684 to 450446 about two days. Then stay with status no synced.

**Desktop**

- OS: Windows 10
- Raspberry 4 4GB

**Additional context**
debug.log 

chia,wallet.wallet_node : INFO Have collected 658 potential peaks
chia,wallet.wallet_node : INFO No peers to sync to
chia,wallet.wallet_node : INFO Loop end in sync job

**Comment by tangdasan** [comment]
+1

**Comment by GiverDead** [comment]
When i click "delete not verified transactions" and restart GUI  -  wallet start syncing for 4-6 hours and then freeze again

**Comment by dmitryalexandrow** [comment]
из своего опыта сообщаю,что была аналогичная проблема!! неделю с ней боролся!! пробовал следующие шаги:
1.Обновил Chia до последней версии 1.2.2
1.Закрыл программу
2.если не все задачи закрыты, через диспетчера задач принудительно закрывал все программы.
3.Перезагрузка компьютера
4.Удалить файл db в кошельке
5.Загрузка программы с синхронизацией кошелька..

если опять застрянет на той же высоте...тогда всё тоже самое по шагам, только в пункте 4.  снести всю папку Chia (предварительно скопировав её) и запуск Full Node c начала...все синхронизировалось, включая все транзакции.

Если поможет, значит не зря неделю я боролся с этой проблемой

**Comment by maybeTomorrow** [comment]
me too,then my full node crash

**Comment by GiverDead** [comment]
Wallet sync for 2-3k points and then freeze. I relaunch Chia and again 2-3k. And relaunch again until sync

**Comment by dmitryalexandrow** [comment]
Is node full or not ?
05.08.2021, 14:31, GiverDead < ***@***.*** ***@***.*** >
Wallet sync for 2-3k points and then freeze. I relaunch Chia and again 2-3k. And relaunch again until sync

**Comment by GiverDead** [comment]
![image](https://user-images.githubusercontent.com/15796944/128322678-30d6badc-5a60-4bf3-9bc8-8d14b842a5ae.png)
Yes. It's full

**Comment by dmitryalexandrow** [comment]
Сheck your IP if you have a dynamic one, you need to change it to a static one.You also need to connect port 8444.If you have all this, then the launch options are below There are two options. First, close the program Chia.In the task manager, see that all commands are closed, if there are open ones, close forcibly.Update Chia to the latest version.Restart the computer. delete the folder db chia/mainnet/wallet/db Run the program Chia.Second:Copy the Chia folder to a free disk or USB flash drive. Close the Chia program.In the task manager, see that all commands are closed, if there are open ones, close forcibly.Update Chia to the latest version.Restart the computer. delete the entire Chia folder.Starting full node. In this version, it is mandatory that the directories with the plots are registered, otherwise you will not download them later!!!!!!
05.08.2021, 16:59, GiverDead < ***@***.*** ***@***.*** >
https://user-images.githubusercontent.com/15796944/128322678-30d6badc-5a60-4bf3-9bc8-8d14b842a5ae.png image Yes. It's full
