### ISSUE TITLE
finding to mutch proofs and don't win blocks  +/- 1 every 5 min [BUG]

### ISSUE THREAD

**Issue by abspoel99** [Chia-Network/chia-blockchain#7893]
so im having a problem of finding to mutch proofs...
won't get any reward though, did try find this issue but haven't seen a post about it.

here is a screenshot of what i'm talking about:
![image](https://user-images.githubusercontent.com/29400615/127759901-d5815015-1dd5-494f-a6b3-3f2ebf75c61c.png)

don't know if i am connected to a defect timelord or the proofs just won't get trough?
have 170TB of plots, NFT 20% and 80% OG

**Comment by emlowe** [comment]
Your NFT plots, assuming they are pooling, will find "partial" proofs more often to send to the pool, depending on the pool difficulty (the pool difficulty is set low so that you send partial proofs at regular intervals to validate space). This is normal. Also with any plots, including OG, It's not a 1-1 relationship between finding proofs and farming a block, that is, you can find proofs and not farm blocks as there may have been a better proof. This is also normal.
