### ISSUE TITLE
Add end to end tests of farm health.

### ISSUE THREAD

**Issue by rckjhn** [Chia-Network/chia-blockchain#8078]
**Describe the bug**
A farm may win blocks at a rate substantially below the expected time to win during some time window.

**To Reproduce**
Run a farm and observe the win rates.

There are existing checks on the plot level "chia plots check ...".
Would it be possible to build a tool to check the farm?

**Comment by loppefaaret** [comment]
The shown value for time to win, is an _estimate_ and is subject to the variations in cryptographic blockchains - it is far from uncommon for it to sway *5
The estimation is based on an average amount of wins over time, for a single win.
It is not really an issue we are going to change to be honest, it is the nature of the mathematics that we build on.
When it comes to digging deeper into the setup, and analyzing wether everything is running optimised, there are some pointers on our wiki, and i'm sure there are something to find in our discussions here on github, and i can also recommend our Keybase official chat https://keybase.io/team/chia_network.public

I'm closing this issue with the above noted.

**Comment by Jacek-ghub** [comment]
@loppefaaret, I kind of disagree with your statements.  

There is no point to pull out 5x from your own hat, where Chia UI could do a nice Poisson distribution chart to show where the farm is in the process.  It is a well understood chart when analyzing distributions like chia winning, where your 5x is just another garbage that would confuse most of the people.  Also, a single person whining about winning being late is rather a worthless thing to pursue, looks like there are several people with farms in petabytes that are not receiving any rewards for a month or so, and for one those numbers exceed your 5x a bit, and also adding those farms together make your argument rather as silly as those that ask about winning having just 2 plots.

Why don't you ask for the UI guys to do a similar section that is right now for pools, but that will show harvester stats.  How many plots, what is the ratio of proofs found to those plots, the ratio of partials submitted to those plots, and chart those over time, or rather like on those pool over the last 24 hours, and since started.

Your suggestion that all of us need to start digging into those logs, collecting data, putting it together, where just one of your engineers can do that job over a coffee break is really lame.  Is that really the company policy?

Please take a look at [this](https://github.com/Chia-Network/chia-blockchain/discussions/7939) discussion.

I would ask to to revert closing this issue with the above noted.

**Comment by rckjhn** [comment]
@loppefaaret 

The e2e test is not related to the math/stats.

Here is the result of "chia plot check" which I am sure you have seen.

```2021-08-15T00:54:36.513  chia.plotting.check_plots        : INFO     Testing plot /media/plots/022/plot-k32-2021-05-04-03-22-f8ec...abe9.plot k=32
2021-08-15T00:54:36.514  chia.plotting.check_plots        : INFO     	Pool public key: <...>
2021-08-15T00:54:36.528  chia.plotting.check_plots        : INFO     	Farmer public key: <...>
2021-08-15T00:54:36.528  chia.plotting.check_plots        : INFO     	Local sk: <...>
2021-08-15T00:54:43.568  chia.plotting.check_plots        : INFO     	Proofs 29 / 30, 0.9667```


So clearly it is possible to send challenges on the plot level and expect proofs to be found.
Is it not possible to send a challenge to a harvester that is expected to produce a proof and see that it actually finds it?
"chia harvester check". This check would be a level up in the sense it would check the plots collectively.

For the smaller farmer with longer ETW there is considerable anxiety around "is my farm working" or "am I just being unlucky". This test would answer "is my harvester working at least as well as my plots".
