### ISSUE TITLE
[BUG]5p can't find the block！！！！

### ISSUE THREAD

**Issue by asgadolph** [Chia-Network/chia-blockchain#8153]
I have 5p plots; The block has not been found for more than two consecutive times and seven days this month. All settings are OK and the network is unobstructed. I don't know whether it's me or everyone.

I hope to get a reply and help solve it. Thank you very much!

bter888@163.com

**Comment by markusmazurczak** [comment]
Are you pool mining or solo?
What are 5p plots? Do you have 5 plots?
What are "two consecutive times"?

Why are you that sure that you should have won during "your" consecutive times?

**Comment by max4711qq** [comment]
There are two threads about this. You are in good company unfortunately

https://github.com/Chia-Network/chia-blockchain/discussions/8074

https://github.com/Chia-Network/chia-blockchain/discussions/7939

Chia network is not working as it is supposed to be. Unfortunately the small "farmers" are not aware of this because their time to win is beyond ...

**Comment by asgadolph** [comment]
![Uploading 微信图片_20210823035058.png…]()
![微信图片_20210823035050](https://user-images.githubusercontent.com/84242772/130368199-e8d26091-855f-4ce4-b56f-fdb4cf099862.png)

**Comment by asgadolph** [comment]
![微信图片_20210823035058](https://user-images.githubusercontent.com/84242772/130368220-ac0cee96-5847-48bf-b495-613e052e58bd.png)

**Comment by asgadolph** [comment]
30000og plots burst abnormally! Up to now, the block has been discovered once in 7 days. And 16000 new plots have not found blocks.

**Comment by asgadolph** [comment]
There is a problem with the time when the block was found.

**Comment by emlowe** [comment]
The blockchain is progressing, blocks are being created, and block rewards are being distributed as designed. Just because you aren't farming a block doesn't mean something is wrong. Every block farmed was in fact farmed by someone - which means that they found a valid proof. There are no favourites played in the math. There are plenty of large farmers who on occasion go through stretches where wins seem less often. Check your logs, make sure you lookups are fast and make sure your internet connection is good. You have 28 seconds to get your proof to a timelord.

This sounds like a support question and not a bug report
