### ISSUE TITLE
argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by dutchmulti** [Chia-Network/chia-blockchain#8452]
My chia wallet gave a error out of the blue no more plots... 
When i wanted to add my plots again it gave this "argument of type 'NoneType' is not iterable"
What can this be??

Screenshot:
![afbeelding](https://user-images.githubusercontent.com/34837574/132993913-36faf180-99b0-4f96-9d24-511d57dd7c90.png)

The hard disk is still availble so i gues it has to do with Chia Software? i update it to 1.2.6 

**Desktop**

- OS: windows 10

**Comment by dorifutoben** [comment]
I have this same issue. I have the latest client. I found only one of my hard drives were being recognized. When I attempted to delete the directory locations using GUI, it said I didn't have permission to remove the plot directory. I reinstalled, using Revo uninstaller to uninstall. Reinstalled. I can't add plot directories now says the same issue as you describe.  "argument of type 'NoneType' is not iterable"

**Comment by dorifutoben** [comment]
I had recently upgraded to the newest version and observed this issue. 
I found something that worked for me, thanks to a user 'sdbarrish' who had great info.  
Let me know if it works for you. 
https://github.com/Chia-Network/chia-blockchain/issues/8386#issuecomment-918709606

**Comment by emlowe** [comment]
We need logs put into DEBUG in order to find out where this is coming from.

Please stop the UI, edit config.yml, change `log_level: DEBUG` and restart UI.

The config.yaml and logs are located in your C:\users\[username\.chia directory

**Comment by digitalspaceport** [comment]
I had this happen the other night after a network share fell offline due to me repurposing the machine without removing the share prior in the client. 

Here are the steps I used to correct this.

1) Stop Chia
2) Reboot computer and do not start chia client
3) Open config.yaml in txt editor, find line 171-ish
4) Deleted all plot_directories that start with - ([see pic here for visual of this](https://imgur.com/a/w5BGYH7))
5) save file, exit txt editor
6) restart chia client
7) re-add folder locations after ensuring they are online

This may have to do with the inclusion in 1.2.6 of a cache mechanism for plots, I forget that issue #, but could be a bug.
