### ISSUE TITLE
I won a block, and ask for support and you close the case with no solution

### ISSUE THREAD

**Issue by jealalri** [Chia-Network/chia-blockchain#8564]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/8563

<div type='discussions-op-text'>

<sup>Originally posted by **jealalri** September 22, 2021</sup>
I won a block in space pool, i got this 
Fecha
9/20/21, 10:47 PM
Altura
887426
Hash
1af00ac572a09975433d8bec790998390e93814646fd13c6d1937fad0046c4b9
My farmer Id is: 
0xd86a7d4ff00ca5545c375093756812d094815db40529738fc9f68c6bf8912eb5
the reward wallet where they are suppose to send the token is: xch1f0ctuf9v9yj2rjvqmrvrh4d23y3a8mav8gfc6xrex2nhsslx7yss3u3t3p
and what you do is close the case</div>

**Comment by loppefaaret** [comment]
yes, cause the issues are a place for the users and developers to report and fix problems with the software - not a place for support using said software
you your self already created a soppurt discussion, then opened an issue as well - instead of running multiple places, lets just keep to one place, it makes it much easier to handle
https://github.com/Chia-Network/chia-blockchain/discussions/8542
this is the place for your lost block t be supported

does this make sense to you ?
