### ISSUE TITLE
Add Token, Custom Dialog accepts TAIL without a GENESIS_ID [Bug] 

### ISSUE THREAD

**Issue by darkverbito** [Chia-Network/chia-blockchain#9268]
### What happened?

The AddToken Dialog chia-blockchain-gui/packages/wallet/src/components/wallet/cat/WalletCATCreateExistingSimple.tsx accepts a seemingly invalid TAIL.

run -i /Development/chia-blockchain/chia/wallet/puzzle /Development/chia-blockchain/chia/wallet/puzzles/genesis-by-coin-id-with-0.clvm
(a (i 47 (q 8) (q 2 (i (= 45 2) () (q 8)) 1)) 1)

cdv clsp treehash '(a (i 47 (q 8) (q 2 (i (= 45 2) () (q 8)) 1)) 1)'
493afb89eed93ab86741b2aa61b8f5de495d33ff9b781dfc8919e602b2afa150

It may be desirable to ensure that an invalid TAIL is not accepted in the UI.

### Version

1.2.11.dev248

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by loppefaaret** [comment]
is this happening on testnet7 ?

**Comment by emlowe** [comment]
Since this is a hash, the wallet has no means to determine what is or is not valid (all hashes look the same and one can't go backwards to the actual code) - Note, this isn't creating the CAT, it's creating a CAT wallet that can watch for and receive CAT-related things on the chain. In this case, you create a CAT wallet that will always be zero and never have any of that particular CAT, since the CAT itself cannot exist.
Since we are using a hash here, there is limited input validation available and it will be possible to create such wallets.
