### ISSUE TITLE
[Bug]  Chia light Wallet Beta GUI not opened

### ISSUE THREAD

**Issue by Shadow84444** [Chia-Network/chia-blockchain#9341]
### What happened?

Chia Wallet GUI not opened. On the startup screen show the next message "Connecting to daemon Attempt 672" and attempt number is more and more
![Chia error screen](https://user-images.githubusercontent.com/94826380/142821200-0e72e93a-a323-4675-bde6-12338391c0a6.jpg)

### Version

1.2.11254

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by loppefaaret** [comment]
without the log - i can only guess that it might be a corrupted wallet database - you can try this:
WINDOWS WALLET DATABASE RESET

Close down the Chia app, and open up a PowerShell window, and execute the below command:
```
mv ~\.chia\mainnet\wallet\db\block* ~\Desktop\
```
Then try opening up the Chia app again.
If it worked, you can remove the files we put on the Desktop.
Note that if you got new plots that points to a plotNFT, the wallet needs to sync pass the latest edit before it farms correctly!

**Comment by Shadow84444** [comment]
Dears, I try to use the Chia Wallet GUI, but not Chia GUI. I haven't the directory specified by you.

**Comment by loppefaaret** [comment]
im sorry, yes, i see now that this is the beta light wallet - and not the regular chia client in use
any chance that you might have some logging output in:
```
~\.chia\standalone_wallet\log\debug.log
```
if you can edit paste that into here, or just simply drag'n'drop the file here to attach it - that might shed some ligt on the issue

but from what i can guess, is that the `daemon` that manages the underlying Chia services, is unable to start up - this is mostly due to being unable to lock onto port 54000 - either from a previous stalled daemon process being left behind, or in some cases, such things as Hyper-V are reserving a port range that includes port 54000...
to fic t he first suggestion, you would have to simply reboot and try again.
in the other suggestion, you would need to open up a command prompt or PowerShell window, and execute this command:
`net stop winnat`
then proceed to open up Chia light wallet beta, and once it is up, again, in the command prompt or PowerShell window, start the service we stopped again:
`net start winnat`
